### DISCUSSION TITLE
Support request: Command gets executed after space even when disabled.

### DISCUSSION THREAD

**Discussion by fabiogibson** [aws/codewhisperer-command-line-discussions#101] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When typing command arguments, no matter if I select the argument from the autocomplete or if I type it, when I press space, I expect it to insert the space char and move to the next argument, instead of executing the partial command.

### Actual behaviour

When I start typing a command, the list of arguments shows up, but if I type the argument instead of selecting it from the autocompletion list, when I press space the command is executed. 

### Steps to reproduce

1. disable "Allow instant execution after space"

1.  type: "docker ps", "git add", "poetry env" or any other command, but don't select the argument "ps, add or env" from the autocomplete, type it. Once you press space, the command is executed. 

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 14.4.0 (23E214)
```
