### DISCUSSION TITLE
"IO Error: Permission denied (os error 13)" when executing Shell integrations

### DISCUSSION THREAD

**Discussion by NaotoKubota** [aws/codewhisperer-command-line-discussions#103] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Path to `cw` is supposed to be added to `.bashrc` and `.bash_profile`.

### Actual behaviour

cw is not working and no autocompletion is available.
I got an error like this screenshot:

![image](https://github.com/aws/codewhisperer-command-line-discussions/assets/47266696/9a5e4d3f-7c46-4dbb-8eb6-2cf329c691ec)

Also I tried `/Applications/CodeWhisperer.app/Contents/MacOS/cw doctor` and got this message:

```
✘ bash ~/.bashrc integration check: /Users/Naoto/.bashrc does not source pre integration

  Run cw integrations install dotfiles to reinstall shell integrations for bash
Attempting to fix automatically...
Failed to fix: IO Error: Permission denied (os error 13)


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with cw issue to let us know!
```

I checked the permissions of .bashrc and .bash_profile:
```
$ ls -ltr ~/.bashrc ~/.bash_profile
-rw-r--r--  1 Naoto  staff   369B Mar 14 11:42 /Users/Naoto/.bashrc
-rw-r--r--  1 Naoto  staff   816B Mar 14 13:32 /Users/Naoto/.bash_profile
```

Does anyone have ideas?

### Steps to reproduce

1. Install CodeWhisperer
2. Click Shell integrations

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  - cores: 6
  - mem: 64.00 GB
os-info:
  - macOS 13.6.3 (22G436)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/naoto
  - exe-path: /Applications/CodeWhisperer.app/Contents/MacOS/cw
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - PATH: /Users/Naoto/anaconda3/bin:/Users/Naoto/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
    - __CFBundleIdentifier: com.googlecode.iterm2
```
