### DISCUSSION TITLE
Support request: cw on external ssd presents "Not Found" (MacOS, Mac Air M1 2020)

### DISCUSSION THREAD

**Discussion by hahnandrew** [aws/codewhisperer-command-line-discussions#105] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

cw to boot

Im in a user housed on an external SSD. cw is on the applications folder of my user, but not the absolute path /Applications

downloading cw on the applications folder makes it work fine, but interestingly, if i have both downloaded (cw on ssd user/Applications, /Applications) use cw, quit, delete cw on /Applications, restart cw on the ssd user/Applications, it works, even after logging out. however, after rebooting my system, it goes back to not working. my .zshrc file is configured properly as well.

### Actual behaviour

cw doesn't work:
![Screenshot 2024-03-14 at 10 42 51 PM](https://github.com/aws/codewhisperer-command-line-discussions/assets/58017052/2d7f9189-a912-44a7-95bf-afe95063de89)

cw doctor says no issues
![Screenshot 2024-03-14 at 10 43 12 PM](https://github.com/aws/codewhisperer-command-line-discussions/assets/58017052/3856062a-28a4-41f9-8e88-bf3cae999756)

misc information - i've tried installing via brew as well, to no avail. i tried opening the application executable itself inside the app, but it just gave me the same not found error. i also tried giving codewhisperer full disk access to no avail. 

i uninstalled cw on all and installed it on my /Applications folder, but it is no longer working. I get this error everytime i run and restart cw:
```
✘ CodeWhisperer Integration: cwterm is not running in this terminal, please try restarting your terminal

  CW_TERM=


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with cw issue to let us know!
```

### Steps to reproduce

In a user housed on an external SSD, download CW in the user's Application folder. Run application

### Environment

```yaml
software@dhcp-vl2041-41997 ~ % cw diagnostic

CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Volumes/T7/software
  - exe-path: /Volumes/T7/software/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 45597109c6064c518a0db9e47cc0427f
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Volumes/T7/software/.amplify/bin:/Volumes/T7/software/.gem/bin:/opt/homebrew/opt/ruby/bin:/Volumes/T7/software/.rbenv/shims:/opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/Volumes/T7/software/.pyenv/shims:/Volumes/T7/software/.amplify/bin:/Volumes/T7/software/.nvm/versions/node/v21.7.1/bin:/Volumes/T7/software/.gem/bin:/opt/homebrew/opt/ruby/bin:/Volumes/T7/software/.rbenv/shims:/opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Volumes/T7/software/.local/bin:/Volumes/T7/software/development/flutter/bin:/Volumes/T7/software/development/flutter/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 45597109c6064c518a0db9e47cc0427f
```
