### DISCUSSION TITLE
Docker image tag completion not functioning

### DISCUSSION THREAD

**Discussion by ktika** [aws/codewhisperer-command-line-discussions#107] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Pressing tab should prompt for possible image tag values.

### Actual behaviour

When pressing tab, nothing happens.

<img width="644" alt="Screenshot 2024-03-16 at 22 40 49" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/45484454/ae5c312b-9920-4125-85e2-d820d15151eb">
<img width="565" alt="Screenshot 2024-03-16 at 22 41 06" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/45484454/95896349-409c-4a86-8d11-55156c93bdb7">

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/katikap
  - exe-path: /Users/katikap/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: c85ecaa436444f16b1c0ae13f688cea5
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Users/katikap/.volta/bin:/Users/katikap/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/katikap/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/katikap/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: c85ecaa436444f16b1c0ae13f688cea5
```
