### DISCUSSION TITLE
Support request: Telemetry and other "features" re-enabled without my consent

### DISCUSSION THREAD

**Discussion by bennygoldman** [aws/codewhisperer-command-line-discussions#112] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

My choices to disable telemetry, sharing data with AWS, and enabling "AI" features to be respected  after "upgrading" to Code Whisperer 

### Actual behaviour

All were reenabled without my doing so

### Steps to reproduce

1. Observe and attempt to fix a completely different issue, where "tab" and "enter" keys no longer accept CW's suggestion and place it in the CLI (I will file this report next)
2. Go to CW settings
3. Observe that settings which I had previously disabled immediately upon installing CW were enabled.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/school
  - exe-path: /Users/school/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 03331a7c817e47558f015b9f575b8b85
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.0
    - PATH: /Users/school/.console-ninja/.bin:/opt/homebrew/opt/ruby/bin:/Users/school/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/school/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 03331a7c817e47558f015b9f575b8b85
```
