### DISCUSSION TITLE
Support request: Unable to accept CLI completions using tab or enter

### DISCUSSION THREAD

**Discussion by bennygoldman** [aws/codewhisperer-command-line-discussions#113] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Tab or Enter to accept the completions for the CLI

### Actual behaviour

Both did their standard terminal functionality. Screenshots attached. Same happened in VSCode terminal.

<img width="520" alt="cwPressedEnter" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/c3491fe2-7d1b-4092-847e-3261b0df08eb">
<img width="517" alt="cwPressedTab" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/01d82d8e-0e2b-44a2-a0b9-7359a6f3c29a">
<img width="578" alt="cwAutosuggest" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/adfe2322-2fd1-4eed-ac95-2fa35c137a21">
<img width="617" alt="cdPressedEnter" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/9e2253fe-36a2-4fec-aff5-6cec14ff863c">
<img width="542" alt="cdPressedTab" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/2860b1a4-17e4-47ae-af71-e1eaac9d7e0f">
<img width="577" alt="cdAutosuggest" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7210738/0779552c-14da-4f4c-95ae-19d65b954594">

### Steps to reproduce

Use the CLI and try to accept a completion

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/school
  - exe-path: /Users/school/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 6a06599c48eb4cd8bd2b106047ab7330
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.0
    - PATH: /Users/school/.console-ninja/.bin:/opt/homebrew/opt/ruby/bin:/Users/school/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/school/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 6a06599c48eb4cd8bd2b106047ab7330
```
