### DISCUSSION TITLE
`z` integration only suggests visited paths

### DISCUSSION THREAD

**Discussion by ScottRobinson03** [aws/codewhisperer-command-line-discussions#114] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

All paths should be suggested, whether visited by `z` or not. Paths not visited by `z` should just have a score of e.g. 0 so they just show underneath visited paths (rather than being completely hidden).

### Actual behaviour

Paths are only suggested if you've already visited via `z {path}`.

Somewhat related to #82.

### Steps to reproduce

- Install `z`
- Type `z ` and notice that no paths are suggested
- `z` to a directory (e.g. `z ~/Documents`)
- Notice that directory is now shown in suggestions for `z `

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.3.0 (23D56)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/srn42
  - exe-path: /Users/srn42/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 2f568fcc80a3462daa6071f5c261eb06
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: *redacted*
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 2f568fcc80a3462daa6071f5c261eb06
```
