### DISCUSSION TITLE
Autocomplete renders in wrong place

### DISCUSSION THREAD

**Discussion by jeremycastanza** [aws/codewhisperer-command-line-discussions#116] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

While opening integrated terminal in VSCodium, the autocomplete window should appear near the integrated terminal.

### Actual behaviour

The autocomplete window appears, but is far away from the integrated terminal command line.

### Steps to reproduce

Use VSCodium and open integrated terminal with CodeWhisper CLI installed. 

While using VSCodium a bug presents that's very similar to this issue logged against the Fig repo:
https://github.com/withfig/fig/issues/2058

### Environment

```yaml
# username and cwd have been redacted

CODEWHISPERER-details:
  - 0.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: vscodium
  - cwd: <redacted>
  - exe-path: /Users/<redacted>/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: f1d3abd3804b4ff3a16f9453030db80a
    - CW_SET_PARENT: f1d3abd3804b4ff3a16f9453030db80a
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.0
    - PATH: /Users/<redacted>/.nvm/versions/node/v18.18.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/<redacted>/Library/pnpm:/Users/<redacted>/.nvm/versions/node/v18.18.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/<redacted>/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/<redacted>
    - __CFBundleIdentifier: com.vscodium
```
