### DISCUSSION TITLE
Not working in Mac iTerm2, no pop-ups/completions

### DISCUSSION THREAD

**Discussion by mquinnv** [aws/codewhisperer-command-line-discussions#118] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

to complete like Fig did. it did work briefly after upgrade, but now there is just nothing. i found issue #51 and it said for each affected to post their debug output

### Actual behaviour

[Log] [fig] declaring constants... (user-script:2, line 1)
[Log] [cw] setting up event listeners... (index-A3qZizNF.js, line 85)
[Log] [cw] unsubscribing any existing notifications... (index-A3qZizNF.js, line 85)
[Error] Refused to connect to api://localhost/notificationRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: TypeError: Load failed
[Error] Refused to connect to api://localhost/getSettingsPropertyRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/getLocalStateRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/notificationRequest because it does not appear in the connect-src directive of the Content Security Policy. (x2)
[Error] Refused to connect to api://localhost/installRequest because it does not appear in the connect-src directive of the Content Security Policy. (x3)
[Error] Refused to connect to api://localhost/notificationRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: TypeError: Load failed (x8)
[Error] Refused to connect to api://localhost/telemetryPageRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/getLocalStateRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/authStatusRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/notificationRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: TypeError: Load failed (x4)
[Error] Refused to connect to api://localhost/getSettingsPropertyRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/getLocalStateRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Refused to connect to api://localhost/installRequest because it does not appear in the connect-src directive of the Content Security Policy. (x3)
[Error] Refused to connect to api://localhost/telemetryPageRequest because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: TypeError: Load failed (x6)

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.7.0/bin/fish
  - terminal: iterm
  - cwd: /Users/michael
  - exe-path: /Users/michael/.local/bin/cw
  - install-method: brew
  - env-vars:
    - PATH: /Users/michael/Library/pnpm:/Users/michael/.rbenv/shims:/Users/michael/.rbenv/shims:/Users/michael/.local/bin:/Users/michael/bin://opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin://opt/homebrew/sbin:/usr/local/sbin:/usr/sbin:/sbin:/Users/michael/.sdkman/candidates/java/current/bin:/Users/michael/.sdkman/candidates/gradle/current/bin:/System/Cryptexes/App/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
    - __CFBundleIdentifier: com.googlecode.iterm2
    - SHELL: /opt/homebrew/bin/fish
    - TERM: xterm-256color
    - DISPLAY: /private/tmp/com.apple.launchd.ZjMFgiUvTK/org.xquartz:0
```
