### DISCUSSION TITLE
CodeWhisperer had an Error!: path must be shorter than libc::sockaddr_un.sun_path

### DISCUSSION THREAD

**Discussion by kwittmann-sflx** [aws/codewhisperer-command-line-discussions#119] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When using the terminal in vscode, I expect `cw` to work properly.

### Actual behaviour

![image](https://github.com/aws/codewhisperer-command-line-discussions/assets/109075013/144d821a-68e8-459a-aab0-4af57807bc66)

- When opening a new terminal, I see the error message:

```
CodeWhisperer had an Error!: path must be shorter than libc::sockaddr_un.sun_path
```

- No suggestions or any overlay is displayed anytime.

- `cw doctor` gives the following output:

```

✘ Cwterm: Tried to find the socket file, but it wasn't there.

  CodeWhisperer uses the /tmp directory for sockets.
  Did you delete files in /tmp? The OS will clear it automatically.
  Try making a new tab or window in your terminal, then run `cw doctor` again.
  No file at path: "/var/folders/6z/8f_qtxlx5pgbfl9tskfz02500000gn/T/com.apple.shortcuts.mac-helper//cwrun/t/3d80021c33294741812d3fe3722b71fe.sock"


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with cw issue to let us know!
```

### Steps to reproduce

🤷🏻‍♂️

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/kaiwittmann/Code/schuettflix/gutenberg
  - exe-path: /Users/kaiwittmann/.local/bin/cw
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.microsoft.VSCode
    - PATH: /Users/kaiwittmann/.local/share/fig/plugins/git-open:/Users/kaiwittmann/.dvm/bin:/Users/kaiwittmann/Library/Preferences/netlify/helper/bin:/Users/kaiwittmann/.nvm/versions/node/v20.10.0/bin:/Users/kaiwittmann/.nvm/versions/node/v20.11.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kaiwittmann/.local/share/fig/plugins/git-open:/Users/kaiwittmann/.dvm/bin:/Users/kaiwittmann/Library/pnpm:/Users/kaiwittmann/Library/Preferences/netlify/helper/bin:/Users/kaiwittmann/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/kaiwittmann/.local/bin
    - SHELL: /bin/zsh
    - CW_SHELL: /bin/zsh
    - CW_SET_PARENT_CHECK: 1
    - ZDOTDIR: /Users/kaiwittmann
    - CW_IS_LOGIN_SHELL: 1
    - CW_START_TEXT: 
    - TERM: xterm-256color
    - CW_EXECUTION_STRING: 
    - CW_SET_PARENT: 3d80021c33294741812d3fe3722b71fe
    - CWTERM_SESSION_ID: 3d80021c33294741812d3fe3722b71fe
    - CW_TERM: 0.15.1
```
```
