### DISCUSSION TITLE
Support request:When I use the global terminal in iterm2, when the global terminal moves, the completion prompt still appears at the location where the previous terminal was.

### DISCUSSION THREAD

**Discussion by notdp** [aws/codewhisperer-command-line-discussions#120] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I hope that when my iTerm2 global window moves, the completion prompt for the next command input can also appear in the corresponding position, instead of staying in the original position.

### Actual behaviour

<img width="815" alt="截屏2024-03-21 上午10 46 19" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/32795983/e96ac586-0e3a-4b0c-a624-29ab3adb47f6">

### Steps to reproduce

1. Integrate iterm2

2. Enable iterm2 global terminal

3. Call out the global terminal at any position on the desktop with a shortcut key

4. Use command completion in IDEA built-in terminal

5. Use command completion again in iterm2 global terminal

Then you will find that this time the command completion appears in the first position

At first, I thought it was because the completion prompt couldn't track the movement of the window. Later, I found that when using only iTerm2 or only the IDEA terminal, the completion prompt tracks the movement of windows well.

When both are mixed, however, the position of the completion prompts becomes confused.

In short, when the global terminal of iterm2 is mixed with other terminals (built-in terminal in idea, normal terminal window of iterm2), the completion prompt of the global terminal of iterm2 cannot track the current window position. In the built-in terminal of idea and the normal terminal window of iterm2, the position of completion prompts is correct.

idea info:

IntelliJ IDEA 2023.3.5 (Ultimate Edition)
Build #IU-233.14808.21, built on March 12, 2024

Runtime version: 17.0.10+1-b1087.21 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/notdp
  - exe-path: /Users/notdp/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 259a74bd09b049729094884caed1e7bc
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /Users/notdp/.pyenv/shims:/opt/homebrew/opt/python@3.11/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/notdp/.local/bin:/Users/notdp/Library/Application Support/JetBrains/Toolbox/scripts:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 259a74bd09b049729094884caed1e7bc
```
