### DISCUSSION TITLE
CW throw Malloc error on cd command (macOS)

### DISCUSSION THREAD

**Discussion by gabrielstuff** [aws/codewhisperer-command-line-discussions#121] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Hello, running `cd` and have autocompletion display path / folder / file.

Might be duplicate of : https://github.com/aws/codewhisperer-command-line-discussions/discussions/110

### Actual behaviour

`cd` and then ➜ `cd zsh (cwterm)(15765) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.`

### Steps to reproduce

I really do not know. It was working fine.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/gd/Downloads
  - exe-path: /Users/gd/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 74177653eb7e4a8a8dfa1f2191c69adf
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /Users/gd/Sources/google-cloud-sdk/bin:/Users/gd/.bun/bin:/Users/gd/Library/pnpm:/Users/gd/Library/Caches/fnm_multishells/26948_1711008803272/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/gd/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 74177653eb7e4a8a8dfa1f2191c69adf
```
