### DISCUSSION TITLE
Support request: Can't install Shell integrations properly.

### DISCUSSION THREAD

**Discussion by y-natsui** [aws/codewhisperer-command-line-discussions#122] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I want to complete the installation successfully.

### Actual behaviour

Even though there are no issues with `cw doctor`, and code completion in cw seems to be working, an error occurs at the screenshot section, preventing installation.

<img width="948" alt="スクリーンショット 2024-03-23 18 32 13" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7719254/78b922ef-1e0a-4847-bbb8-0b0616d00779">

### Steps to reproduce

Before installing CodeWhisperer, I manually removed Fig because its version was too outdated. I followed the instructions in the document linked below:
[Uninstall Fig Manually](https://fig.io/user-manual/other/uninstall#manually)

### Environment

```yaml
% cw diagnostic

CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/username
  - exe-path: /Users/username/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 45c294cda7ba4e72badc777f68cd0110
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /Users/username/.rbenv/shims:/Users/username/.nodebrew/current/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/username/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 45c294cda7ba4e72badc777f68cd0110
```
