### DISCUSSION TITLE
Support request: zsh load is slow

### DISCUSSION THREAD

**Discussion by brc-dd** [aws/codewhisperer-command-line-discussions#123] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

`codewhisperer/shell/zshrc.(pre|post).zsh` should take only few ms.

### Actual behaviour

Currently it takes about a second before one can type any command. It was not this noticeable on fig. And it seems like the shell is init twice -- so if you start typing just after opening, a part of command is lost. Can the performance of code whisperer be improved? Maybe some parts can use zsh_async or something 👀 

**Edit:** Sometimes it's faster -- like under 200-300ms. Is this dependent on network? 

### Steps to reproduce

Add this to top and bottom of `~/.zshrc`:

```sh
echo start - "$(perl -MTime::HiRes=time -e 'printf "%.9f\n", time')"

# codewhisperer stuff

echo end - "$(perl -MTime::HiRes=time -e 'printf "%.9f\n", time')"
```

One can get stuff like this:

```
start - 1711188760.072175026
start - 1711188760.361670971
end - 1711188760.979902935
```

You can also try `time  zsh -i -c exit`. It results in output similar to this:

```
zsh -i -c exit  0.19s user 0.08s system 51% cpu 0.509 total
```

zprof doesn't show anything useful

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/divyansh/foo
  - exe-path: /Users/divyansh/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: ac365cc8f36f495e8a43c0e957a8f20d
    - CW_SET_PARENT: ac365cc8f36f495e8a43c0e957a8f20d
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/divyansh/.composer/vendor/bin:/Users/divyansh/.deno/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/divyansh/.local/bin:/Users/divyansh/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/divyansh
    - __CFBundleIdentifier: com.microsoft.VSCode
```
