### DISCUSSION TITLE
Support request: Malloc error constantly

### DISCUSSION THREAD

**Discussion by doreilly257** [aws/codewhisperer-command-line-discussions#124] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

not to display memory error issues constantly.

### Actual behaviour

                             zsh (cwterm)(5272) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

### Steps to reproduce

unknown, it just happens

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/doreilly/Work/AI/search
  - exe-path: /Users/doreilly/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 839e3e1a56ea4e6ead61ad8ba0fe46bd
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /Users/doreilly/Library/pnpm:/Users/doreilly/.warpstream:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Users/doreilly/.cargo/bin:/Users/doreilly/.local/bin:/Users/doreilly/.local/bin:/Users/doreilly/.local/bin:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 839e3e1a56ea4e6ead61ad8ba0fe46bd
```
