### DISCUSSION TITLE
Support request: Can CodeWhisperer be installed in a path other than in /Applications?

### DISCUSSION THREAD

**Discussion by hkhelif** [aws/codewhisperer-command-line-discussions#125] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Execute the CodeWhisperer app just like any other app not installed under the /Applications folder i.e VSCode, Obsidian, etc

### Actual behaviour

CodeWhisperer UI does not work and simply shows "Not Found" 
<img width="1072" alt="Screenshot 2024-03-25 at 15 12 33" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/121366490/0f513d62-d97f-44e8-98b6-b44f53d6b951">

### Steps to reproduce

* Install CodeWhisperer using homebrew under a folder other than /Applications (due to security reasons I do not want to use my Admin user and simply want to install the app in a different folder): 
`HOMEBREW_CASK_OPTS="--appdir=/Users/haithem/personal/00.01.cask" brew install --cask codewhisperer`
* Add `$HOME/.local/bin` to path 
* Login using `cw login`
* Run `cw install`
* Make sure CodeWhisperer post block and pre block are added to my `.zshrc` config 

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/haithem
  - exe-path: /Users/haithem/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: REDACTED
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: REDACTED
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: REDACTED
```
