### DISCUSSION TITLE
Support request:

### DISCUSSION THREAD

**Discussion by codrkoaz** [aws/codewhisperer-command-line-discussions#129] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

It stopped working today, but was working 3 weeks ago.

### Actual behaviour

I tried using my hyper terminal as usual and for some reason whenever i did cd nothing happen when fig merged with cw and got updated it worked so everything was fine but not it doesn't. I think it's because ohmyzsh got updated not to sure.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/koaz
  - exe-path: /Users/koaz/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: b20d9412128b4e6e881d483f246f83f3
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - PATH: /Users/koaz/.console-ninja/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/koaz/.local/bin:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - CW_SET_PARENT: b20d9412128b4e6e881d483f246f83f3
```
