### DISCUSSION TITLE
Support request: Insert selected changing from Enter to anything else does not work

### DISCUSSION THREAD

**Discussion by kar0v** [aws/codewhisperer-command-line-discussions#134] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect when I change the key combination for "insert selected" to work. For example, shift + enter instead of enter should work.

### Actual behaviour

when changing from `enter` to `shift + enter` it does not work, but executes the current line. 

### Steps to reproduce

change `insert selected` key to anything but `enter`

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.3
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/kkarov
  - exe-path: /Users/kkarov/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: c23bcd037255461084fd959257e61fb5
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.3
    - PATH: /Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/kkarov/.nvm/versions/node/v14.17.1/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/Users/kkarov/.local/bin:/Users/kkarov/.local/bin:/Users/kkarov/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: c23bcd037255461084fd959257e61fb5
```
```
