### DISCUSSION TITLE
Support request: CodeWhisperer not working in integrated VS Code terminal

### DISCUSSION THREAD

**Discussion by MarGustafsson** [aws/codewhisperer-command-line-discussions#138] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

CodeWhisperer should show suggestions in both my default terminal and the integrated VS Code terminal since i have integrations for CodeWhisperer enabled.

### Actual behaviour

CodeWhisperer is working in my terminal app (Iterm2), but not in the integrated vs code terminal, that also uses the same shell as iterm, which is zsh.

So in my normal terminal i get completions for everything, but in vscode nothing ever shows up, and `cw doctor` only says that the terminal is not running with the latest integration, and that i should restart. And i have tried hard-quitting Vs code, just killing the integrated terminal, `cw restart`, but nothing helps.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.3
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/marcus
  - exe-path: /Users/marcus/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CW_SET_PARENT_CHECK: 1
    - __CFBundleIdentifier: com.microsoft.VSCode
    - CW_TERM: 0.15.1
    - PATH: /usr/local/sbin//Users/marcus/.bun/bin:/opt/homebrew/opt/php@8.0/sbin:/opt/homebrew/opt/php@8.0/bin:/Users/marcus/.nvm/versions/node/v20.10.0/bin:/Users/marcus/.deno/bin:/opt/homebrew/bin:/usr/local/sbin//Users/marcus/.orbstack/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/marcus/.cargo/bin:/usr/local/sbin//Users/marcus/.bun/bin:/opt/homebrew/opt/php@8.0/sbin:/opt/homebrew/opt/php@8.0/bin:/Users/marcus/.nvm/versions/node/v20.10.0/bin:/Users/marcus/.deno/bin:/opt/homebrew/bin:/usr/local/sbin//Users/marcus/.cargo/bin:/Users/marcus/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: b647f9bf5c2042a8aae16258ba00fd2c
    - SHELL: /bin/zsh
    - CW_SET_PARENT: b647f9bf5c2042a8aae16258ba00fd2c
    - ZDOTDIR: /Users/marcus
```
