### DISCUSSION TITLE
Support request: Alacritty command prompt is covered

### DISCUSSION THREAD

**Discussion by amaduswaray** [aws/codewhisperer-command-line-discussions#142] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The expected behavior of cw is for the window to appear below the shell prompt, so that my current prompt is still visible when typing

### Actual behaviour

The window covers the comand prompt

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.3
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: alacritty
  - cwd: /Users/<user>
  - exe-path: /Users/<user>/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: <id>
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.3
    - PATH: <$PATH>
    - TERM: xterm-256color
    - __CFBundleIdentifier: org.alacritty
    - CW_SET_PARENT: <parent>
```
