### DISCUSSION TITLE
Support request:can't input automatically for cli

### DISCUSSION THREAD

**Discussion by koizumitakao** [aws/codewhisperer-command-line-discussions#144] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

can input automatically for cli

### Actual behaviour

can't input automatically for cli
![画面収録 2024-04-17 10 07 34](https://github.com/aws/codewhisperer-command-line-discussions/assets/155604113/2917aaa6-98f5-486e-af82-c61623a01d14)

### Steps to reproduce
I installed github copilot for cli and then can't input automatically.
but I already have uninstalled github copilot and reintalled codewhisper.
<img width="947" alt="スクリーンショット 2024-04-17 10 03 26" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/155604113/41bdb36f-dfbd-4d6d-8f5b-b1ce90d25540">
<img width="946" alt="スクリーンショット 2024-04-17 10 03 34" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/155604113/62a0eba3-c4ab-4735-abe1-07da668429cb">
<img width="572" alt="スクリーンショット 2024-04-17 10 03 43" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/155604113/2b5af1c7-8120-4f36-9773-1b9afcf630fe">

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.3
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.6.4 (22G513)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/koizumi.takao
  - exe-path: /Users/koizumi.takao/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 69da2b3dc3a74073a105e9454bc559a1
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.3
    - PATH: /Users/koizumi.takao/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/koizumi.takao/.pyenv/shims:/Users/koizumi.takao/.nodenv/shims:/Users/koizumi.takao/.nodenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/koizumi.takao/.local/bin:/opt/homebrew/opt/mysql-client@8.2/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 69da2b3dc3a74073a105e9454bc559a1
```
