### DISCUSSION TITLE
Wrong dropdown placement on Goland

### DISCUSSION THREAD

**Discussion by padmaraj-durian** [aws/codewhisperer-command-line-discussions#146] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expected the dropdown to come properly

### Actual behaviour

Comes somewhere else, sometimes on different display
<img width="623" alt="image" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/94341420/5ab49600-597d-457a-9b0d-9c6b5d70b12e">

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  - cores: 8
  - mem: 64.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /bin/zsh
  - terminal: intellij-goland
  - cwd: /Users/padmaraj/DurianPay/dpay-common
  - exe-path: /Users/padmaraj/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: d28e98df23d34f9c9fdb69c31c672ab4
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /usr/local/go/bin:/Users/padmaraj/go/bin:/Users/padmaraj/.console-ninja/.bin:/Users/padmaraj/.nvm/versions/node/v18.17.1/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/padmaraj/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.goland
```
