### DISCUSSION TITLE
ali

### DISCUSSION THREAD

**Discussion by Booboo213** [aws/codewhisperer-command-line-discussions#147] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

a

### Actual behaviour

a

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 12.7.4 (21H1123)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/ali
  - exe-path: /Users/ali/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 930a655b208d45a5ab33f35d699fcd23
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/ali/Library/Caches/activestate/bin:/Users/ali/.local/ActiveState/StateTool/release/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/ali/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
```
