### DISCUSSION TITLE
maia

### DISCUSSION THREAD

**Discussion by tmaiat** [aws/codewhisperer-command-line-discussions#148] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

In the terminal, no suggestions are proposed.

### Actual behaviour

https://github.com/aws/codewhisperer-command-line-discussions/assets/167820626/f01e73b7-40a8-449c-99cb-1b1d9dc00525

### Steps to reproduce

With each use of the terminal, codewhisperer does not display anything.

### Environment

```yaml
maia@macbookpro-maia ~ % cw diagnostic

CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/maia
  - exe-path: /Users/maia/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 5d0ff806fb7a436fab973a796565337b
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - DISPLAY: /private/tmp/com.apple.launchd.v3LfEqZK6H/org.xquartz:0
    - PATH: /opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/maia/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
maia@macbookpro-maia ~ %
```
