### DISCUSSION TITLE
Autocomplete

### DISCUSSION THREAD

**Discussion by Keroro2139** [aws/codewhisperer-command-line-discussions#149] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete automatically show when I press spacebar.

### Actual behaviour

Autocomplete not show when I press spacebar, it show when I press tab after space.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M3 Pro
  - cores: 11
  - mem: 18.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/aob
  - exe-path: /Users/aob/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 300a6ebed9784ab7bcc1d850e7616dab
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /usr/local/opt/libpq/bin:/Users/admin/Library/pnpm:/Users/aob/.nvm/versions/node/v18.19.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/aob/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
```
