### DISCUSSION TITLE
CW is not stable when enable the Stage Manager

### DISCUSSION THREAD

**Discussion by sonthepham-dev** [aws/codewhisperer-command-line-discussions#150] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

CW always shows the completion popup when the Stage Manager is enabled

### Actual behaviour

When I enable Stage Manager, the completion popup sometimes does not show. CW still works normally when the Stage Manager is disabled.

https://github.com/aws/codewhisperer-command-line-discussions/assets/46697168/35b3e399-236e-4bbe-9828-323696b8f561

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 16.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/irx
  - exe-path: /Users/irx/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: a2e1d00784ab43f3a832367658edf613
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/irx/.sdkman/candidates/java/current/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/irx/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
```
