### DISCUSSION TITLE
aws cli autocompletion doesnt work on iTerm2

### DISCUSSION THREAD

**Discussion by em-daimongkol-tw** [aws/codewhisperer-command-line-discussions#151] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Once I typed 'aws' and space, it should display auto suggestion for the aws commands

### Actual behaviour

Nothing showing

### Steps to reproduce

Type 'aws' and space bar

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/worasitdaimongkol
  - exe-path: /Users/worasitdaimongkol/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 24cbd98cb45f4869a01005461afcb438
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/worasitdaimongkol/.jbang/bin:/Users/worasitdaimongkol/Downloads/google-cloud-sdk/bin:/Users/worasitdaimongkol/.nvm/versions/node/v20.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Users/worasitdaimongkol/.local/bin:/Users/worasitdaimongkol/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
```
