### DISCUSSION TITLE
CodeWhisper noy working with Hyper Terminal

### DISCUSSION THREAD

**Discussion by OAS-Dev** [aws/codewhisperer-command-line-discussions#152] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete automatically show when I press spacebar.

### Actual behaviour

Autocomplete not show when I press Space. Works on Mac Terminal but not in Hyper Terminal

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/arielsaucedo
  - exe-path: /Users/arielsaucedo/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 7f1e41777b3d445fa1204c214b340191
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/arielsaucedo/.console-ninja/.bin:/Users/arielsaucedo/.nvm/versions/node/v20.11.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/arielsaucedo/.local/bin:/usr/local/mysql-8.3.0-macos14-arm64/bin:/Users/arielsaucedo/Library/Android/sdk/emulator:/Users/arielsaucedo/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
```
