### DISCUSSION TITLE
cw doctor complains about invalid CLI path

### DISCUSSION THREAD

**Discussion by mbd-s** [aws/codewhisperer-command-line-discussions#154] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The CodeWhisperer CLI binary is installed in the correct directory.

### Actual behaviour

The binary is installed in two directories:

- /Users/USER/.local/bin/cw
- /Users/USER/.local/bin/q

These are identical (no output from `cmp /Users/USER/.local/bin/q /Users/USER/.local/bin/cw` and the checksums are the same). But `cw doctor` thinks that the binary is in the wrong place:

```
$ cw doctor

✘ Valid CLI path: CLI (/Users/USER/.local/bin/cw) must be in /Users/USER/.local/bin/q


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```

For what it's worth, CodeWhisperer seems to be working OK, but as I run `cw doctor` proactively to alert me to issues, I'd like to remove any false positives.

### Steps to reproduce

```
$ brew install codewhisperer
# open CodeWhisperer app
# open new terminal window
$ cw doctor

✘ Valid CLI path: CLI (/Users/USER/.local/bin/cw) must be in /Users/USER/.local/bin/q


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```

### Environment

```yaml
q-details:
  - 1.0.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.7.1/bin/fish
  - terminal: iterm
  - cwd: /Users/USER
  - exe-path: /Users/USER/.local/bin/q
  - install-method: unknown
  - env-vars:
    - SHELL: /opt/homebrew/bin/fish
    - __CFBundleIdentifier: com.googlecode.iterm2
    - Q_PARENT: 
    - Q_TERM: 1.0.0
    - QTERM_SESSION_ID: 5c526bb6bd7747f591ef341e090053de
    - TERM: xterm-256color
    - PATH: /Users/USER/.krew/bin:/Users/USER/.bun/bin:/Users/USER/work/src:/Users/USER/work:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.local/bin
```
