### DISCUSSION TITLE
Code Whisperer fails to update

### DISCUSSION THREAD

**Discussion by atejada** [aws/codewhisperer-command-line-discussions#155] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Code Whisperer to get updated and run

### Actual behaviour

CodeWhisperer desktop socket exists: CodeWhisperer socket missing
Attempting to fix automatically...
Restarting CodeWhisperer
Failed to fix: failed to launch CodeWhisperer: `failed to connect to socket`

✘ Doctor found errors. Please fix them and try again.

### Steps to reproduce

Open Code Whisperer, it will try to update and then fail

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.4.1 (23E224)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/blag/Blag/io_Codes
  - exe-path: /Users/blag/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 05e697c3b6334bb9a3e66e0d815aed8b
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - DISPLAY: /private/tmp/com.apple.launchd.CjwvV8fqjz/org.xquartz:0
    - PATH: /Users/blag/.opam/default/bin:/Users/blag/.juliaup/bin:/Users/blag/.modular/pkg/packages.modular.com_mojo/bin:/Users/blag/miniconda3/bin:/Users/blag/miniconda3/condabin:/opt/homebrew/opt/curl/bin:/opt/homebrew/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/blag/.bun/bin:/Users/blag/.nvm/versions/node/v16.11.1/bin:/Users/blag/perl5/bin:/Users/blag/8th/bin/mac64:/Users/blag/Blag/icon/bin:/Users/blag/.composer/vendor/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/openssl@1.1/bin:/Applications/factor:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Users/blag/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/blag/V:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/blag/.cargo/bin:/Users/blag/.local/bin:/Users/blag/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
```
