### DISCUSSION TITLE
CodeWhisperer desktop socket exists: CodeWhisperer socket missing

### DISCUSSION THREAD

**Discussion by mattreginaldo** [aws/codewhisperer-command-line-discussions#156] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The CW should be working. The update isn't working either.

### Actual behaviour

I received this error when CW when was updating: failed to update CodeWhisperer: ``

Running 'cw doctor'

Failed to fix: failed to launch CodeWhisperer: `failed to connect to socket`

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with cw issue to let us know!

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.5.0 (23F5049f)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/mateusreginaldo
  - exe-path: /Users/mateusreginaldo/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: e14d79def81b480d84db151d216f7560
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/mateusreginaldo/.nvm/versions/node/v16.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/mateusreginaldo/.local/bin:/Users/mateusreginaldo/Library/Android/sdk/platform-tools:/Users/mateusreginaldo/Library/Android/sdk/tools:/Users/mateusreginaldo/Library/Android/sdk/tools/bin:/Users/mateusreginaldo/Library/Android/sdk/emulator
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
```
