### DISCUSSION TITLE
✘ CodeWhisperer desktop socket exists: CodeWhisperer socket missing

### DISCUSSION THREAD

**Discussion by bryanwonggy** [aws/codewhisperer-command-line-discussions#157] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expected cw to work

### Actual behaviour

Cw doesnt work

### Environment

```yaml
CODEWHISPERER-details:
  - 0.15.4
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 96.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/bryanwong/dev/mozart/services/rails
  - exe-path: /Users/bryanwong/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 0289048d3aa04e419c58740f0f9c1350
    - CW_SET_PARENT: 
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.4
    - PATH: /Users/bryanwong/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/bryanwong/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bryanwong/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/bryanwong/.local/bin:/Users/bryanwong/.orbstack/bin:/Users/bryanwong/.orbstack/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/bryanwong
    - __CFBundleIdentifier: com.microsoft.VSCode
```
