### DISCUSSION TITLE
Q Error every time zsh/Terminal starts or reloads

### DISCUSSION THREAD

**Discussion by ThatGuySam** [aws/codewhisperer-command-line-discussions#158] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I start a Terminal or command line there are no errors

### Actual behaviour

This was also an issue with Fig that I thought was related to support discontinuing. 

Every time a I start a Terminal or run `source ~/.zshrc` I get the follow error twice
```bash
error: unexpected argument '-a' found

  tip: to pass '-a' as a value, use '-- -a'

Usage: q init [OPTIONS] <SHELL> <WHEN>

For more information, try '--help'.

This command may be valid in newer versions of the Q CLI. Try running q update.
```

Even when I strip out everything from my `~/.zshrc` file except for the Q pre/post the error still persists: 
```bash
# Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"

# Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"
```

If I take away the `zshrc.pre.zsh` or `zshrc.post.zsh` lines I get the error once instead of twice. 
If I take away both I get no errors. 

Here's what `q doctor` says
```bash
athena@Athena Code % q doctor

✔ Everything looks good!

  Q still not working? Run q issue to let us know!
 ```
 
 
Here's what `cw doctor` says
 ```bash
 
✘ Valid CLI path: CLI (/Users/athena/.local/bin/cw) must be in /Users/athena/.local/bin/q


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```
But I assume that's an expected error with the transition from cw to q

### Steps to reproduce

It triggers for me anytime I start or reload any zsh command line so I assume it's not happening for everyone. 

Honestly, I have no idea how to troubleshoot anything outside of the zshrc file without reinstalling my whole system. 

If it helps at all here's my `brew list`
<details>
<summary>`brew list`</summary>
<code>
athena@Athena Code % brew list
==> Formulae
abseil				libtiff
act				libtool
aom				libunibreak
applesimutils			libunistring
apr				libuv
apr-util			libvidstab
argon2				libvmaf
aribb24				libvorbis
aspell				libvpx
astrometry-net			libx11
autoconf			libxau
automake			libxcb
awscli				libxdmcp
b2-tools			libxext
bison				libxrender
boost				libyaml
brotli				libzip
c-ares				little-cms2
ca-certificates			llvm
cairo				llvm@16
cask				lz4
certifi				lzo
cffi				m4
cfitsio				mbedtls
chruby				mpdecimal
cjson				mpfr
cloudflared			mpg123
cmake				netpbm
composer			nettle
coreutils			node
curl				numpy
dav1d				oniguruma
deno				openblas
doctl				opencore-amr
docutils			openexr
double-conversion		openjdk@11
duti				openjpeg
edencommon			openldap
emacs				openssl@1.1
fastlane			openssl@3
fb303				openvino
fbthrift			opus
ffmpeg				p11-kit
fizz				pango
flac				pcre2
fmt				php
fnm				pixman
folly				pkg-config
fontconfig			protobuf
freetds				pugixml
freetype			pycparser
frei0r				pyenv
fribidi				python-brotli
fzf				python-certifi
gallery-dl			python-charset-normalizer
gcc				python-idna
gd				python-mutagen
gdbm				python-packaging
gettext				python-requests
gflags				python-setuptools
gh				python-urllib3
giflib				python@3.10
git				python@3.11
glib				python@3.12
glog				rav1e
gmp				readline
gnutls				redis
go				rtmpdump
graphite2			rubberband
gsl				ruby
handbrake			ruby-install
harfbuzz			ruby@3.1
highway				rust
hwloc				scour
icu4c				sdl2
idb-companion			sevenzip
imath				six
isl				snappy
jansson				speex
jasper				sqlite
jpeg-turbo			srt
jpeg-xl				svt-av1
krb5				syncthing
lame				tabby
leptonica			tbb
libarchive			terminal-notifier
libass				tesseract
libavif				theora
libb2				tidy-html5
libbluray			tree-sitter
libevent			unar
libffi				unbound
libgit2				unixodbc
libgit2@1.6			wangle
libidn2				watchman
libmicrohttpd			wcslib
libmpc				webp
libnghttp2			wget
libogg				x264
libpng				x265
libpq				xorgproto
librist				xvid
libsamplerate			xz
libsndfile			yt-dlp
libsodium			ytarchive
libsoxr				z3
libssh				zeromq
libssh2				zimg
libtasn1			zstd

==> Casks
1password			libreoffice
1password-cli			notion-calendar
android-studio			parallels
beeper				postman
chromium			responsively
cinebench			slack
cron				spotify
docker				steam
expo-orbit			tableplus
fig				the-unarchiver
firefox				tower
google-chrome			transmit
google-drive			unpkg
handbrake			visual-studio-code
inkscape			vlc
knime				wondershare-uniconverter
</code>
</details>

### Environment

```yaml
q-details:
  - 1.0.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 96.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: vscode-insiders
  - cwd: /Users/USER/Library/Application Support/amazon-q/shell
  - exe-path: /Users/USER/.local/bin/q
  - install-method: brew
  - env-vars:
    - PATH: /Users/USER/.pyenv/shims:/Users/USER/.asdf/shims:/Users/USER/.asdf/bin:/Users/USER/Library/Caches/fnm_multishells/6130_1714583925549/bin:/Users/USER/Library/Caches/fnm_multishells/6075_1714583925540/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/Users/USER/Library/Caches/fnm_multishells/5305_1714583880824/bin:/Users/USER/Library/Caches/fnm_multishells/5257_1714583880816/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/Users/USER/Library/Caches/fnm_multishells/5011_1714583870453/bin:/Users/USER/Library/Caches/fnm_multishells/4972_1714583870445/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/Users/USER/Library/Caches/fnm_multishells/4661_1714583854901/bin:/Users/USER/Library/Caches/fnm_multishells/4630_1714583854893/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/Users/USER/Library/Caches/fnm_multishells/3394_1714583765239/bin:/Users/USER/Library/Caches/fnm_multishells/3377_1714583765233/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/Library/Caches/fnm_multishells/884_1714570166008/bin:/Users/USER/Library/Caches/fnm_multishells/865_1714570165991/bin:/Users/USER/Library/Application Support/fnm:/usr/local/opt/ruby/bin:/Users/USER/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.fig/bin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.orbstack/bin:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.maestro/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools
    - QTERM_SESSION_ID: 5d80ba56b5834100a324db1091d05026
    - Q_SET_PARENT_CHECK: 1
    - Q_TERM: 1.0.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/USER
    - __CFBundleIdentifier: com.microsoft.VSCodeInsiders
```
