### DISCUSSION TITLE
not recommend (hint) command line

### DISCUSSION THREAD

**Discussion by bunheree** [aws/codewhisperer-command-line-discussions#159] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I need to suggest a command.

### Actual behaviour

Although I run q doctor and q restart, when I use no command is suggested, it's still working normally.

### Environment

```yaml
q-details:
  - 1.0.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/USER/projects/amazonServer/Mirakl
  - exe-path: /Users/USER/.local/bin/q
  - install-method: unknown
  - env-vars:
    - PATH: /Users/USER/Library/Application Support/Herd/bin/:/Users/USER/.nvm/versions/node/v20.1.0/bin:/Users/USER/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin:/Users/USER/.fig/bin
    - QTERM_SESSION_ID: 3bdb8a047a3a4f5397aa5a350b07be26
    - Q_SET_PARENT_CHECK: 1
    - Q_TERM: 1.0.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
```
