### DISCUSSION TITLE
Feat: play nicely with BLE bash plugin

### DISCUSSION THREAD

**Discussion by MustCodeAl** [aws/codewhisperer-command-line-discussions#16] [Feature request]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocompletion should still show up even with there are inline suggestions with [BLE](https://github.com/akinomyoga/ble.sh)
It does when im using zsh with with [autosuggestions](https://github.com/zsh-users/zsh-autosuggestions)

### Actual behaviour

The autocomplete isn't working with bash's ble when there is a suggestion inline

https://github.com/aws/codewhisperer-command-line-discussions/assets/87888006/61760d1f-206e-443b-b3ea-ba7008a5d3a0

### Steps to reproduce

By messing with the delay of the inline suggestion it makes the autocompletion stay open longer

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /opt/homebrew/Cellar/bash/5.2.21/bin/bash
  - terminal: iterm
  - cwd: /Users/albertdoh
  - exe-path: /Users/albertdoh/.local/bin/cw
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/zsh
    - CWTERM_SESSION_ID: 4d58415cc3974259b5cf1a34797d6cd2
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: w0t0p0:01121C12-DCE8-4900-9D40-5E54F2D6F54A
    - TERM: xterm-256color
    - CW_TERM: 0.12.0
    - CW_SET_PARENT_CHECK: 1
    - PATH: /opt/homebrew/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/opt/libpq/bin:/usr/local/opt/ruby@2.7/bin:/opt/homebrew/opt/bison/bin:/Users/albertdoh/.cargo/bin:/opt/local/sbin:/usr/local/bin:/opt/homebrew/bin:/Users/albertdoh/.fig/bin:/Users/albertdoh/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/albertdoh/.nvm/versions/node/v21.2.0/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/albertdoh/opt/anaconda3/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/opt/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
```
