### DISCUSSION TITLE
Shell Integration to AMazon Q CLI

### DISCUSSION THREAD

**Discussion by awshakank** [aws/codewhisperer-command-line-discussions#163] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I received an error as below when I click on Install for Shell Integrations in Amazon Q for CLI

### Actual behaviour

![image](https://github.com/aws/q-command-line-discussions/assets/168870040/be1dfe15-201c-44c6-9095-074938cfddbf)

### Steps to reproduce

Anytime when I click on Install button

### Environment

```toml
[q-details]
version = "1.0.1"
hash = "767df561558b38ffd4267e16f82dd563d04231c7"
build-datetime = "2024-05-02T19:01:32.842336Z (1d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/.config/fish"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/miniconda3/bin:/Users/USER/miniconda3/condabin:/opt/homebrew/opt/awscli@1/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/USER/.local/bin"
QTERM_SESSION_ID = "eceaac6f3ea345c89dbd5aa9fdf401f9"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
