### DISCUSSION TITLE
Autocompletion pane doesn't show up despite checks passing with flying colours

### DISCUSSION THREAD

**Discussion by ayadagain** [aws/codewhisperer-command-line-discussions#164] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocompletion pane to show up

### Actual behaviour

The autocompletion pane doesn't show up despite passing all the checks. It doesn't work; I've tried it in VS Code terminal, macOS terminal, and JetBrains terminal. I've tried reinstalling, but to no avail

### Environment

```toml
[q-details]
version = "1.0.1"
hash = "767df561558b38ffd4267e16f82dd563d04231c7"
build-datetime = "2024-05-02T19:01:32.842336Z (3d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Developer/tam/verse"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "PyCharm Professional"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.sdkman/candidates/java/current/bin:/Users/USER/.pyenv/shims:/Users/USER/.nvm/versions/node/v16.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/fvm/default/bin:/Users/USER/gocode/bin"
QTERM_SESSION_ID = "281bb3904e1b4469992f2990462e0464"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.jetbrains.pycharm"
```
