### DISCUSSION TITLE
Doctor command fails on .profile check

### DISCUSSION THREAD

**Discussion by corey-cole** [aws/codewhisperer-command-line-discussions#165] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

CLI integration should not give incorrect errors.  Q doctor should correctly identify issues. Q integrations install dotfiles should identify issues with Q-generated content and correct it.

### Actual behaviour

Q integration with iTerm2 gives file-not-found errors during startup.  Q doctor (and related subcommands) give false positive errors.

```bash
❯ q doctor

✘ bash ~/.profile integration check: /Users/bcorecol/.profile does not source pre integration first

  Run q integrations install dotfiles to reinstall shell integrations for bash
Attempting to fix automatically...
Re-running check...

✔ bash ~/.profile integration check
✘ bash ~/.bash_profile integration check: /Users/bcorecol/.bash_profile does not source pre integration first

  Run q integrations install dotfiles to reinstall shell integrations for bash
Attempting to fix automatically...
Re-running check...

✔ bash ~/.bash_profile integration check
✔ Everything looks good!

  Amazon Q still not working? Run q issue to let us know!


~ took 7s
❯ ls -l ~/.profile
-rw-r--r--@ 1 bcorecol  staff  2425 May  5 12:17 /Users/bcorecol/.profile

~
❯ cat !$
cat ~/.profile
# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash"
# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/profile.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/profile.pre.bash"
# Q pre block. Keep at the top of this file.
# Q pre block. Keep at the top of this file.

❯ head ~/.bash_profile
# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash"
# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/profile.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/profile.pre.bash
```

### Environment

```toml
[q-details]
version = "1.0.1"
hash = "767df561558b38ffd4267e16f82dd563d04231c7"
build-datetime = "2024-05-02T19:01:32.842336Z (3d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/bash/5.2.26/bin/bash"
shell-version = "5.2.26"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.cargo/bin:/Users/USER/.rbenv/shims:/Users/USER/.pyenv/shims:/Users/USER/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.local/bin:/Users/USER/.toolbox/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
QTERM_SESSION_ID = "33637bf34735433b858b39c269f1c5dc"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.1"
SHELL = "/opt/homebrew/bin/bash"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
