### DISCUSSION TITLE
Permissions issue with shell integrations

### DISCUSSION THREAD

**Discussion by Sureshkumars** [aws/codewhisperer-command-line-discussions#167] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I installed Q, it asked me for shel integrations and just want it to be completed successfully.
![Screenshot 2024-05-06 at 10 40 43 AM](https://github.com/aws/q-command-line-discussions/assets/6508053/7274f0a1-9703-4115-9b78-b74d9341650b)

### Actual behaviour

When I installed Q, it asked me for shel integrations but it is failing to complete saying some IO permissions denied. q doctor says everything is fine but I still see that issue in the app.

### Environment

```toml
[q-details]
version = "1.0.1"
hash = "767df561558b38ffd4267e16f82dd563d04231c7"
build-datetime = "2024-05-02T19:01:32.842336Z (4d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M2 Pro"
total-cores = 12
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/miniconda3/bin:/opt/miniconda3/condabin:/Users/USER/.nvm/versions/node/v18.19.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "fe4b2013ebc745beb26aab24c55d45e4"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
