### DISCUSSION TITLE
Error on restart when updating

### DISCUSSION THREAD

**Discussion by xlxs4** [aws/codewhisperer-command-line-discussions#169] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When opening Q with `q restart`, it automatically updated. I would expect no "errors" to be reported, since everything worked as it should (i.e. pop up with update progress -> q launched properly when update was finished).

### Actual behaviour

While everything seemed to work nominally, there was an error print: `error: failed to launch: failed to connect to socket`
<img width="778" alt="image" src="https://github.com/aws/q-command-line-discussions/assets/54778816/1f0b8ef5-f07a-4cf3-9415-1b9005a3b60f">

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (2d ago)"

[system-info]
os = "macOS 14.5.0 (23F5074a)"
chip = "Apple M2 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.nvm/versions/node/v21.5.0/bin:/Users/USER/.juliaup/bin:/opt/homebrew/opt/grep/libexec/gnubin:/Users/USER/.cargo/bin:/Users/USER/.emacs.d/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/usr/local/go/bin:/Users/USER/.local/bin:/opt/homebrew/opt/fzf/bin"
QTERM_SESSION_ID = "9ce8f82120e446e4920315f14704f769"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
