### DISCUSSION TITLE
have to enter a space before first character for the context menu to appear

### DISCUSSION THREAD

**Discussion by TheSolly** [aws/codewhisperer-command-line-discussions#170] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I enter a command like `cd` and press space the context menu should appear.

<img width="861" alt="image" src="https://github.com/aws/q-command-line-discussions/assets/31882844/2e6d5aa4-9371-4676-a498-4d46fa4b85d4">

### Actual behaviour

I have to enter a space first then my command like `cd`, and then the context menu appears.

<img width="866" alt="image" src="https://github.com/aws/q-command-line-discussions/assets/31882844/e9deef1e-7674-424e-9bd5-f0ed2fbb8a70">

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (2d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Documents
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.rbenv/shims:/Users/USER/.rbenv/shims:/opt/homebrew/opt/llvm/bin:/Users/USER/google-cloud-sdk/bin:/Users/USER/bin:/opt/homebrew/bin:/usr/local/bin:/Users/USER/.fastlane/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/Users/USER/bin:/Users/USER/.zplug/bin:/Users/USER/.nvm/versions/node/v21.7.2/bin:/Users/USER/.rbenv/shims:/opt/homebrew/opt/llvm/bin:/Users/USER/google-cloud-sdk/bin:/Users/USER/bin:/opt/homebrew/bin:/usr/local/bin:/Users/USER/.fastlane/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/opt/homebrew/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/opt/homebrew/opt/fzf/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools"
QTERM_SESSION_ID = "713a22daa27a46cd857e62f75db0b07b"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
