### DISCUSSION TITLE
使用q，q login选择 Sign up or Sign in with Email (Builder ID)，之后不知道怎么用了

### DISCUSSION THREAD

**Discussion by liuhao16** [aws/codewhisperer-command-line-discussions#172] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

我想在ssh中使用q
<img width="504" alt="image" src="https://github.com/aws/q-command-line-discussions/assets/39983417/77dcce2a-eb40-4723-a892-410ef8e2f0a2">
接下来我ying应该这么操作

### Actual behaviour

我想在ssh中使用q

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (4d ago)"

[system-info]
os = "macOS 13.5.1 (22G90)"
chip = "13th Gen Intel(R) Core(TM) i5-13400F"
total-cores = 6
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/work/code/node"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/anaconda3/condabin:/Users/USER/.nvm/versions/node/v20.10.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts"
QTERM_SESSION_ID = "a502a69a68954990a1287c2367b0f947"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
