### DISCUSSION TITLE
autocomplete not works

### DISCUSSION THREAD

**Discussion by indrapalijama** [aws/codewhisperer-command-line-discussions#173] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

  autocomplete is working

### Actual behaviour

autocomplete not working

### Steps to reproduce

just run command as usual

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (7d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.local/share/fig/plugins/git-open:/opt/homebrew/opt/postgresql@15/bin:/Users/USER/.deta/bin:/Users/USER/.rd/bin:/opt/homebrew/Caskroom/miniconda/base/bin:/Users/USER/.bun/bin:/Users/USER/Oracle:/Users/USER/Library/Android/sdk/emulator:/Users/USER/.nvm/versions/node/v18.14.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/usr/local/go/bin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Developer/flutter/bin"
QTERM_SESSION_ID = "84bc9ddc9984418093513be6857aab5b"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
