### DISCUSSION TITLE
Amazon Q Command Line Jet Brains Rider SDK: Enables "support for screen readers"  on restart of IDE

### DISCUSSION THREAD

**Discussion by shari-vari** [aws/codewhisperer-command-line-discussions#174] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

![Screenshot 2024-05-14 at 14 51 58](https://github.com/aws/q-command-line-discussions/assets/24223078/05a4767f-c7de-4834-b97c-b6f02891b05f)

Screen reader should be unticked. Tooltips on UI are abvailable

### Actual behaviour

On restart of Rider, Appearance>Accessibilty>Suport screen readers is ticked and tooltips are disabled.

### Steps to reproduce

1. Install Amazon Q for Command Line Plugin
2. Restart Rider IDE
3. Hover mouse over menu items and see that tooltips are disabled
4. Check settings, Appearance>Accessibilty>Suport screen readers - box is ticked
5. Untick box and save - note tooltips have returned
6. Repeat steps 2 - 4 and note that Appearance>Accessibilty>Suport screen readers box is ticked again
7. Untick the box and save
8. Disable Amazon Q for Command Line plugin and save
9. Repeat steps 2 - 4 and note that the box has remained unticked and tooltips are available.
10. Re-enable Amazon Q for Command Line
11. Repeat steps 2-4 and note that Support screen reader box is once again ticked

This is incredibly irritating as it took me a while to figure out why my tooltips weren't working.
Related to https://github.com/aws/q-command-line-discussions/discussions/166 

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (7d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/google-cloud-sdk/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Privileges.app/Contents/Resources:/opt/homebrew/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/munki:/Users/USER/.local/bin"
QTERM_SESSION_ID = "bc2907d4d7b540998871b13910f320fc"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
