### DISCUSSION TITLE
Autocomplete popup displayed at the top of Kitty terminal

### DISCUSSION THREAD

**Discussion by baoduong** [aws/codewhisperer-command-line-discussions#175] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete popup should work normally with Kitty terminal

### Actual behaviour

Autocomplete popup  always display at bottom of Kitty

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (7d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Volumes/BAODUONG/NSC/Andromeda/Androweb Kiosk/src/andromeda.androweb.kiosk.client"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Kitty"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/Library/pnpm:/Users/USER/anaconda3/bin:/Users/USER/.nvm/versions/node/v16.20.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/kitty.app/Contents/MacOS:/Users/USER/.local/bin:/Users/USER/.dotnet/tools"
QTERM_SESSION_ID = "45086f2d80534800afed840bd86f05bb"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-kitty"
__CFBundleIdentifier = "net.kovidgoyal.kitty"
```
