### DISCUSSION TITLE
Socket exists but could not connect: Connection refused (os error 61)

### DISCUSSION THREAD

**Discussion by GOWxx** [aws/codewhisperer-command-line-discussions#177] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Normal operation

### Actual behaviour

q doctor

✘ Qterm Socket Check: Socket exists but could not connect: Connection refused (os error 61)

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!

### Steps to reproduce

run `q doctor`

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (9d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/code/unGit/first-learn-html-js-react-next"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Zed"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.T1o0jiptea/org.xquartz:0"
PATH = "/Users/USER/code/unGit/deps/depot_tools:/opt/homebrew/opt/postgresql@15/bin:/Users/USER/Library/Android/sdk/ndk/27.0.11718014/toolchains/llvm/prebuilt/darwin-x86_64/bin:/Users/USER/Library/pnpm:/opt/homebrew/opt/openjdk/bin:/Users/USER/.pyenv/shims:/Users/USER/.nvm/versions/node/v20.10.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/Users/USER/code/unGit/deps/depot_tools:/opt/homebrew/opt/postgresql@15/bin:/Users/USER/Library/Android/sdk/ndk/27.0.11718014/toolchains/llvm/prebuilt/darwin-x86_64/bin:/Users/USER/Library/pnpm:/opt/homebrew/opt/openjdk/bin:/Users/USER/.nvm/versions/node/v20.10.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.orbstack/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools"
QTERM_SESSION_ID = "d53170c551814a71b352b2bd49ebc427"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "dev.zed.Zed"
```
