### DISCUSSION TITLE
Fig plugins unsupported?

### DISCUSSION THREAD

**Discussion by tpluscode** [aws/codewhisperer-command-line-discussions#178] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Are there plans to re-enable support for the "400+" community plugins which fig had supported?

### Actual behaviour

Plugins disappeared when I updated to latest Amazon Q

### Steps to reproduce

Install Q for command line

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (9d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz"
total-cores = 8
memory = "40.00 GB"

[environment]
cwd = "/Users/USER/projects/zazuko/lindas-metadata"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "IDEA Ultimate"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.rvm/gems/ruby-3.0.0/bin:/Users/USER/.rvm/gems/ruby-3.0.0@global/bin:/Users/USER/.rvm/rubies/ruby-3.0.0/bin:/Users/USER/.lando/bin:/Users/USER/.jenv/shims:/Users/USER/.jenv/bin:/usr/local/opt/curl/bin:/Users/USER/.pyenv/shims:/Users/USER/.zinit/polaris/bin:/Users/USER/.nvm/versions/node/v18.19.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/MacGPG2/bin:/Users/USER/projects/zazuko/lindas-metadata/node_modules/.bin:/Users/USER/.local/bin:/Users/USER/.local/bin:/Users/USER/.rvm/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "257d667340f949a1a2ad67dc761fe515"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.jetbrains.intellij"
```
