### DISCUSSION TITLE
Does not work in hotkey fullscreen/quake mode

### DISCUSSION THREAD

**Discussion by andruu** [aws/codewhisperer-command-line-discussions#179] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The typeahead should show up when I start typing

### Actual behaviour

Nothing

### Steps to reproduce

Set a quake terminal using iTerm2

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (10d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M3 Max"
total-cores = 14
memory = "36.00 GB"

[environment]
cwd = "/Users/USER/Herd/prima"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/anaconda3/bin:/Users/USER/anaconda3/condabin:/Users/USER/Library/Python/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.local/share/nvm/v21.7.3/bin:/Users/USER/Library/Application Support/Herd/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "0f3fe0a6522448e09086abeea06fe0e4"
Q_PARENT = ""
Q_TERM = "1.0.2"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
