### DISCUSSION TITLE
Cutting off long commands

### DISCUSSION THREAD

**Discussion by stephenmsachs** [aws/codewhisperer-command-line-discussions#18] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Running `cw ai` should output full length command.

### Actual behaviour

Command is cut-off at some point.

### Steps to reproduce

$ cw ai
list all ebs volumes attached to instances with tag parallelcluster==3.7.1

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /bin/bash
  - terminal: terminal
  - cwd: /Users/stesachs/.emacs.d
  - exe-path: /Users/stesachs/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - CWTERM_SESSION_ID: 28e264d968e5478d9920dc2aa72d96e3
    - CW_TERM: 0.12.0
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT_CHECK: 1
```
