### DISCUSSION TITLE
[macos sonoma] Amazon q not fully working in vscode terminal panel

### DISCUSSION THREAD

**Discussion by knarfben** [aws/codewhisperer-command-line-discussions#180] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I have Amazon Q App installed and it works in the Terminal app.
I'm also using the vscode extension for Amazon Q. So in vscode, if I open a terminal panel, I have no auto complete and `q doctor` reports the following:

```
✗ q doctor

✘ Qterm Socket Check: qterm socket write timed out after 1s


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```

### Actual behaviour

Auto complete works

### Steps to reproduce

type `cd ` (space after cd) 

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (11d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/dev/tenable/tenable-grid"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.nvm/versions/node/v20.10.0/bin:/Users/USER/Library/Python/3.9/bin:/opt/homebrew/bin:/Users/USER/.local/bin:/Users/USER/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/Users/USER/.nvm/versions/node/v20.10.0/bin:/Users/USER/Library/Python/3.9/bin:/opt/homebrew/bin:/Users/USER/.local/bin:/Users/USER/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin"
QTERM_SESSION_ID = "49fdc6dec58444db9a0126274432dc7b"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
