### DISCUSSION TITLE
dont work

### DISCUSSION THREAD

**Discussion by stdnk-a** [aws/codewhisperer-command-line-discussions#181] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Before the update it worked stably

### Actual behaviour

prompts for quick work do not appear after idle time

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (12d ago)"

[system-info]
os = "macOS 12.7.4 (21H1123)"
chip = "Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz"
total-cores = 2
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.8"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "332870d1c0ae44ad9c4b9a9a363f9a44"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
