### DISCUSSION TITLE
Not working on cursor

### DISCUSSION THREAD

**Discussion by kisukeyas** [aws/codewhisperer-command-line-discussions#183] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Type cd and it will be completed.

### Actual behaviour

Completion doesn't work

![スクリーンショット 2024-05-21 11 30 24](https://github.com/aws/q-command-line-discussions/assets/96935761/da247cd8-59e5-4cf5-b6dd-17a5945285e6)
![スクリーンショット 2024-05-21 11 30 41](https://github.com/aws/q-command-line-discussions/assets/96935761/e8df6705-74a2-4b6b-81d9-55c466c2223b)

### Steps to reproduce

Press "cursor ." from iTerm to launch cursor

Completion works in iTerm but not in Cursor
![スクリーンショット 2024-05-21 11 33 19](https://github.com/aws/q-command-line-discussions/assets/96935761/57aadf45-776c-4bf8-85e8-b9a725509121)
![スクリーンショット 2024-05-21 11 33 32](https://github.com/aws/q-command-line-discussions/assets/96935761/b08a8aa3-39e6-4af1-a420-54154e68c790)
![スクリーンショット 2024-05-21 11 33 44](https://github.com/aws/q-command-line-discussions/assets/96935761/6a48b66a-0728-4afa-a982-0814c6bc5efe)

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (13d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M3 Pro"
total-cores = 11
memory = "18.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Cursor"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.pyenv/shims:/Users/USER/.pyenv/bin:/Users/USER/Library/Caches/fnm_multishells/9074_1716258232922/bin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/Library/Caches/fnm_multishells/8595_1716258206590/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "3d83c01c29734026a5aab57332b58e30"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.todesktop.230313mzl4w4u92"
```
