### DISCUSSION TITLE
Not working in Jetbrains terminals

### DISCUSSION THREAD

**Discussion by provoke** [aws/codewhisperer-command-line-discussions#184] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Q would work in the Jetbrains terminal

### Actual behaviour

Q did not work

### Steps to reproduce

follow instructions, restart computer, not working. q doctor reports all is well. Works in other terminals fine.

### Environment

```toml
[q-details]
version = "1.0.2"
hash = "1bc4456c8a90e3eec0e2d6954822c014954c1ae8"
date = "2024-05-07T16:37:16.143212Z (13d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2 Max"
total-cores = 12
memory = "96.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.jenv/shims:/Users/USER/.jenv/bin:/Users/USER/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/opt/grep/libexec/gnubin:bin:/Users/USER/.local/bin:/Users/USER/.config/emacs/bin:gems/bin:/Users/USER/.bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/Users/USER/.nix-profile/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/usr/X11/bin"
QTERM_SESSION_ID = "fb2ec23095104d72875fa82110a501e6"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.0.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
