### DISCUSSION TITLE
Autocompletion not working on ZSH

### DISCUSSION THREAD

**Discussion by pibenett** [aws/codewhisperer-command-line-discussions#185] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The autocompletion to work in any ZSH terminal

### Actual behaviour

The autocompletion stopped to work on zsh terminals but still work on a bash terminal.
I don't know if it might be related but I have this non-blocking error when I start a term: /Users/pierrebenedetto/.zshrc:117: parse error near `>'

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (13h ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/Dev projects/BnetDev/BouyguesImmo/Commerce.Crm.Bi"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "f1e961771fb144469725007ae5e17f52"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
