### DISCUSSION TITLE
mac

### DISCUSSION THREAD

**Discussion by KirbyMondragon** [aws/codewhisperer-command-line-discussions#186] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

i dont know

### Actual behaviour

nothing

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (1d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/development/flutter/bin:/Users/USER/.nvm/versions/node/v20.6.0/bin:/Users/USER/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "f47809921cdd470fa4c114e5efc69da1"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
