### DISCUSSION TITLE
Allow setting trusted certs

### DISCUSSION THREAD

**Discussion by david-moskovitz** [aws/codewhisperer-command-line-discussions#187] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Q Autocomplete to showing up

### Actual behaviour

Q Autocomplete not working, most probably b/c I have a VPN setup and I need to set the VPN cert to Q

### Steps to reproduce

Use A VPN?

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (2d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M2 Max"
total-cores = 12
memory = "96.00 GB"

[environment]
cwd = "/Users/USER/Developer/Work/web-app"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode Insiders"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.bun/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.docker/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin:/Users/USER/.bun/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.docker/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.fig/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "2d09a95eb9ee41d08892b37ddc824298"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCodeInsiders"
```
