### DISCUSSION TITLE
error while writting, im getting this error : zsh (qterm)(16532) MallocStackLogging: can't turn off malloc stack logging because it was not enabled. zsh (qterm)(16533) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

### DISCUSSION THREAD

**Discussion by raebeb** [aws/codewhisperer-command-line-discussions#188] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

type and get the suggestions in the drop menu

### Actual behaviour

every time I'm trying to run any command (git, docker, python, etc) im getting this as I type 
`zsh (qterm)(16532) MallocStackLogging: can't turn off malloc stack logging because it was not enabled. zsh (qterm)(16533) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.`
sometimes work fine and show me the drop menu with the suggestions but after an update of iTerm I started getting this

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (3d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER/Dev/mbai-pm-core"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/anaconda3/envs/MontBlancAi_venv/bin:/Users/USER/anaconda3/condabin:/opt/homebrew/opt/postgresql@15/bin:/usr/local/opt/postgresql@15/bin:/usr/local/opt/postgresql@15/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "d73d72989c7946228fa9b6ed4991207d"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
