### DISCUSSION TITLE
qterm is not running

### DISCUSSION THREAD

**Discussion by FastBoot3DS** [aws/codewhisperer-command-line-discussions#189] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Using CodeWhispers over SSH should show the command line completions when Amazon Q is installed on both the macOS Host ad the Debian Linux Server

### Actual behaviour

The command line completion window doesnt show and `q doctor` returns the following:
<img width="896" alt="Screenshot 2024-05-25 at 4 29 15 PM" src="https://github.com/aws/q-command-line-discussions/assets/120575219/97ce9121-7866-484e-8a3c-20e634f65514">

### Steps to reproduce

1. Log In to MY server over SSH
2. run `q doctor`
3. See error message

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "arn:aws:s3:::fig-io-desktop-pipeline-artifacts-158872659206-us-west-2/FigIoDesktop-Pipelin/figIoDeskt/uKWARoV"
date = "2024-05-21T20:19:55.085016Z (4d ago)"

[system-info]
chip = "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz"
total-cores = 4
memory = "7.70 GB"

[system-info.os.Linux]
kernel_version = "6.1.0-21-amd64"

[system-info.os.Linux.os_release]
id = "debian"
name = "\"Debian GNU/Linux\""
version_id = "\"12\""
version = "\"12 (bookworm)\""

[environment]
cwd = "/home/USER"
cli-path = "/home/USER/.local/bin/q"
shell-path = "/usr/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/bin:/usr/bin:/bin:/usr/games:/home/USER/.local/bin"
Q_SET_PARENT_CHECK = "1"
SHELL = "/usr/bin/zsh"
TERM = "xterm-256color"
XDG_SESSION_TYPE = "tty"
```
