### DISCUSSION TITLE
cw does not work in integrated vscode terminal

### DISCUSSION THREAD

**Discussion by konfortes** [aws/codewhisperer-command-line-discussions#19] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

cw is working in vscode integrated terminal

### Actual behaviour

doesn't work. (It does work in another terminal - Iterm2)
`cw doctor` results in the following error:
```
Cwterm: Socket exists but could not connect: Connection refused (os error 61)
```

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M3 Pro
  - cores: 11
  - mem: 18.00 GB
os-info:
  - macOS 14.1.0 (23B2073)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/ronenkonfortes/work/rewire
  - exe-path: /Users/ronenkonfortes/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CW_SET_PARENT_CHECK: 1
    - __CFBundleIdentifier: com.microsoft.VSCode
    - CW_TERM: 0.12.0
    - PATH: /Users/ronenkonfortes/work/google-cloud-sdk/bin:/Users/ronenkonfortes/.nvm/versions/node/v16.20.2/bin:/opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/ronenkonfortes/.pyenv/shims:/Users/ronenkonfortes/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ronenkonfortes/work/google-cloud-sdk/bin:/Users/ronenkonfortes/.nvm/versions/node/v16.20.2/bin:/opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/ronenkonfortes/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ronenkonfortes/.local/bin
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: 5052ff9786374d14a551cfc179d5af1a
    - SHELL: /bin/zsh
    - CW_SET_PARENT: 5052ff9786374d14a551cfc179d5af1a
    - ZDOTDIR: /Users/ronenkonfortes
```
```
