### DISCUSSION TITLE
Autocomplete no working after iTerm update to 2.3.5

### DISCUSSION THREAD

**Discussion by vjkamath** [aws/codewhisperer-command-line-discussions#191] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expecting varioud folders/git command options to appear when trying command.Prior to update - Auto complete with folders/git commands used to work

### Actual behaviour

Nothing happens - not autocomplete
![Screenshot 2024-05-27 at 16 01 55](https://github.com/aws/q-command-line-discussions/assets/122085134/2573383c-87f0-42c6-ae54-751e219cb3e9)

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (6d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/USER/Library/Python/3.9/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "09600432626946ec997a3b14edfa56a7"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
