### DISCUSSION TITLE
Amazon Q tries to autocomplete in Fish reverse-i-search

### DISCUSSION THREAD

**Discussion by injust** [aws/codewhisperer-command-line-discussions#194] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I can use `reverse-i-search` like normal (press `Ctrl+R`, enter a search string, and press `Enter`).

### Actual behaviour

Amazon Q tries to autocomplete the search string in `reverse-i-search`.
![Screenshot 2024-05-31 at 9 09 33 PM](https://github.com/aws/q-command-line-discussions/assets/3387175/b27e2803-90d5-4c04-b07d-5fe61a6e69ce)
When you press `Enter`, the search string is replaced with `--allow-empty-message`, which gives completely different results. This is probably made worse by enabling fuzzy search in Amazon Q.

### Steps to reproduce

1. Run `git commit --amend`
2. Press `Ctrl+R` and type `--ame`

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (10d ago)"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/usr/local/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "macOS"
install-method = "unknown"

[env-vars]
QTERM_SESSION_ID = "ff426964afbd498f8e4410d4973a857f"
Q_PARENT = ""
Q_TERM = "1.1.0"
SHELL = "/usr/local/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
