### DISCUSSION TITLE
Q Commandline intellij plugin version 1.03 "Marked as incompatible"

### DISCUSSION THREAD

**Discussion by jsamuel1** [aws/codewhisperer-command-line-discussions#197] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect Amazon Q for command line to work on the current latest version of IntelliJ IDEA.
IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024

### Actual behaviour

The plugin is labelled as "Marked as incompatible" in the plugins list.

### Steps to reproduce

Install the plugin via `q integrations install intellij-plugin`.   On next startup of the IDE, the plugin shows as incompatible.
IntelliJ Plugin version is 1.0.3.   Q Commandline 1.1.0.

### Environment

```toml
[q-details]
version = "1.1.0"
hash = "2f25b08ac0b3bd197c00d0e323ec32126a6c0226"
date = "2024-05-21T20:22:19.598303Z (13d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "36.00 GB"

[environment]
cwd = "/Users/USER/src/AmazonCodeWhispererVimPlugin"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/zsh/HEAD-bd19d4e/bin/zsh"
shell-version = "5.9"
terminal = "IDEA Ultimate"
install-method = "brew"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.autojump/bin:/Users/USER/.krew/bin:/Users/USER/.dotnet/tools:/Users/USER/go/bin:/Users/USER/.cargo/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/USER/.toolbox/bin:/Users/USER/bin:/Users/USER/.local/bin:/usr/local/bin:/usr/local/sbin:/Users/USER/.local/share/mise/shims:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/USER/.fzf/bin:/Users/USER/.yarn/bin"
QTERM_SESSION_ID = "a7561e1a2d774dcea7f847c4ccf1d61a"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.1.0"
SHELL = "/opt/homebrew/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.jetbrains.intellij"
```
