### DISCUSSION TITLE
Neovim filename-autocomplete not working on iTerm2

### DISCUSSION THREAD

**Discussion by mito1111** [aws/codewhisperer-command-line-discussions#199] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Neovim command (e.g. `nvim`/`vim`) can activate filename-auto-complete on iTerm2.
Some file names that I want to edit are in auto-complete suggestion panel.

### Current Directory List
Run `nvim` command on iTerm2 as bellow:
![current_directory_list](https://github.com/aws/q-command-line-discussions/assets/86213907/4fef2408-2661-4cdb-a9e6-8fca92fcce99)

### amazon-q auto-complete
Not show file names in auto-complete suggestion as bellow:
But auto-complete suggestion successed when I used CodeWhisperer.
![output](https://github.com/aws/q-command-line-discussions/assets/86213907/47714836-cbea-4d9d-b79d-65fa95f7032e)

### Environment

```toml
[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/work/issues"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/bash/5.2.26/bin/bash"
terminal = "iTerm 2"
install-method = "unknown"
```
