### DISCUSSION TITLE
Feat: Integrate with marlonrichert/zsh-autocomplete

### DISCUSSION THREAD

**Discussion by theKnightsOfRohan** [aws/codewhisperer-command-line-discussions#20] [Feature request]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect both the zsh-autocomplete below suggestions, and the cw cli suggestions to appear.

Because cw-cli fulfills the same need that zsh-autocomplete does, in terms of navigating file structures, in addition to its completion tools, I'm not too put out at this. However, zsh-autocomplete is a popular cli tool, and getting them to work together can only be a good thing.

If I were to speculate, I would say that the reason for this bug is due to zsh-autocomplete displaying the options after the cw-cli dropdown is rendered, overwriting it. 

### Actual behaviour

With zsh-autocomplete enabled: 

https://github.com/aws/codewhisperer-command-line-discussions/assets/114779675/87f601d7-0772-4453-bd08-63c3e3596f48

With zsh-autocomplete disabled:

https://github.com/aws/codewhisperer-command-line-discussions/assets/114779675/82762869-f00c-458e-abe6-e89f352228a3

### Steps to reproduce

Have both zsh-autocomplete and cw-cli installed in your system. I installed zsh-autocomplete using homebrew, and haven't tested with other methods of installation, so that may be a factor, but probably unlikely. Then, once both are enabled in your terminal profile, the conflict should occur.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/rohanseth
  - exe-path: /Users/rohanseth/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 8c4beb0037eb4fcfa1d6e0e8eb9c0bb8
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - DISPLAY: /private/tmp/com.apple.launchd.TRGwX6MCSW/org.xquartz:0
    - PATH: /Users/rohanseth/.rbenv/shims:/Users/rohanseth/.rbenv/shims:/Users/rohanseth/.bun/bin:/Users/rohanseth/.sdkman/candidates/gradle/current/bin:/Users/rohanseth/micromamba/bin:/Users/rohanseth/micromamba/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/rohanseth/.local/bin:/Users/rohanseth/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 8c4beb0037eb4fcfa1d6e0e8eb9c0bb8
```
