### DISCUSSION TITLE
Please add support for Cool-Retro-Term.

### DISCUSSION THREAD

**Discussion by zalez** [aws/codewhisperer-command-line-discussions#202] [Feature request]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

This is a feature request. I would love Amazon Q Developer for command line to also support the Cool-Retro-Term terminal app: https://github.com/Swordfish90/cool-retro-term

This would allow me and others to record awesome demos of Amazon Q Developer, as well as to have a fun terminal experience.

### Actual behaviour

Amazon Q Developer for command line does work inside Cool-Retro-Term, however only the shell related features work. Popup with completion suggestions (which are are implemented on top of the terminal GUI) do not work.

### Steps to reproduce

1. Download the latest Cool-Retro-Term release on a Mac from: https://github.com/Swordfish90/cool-retro-term/releases/download/1.2.0/cool-retro-term-1.2.0.dmg
2. Install Amazon Q Developer app.
3. Try out inline completion for Q inside a new Cool-Retro-Term window. Completions will be suggested inline, but no popups appear.

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (2d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/usr/local/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.UtnZYq7Of6/org.macosforge.xquartz:0"
PATH = "/usr/local/sbin:/Users/USER/bin:/Users/USER/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/git/bin:/usr/texbin"
QTERM_SESSION_ID = "3e427fc4a5c34e7c96379e13e362cc22"
Q_PARENT = ""
Q_TERM = "1.2.0"
SHELL = "/usr/local/bin/fish"
TERM = "xterm"
__CFBundleIdentifier = "com.yourcompany.cool-retro-term"
```
