### DISCUSSION TITLE
PowerLevel zsh support for zsh-autosuggestions

### DISCUSSION THREAD

**Discussion by 32teeth** [aws/codewhisperer-command-line-discussions#203] [Feature request]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

support for p10k zsh-autosuggestions

### Actual behaviour

```
q doctor                                                                                                                                                                                             ✔

✘ Inline: Using zsh-autosuggestions is not supported at the same time as Inline

  To fix either:
  - Remove zsh-autosuggestions from ~/.zshrc and restart your terminal
  - Disable Inline by running: q inline disable


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```

### Steps to reproduce

# Install p10k
[installation guide](`https://dev.to/abdfnx/oh-my-zsh-powerlevel10k-cool-terminal-1no0`)

`p10k configure`

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (7d ago)"

[system-info]
os = "macOS 14.4.1 (23E224)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.C2aj3ejoLQ/org.xquartz:0"
PATH = "/opt/homebrew/bin:/Users/USER/.nvm/versions/node/v18.20.2/bin:/Users/USER/bin:/usr/local/bin:/sbin:/usr/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/.rvm/bin:/Users/USER/.toolbox/bin"
QTERM_SESSION_ID = "9260f03da9a14b329d20e194f5d878e6"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.2.0"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
