### DISCUSSION TITLE
Q is not working on my terminals while doctor says it's all okay

### DISCUSSION THREAD

**Discussion by arscslvt** [aws/codewhisperer-command-line-discussions#206] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [x] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Show suggestions

### Actual behaviour

Doesn't show suggestions in any terminal

#### In-app doctor says it's all okay:
<img width="702" alt="Screenshot 2024-06-13 at 11 54 45" src="https://github.com/aws/q-command-line-discussions/assets/57394934/d8d67c60-6791-482f-aeaf-74f0cee06850">
 
#### Doesn't show any suggestions while typing:
<img width="731" alt="Screenshot 2024-06-13 at 11 54 27" src="https://github.com/aws/q-command-line-discussions/assets/57394934/93b79045-fc3b-44b4-9d09-2507e5ddec87">

#### Even `q doctor` says it's all okay:
<img width="517" alt="Screenshot 2024-06-13 at 11 55 13" src="https://github.com/aws/q-command-line-discussions/assets/57394934/59b2425f-4716-481c-a773-9dd4deaead0a">

### Steps to reproduce

- Open a terminal
- Try to do a cmd

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (10d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.bun/bin:/Users/USER/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/PostgreSQL/12/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scriptseval"
QTERM_SESSION_ID = "e7a05043d50840d88d840d8335b81fce"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.2.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
