### DISCUSSION TITLE
Not launching on start

### DISCUSSION THREAD

**Discussion by claudiorodr** [aws/codewhisperer-command-line-discussions#207] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When having the "Launch on Start" setting turned on I expect to start Amazon Q automatically whenever I restart the computer.

### Actual behaviour

Whenever I restart my laptop I need to manually start Amazon Q, even though I have the "Launch on Start" setting turned on. 

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (11d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Hyper"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.rvm/gems/ruby-2.7.2/bin:/Users/USER/.rvm/gems/ruby-2.7.2@global/bin:/Users/USER/.rvm/rubies/ruby-2.7.2/bin:/Users/USER/.nvm/versions/node/v18.17.0/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/MacGPG2/bin:/Users/USER/.local/bin:/Users/USER/.rvm/bin"
QTERM_SESSION_ID = "ca466d2e502541c785589a0c06c7bf61"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.2.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "co.zeit.hyper"
```
