### DISCUSSION TITLE
Error: maximum nested function level reached

### DISCUSSION THREAD

**Discussion by fang2hou** [aws/codewhisperer-command-line-discussions#209] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

no error when I hit keyboard.

### Actual behaviour

The following error shown.
```
_q_autosuggest_bound_1_self-insert:3: maximum nested function level reached; increase FUNCNEST?
_q_autosuggest_bound_1_accept-line:3: maximum nested function level reached; increase FUNCNEST
_q_autosuggest_bound_1_backward-delete-char:3: maximum nested function level reached; increase FUNCNEST?
```

### Steps to reproduce

let amazon q add the blocks in zshrc, the error shows every time I hit the keyboard.

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (15d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Wezterm"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.cabal/bin:/Users/USER/.ghcup/bin:/Users/USER/.local/goup/current/go/bin:/Users/USER/.cargo/bin:/Users/USER/.pyenv/shims:/Users/USER/.bun/bin:/Users/USER/.volta/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin:/Users/USER/go/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/.orbstack/bin"
QTERM_SESSION_ID = "4ea4b31a367f452db431426121deaacc"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.2.0"
SHELL = "/bin/zsh"
TERM = "wezterm"
__CFBundleIdentifier = "com.github.wez.wezterm"
```

**Comment by brandonskiser** [comment]
Hey, does this happen when tested on a minimal .zshrc file as well? Otherwise, would you mind sharing your .zshrc? There might be some other conflict occurring in your dotfiles causing this.

**Comment by fmal** [comment, marked as answer]
i don't think this happens on a minimal `.zshrc` file. @fang2hou in my case the error above was caused by deferred loading of some zsh plugins. Removing `kind:defer` option from plugins fixed the issue for me.

before (zsh_plugins.txt):

```sh
zsh-users/zsh-autosuggestions  kind:defer
zsh-users/zsh-history-substring-search  kind:defer
```

after:

```sh
zsh-users/zsh-autosuggestions 
zsh-users/zsh-history-substring-search
```

**Reply by NaoyaMiyagawa** [reply]
This worked for me! Thanks a lot, I've been wanting to solve this.

My case: (using zinit)
```shell
# before
zinit wait lucid light-mode atload'_zsh_autosuggest_start' for \
    @'zsh-users/zsh-autosuggestions'

# after
zinit light 'zsh-users/zsh-autosuggestions'
```

**Reply by fang2hou** [reply]
Thanks for the solution! 👍🏻 

And I am using [sheldon](https://github.com/rossmacarthur/sheldon) to manage zsh plugins.
Here is the sample for sheldon users.

```toml
# before
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# after
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
```
