### DISCUSSION TITLE
Autocomplete not working with aliases

### DISCUSSION THREAD

**Discussion by lidora-everc** [aws/codewhisperer-command-line-discussions#21] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I have aliases like:
```
k=kubecolor
kd='kubecolor describe'
keve=kubectl-events
kg='kubecolor get'
kgpow='kubecolor get po -w'
kl='kubecolor logs'
kns=kubens
kt=kubetail
ku='kubectl run -it --rm --restart=Never ubuntu --image=ubuntu bash'
kx=kubectx
```
I want that autocomplete suggestiions for all above command will be appear.

### Actual behaviour

autocomplete for above aliases not working

### Steps to reproduce

Using Same `.zshrc` file as i used with fig(and alias completions worked as well).

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/lidora
  - exe-path: /Users/lidora/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 56c7e4038b3147b697119f79355fcf7a
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/lidora/.krew/bin:/Users/lidora/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/lidora/.krew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/lidora/.local/bin:/Users/lidora/Library/Python/3.10/bin:/Users/lidora/scripts:/Users/lidora/bin:/Users/lidora/Library/Python/3.10/bin:/Users/lidora/scripts:/Users/lidora/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 56c7e4038b3147b697119f79355fcf7a
```
