### DISCUSSION TITLE
Q quit unexpectedly

### DISCUSSION THREAD

**Discussion by zzheng2020** [aws/codewhisperer-command-line-discussions#210] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The software works normally and will not automatically exit for unknown reasons.

### Actual behaviour

Quit unexpectedly and consistently.

### Steps to reproduce

1. open the Q
2. open the iTerm
3. Q quit unexpectedly and consistently.
![q](https://github.com/aws/q-command-line-discussions/assets/46418143/f33f0ec0-f061-425f-b5c2-ce14cef38a1e)

### Environment

```toml
[q-details]
version = "1.2.0"
hash = "5f3cdc12ac743fe04cbef94421772f228fbd146b"
date = "2024-06-03T20:42:04.296133Z (16d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/opt/anaconda3/envs/py10/bin:/opt/homebrew/opt/postgresql@15/bin:/opt/homebrew/opt/libpq/bin:/Users/USER/opt/anaconda3/condabin:/Users/USER/Library/Python/3.8/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Application Support/Coursier/bin://Users/USER/go/bin:/Downloads/Visual Studio Code.app/Contents/Resources/app/bin"
QTERM_SESSION_ID = "9387695e960b48ab8d35bb91531f8ef3"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.2.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
