### DISCUSSION TITLE
Amazon Q is having trouble responding right now. Try again later

### DISCUSSION THREAD

**Discussion by wumingzhang** [aws/codewhisperer-command-line-discussions#213] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Q is not responding any query.

### Actual behaviour

Amazon Q is having trouble responding right now. Try again later

### Environment

```toml
[q-details]
version = "1.3.0"
hash = "2e4743b4ae1c59a9b6dea8cd41ca38afeb7a4eb3"
date = "2024-06-24T19:31:19.860282Z (19h ago)"

[system-info]
os = "macOS 14.6.0 (23G5052d)"
chip = "Apple M1"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Downloads"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "ec06e5d0c5fd4ccdb7395e894e776490"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
