### DISCUSSION TITLE
shell integrations

### DISCUSSION THREAD

**Discussion by tlphieu** [aws/codewhisperer-command-line-discussions#215] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

shell integrations not active

### Actual behaviour

button  for shell integrations not active

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (2d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/opt/miniconda3/condabin:/Users/USER/.modular/pkg/packages.modular.com_mojo/bin:/Users/USER/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
QTERM_SESSION_ID = "17027f4c624b4fee93ca361a0eaa3d1a"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
