### DISCUSSION TITLE
window appers in wrong place

### DISCUSSION THREAD

**Discussion by chertik77** [aws/codewhisperer-command-line-discussions#216] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Window should appear near input 

### Actual behaviour

![Screenshot 2024-07-04 at 18 54 36](https://github.com/aws/q-command-line-discussions/assets/129002577/e7648374-dfb3-486c-a2ff-b803eec02d70)

### Steps to reproduce

it happens sometimes, i cannot even predict this behaviour 

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (6d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "806c09375df64d3a8892dc8ad91025d6"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
