### DISCUSSION TITLE
auto complete not working

### DISCUSSION THREAD

**Discussion by ShashankKumarHunch** [aws/codewhisperer-command-line-discussions#217] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

it auto complete or suggest the different command and folder name.

### Actual behaviour

it is not working

### Steps to reproduce

just type "cd "  it will not suggest next folder name or just type starting few letter of git command it will not suggest anything

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (7d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Desktop"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "0f5784752e2c4e2791e464bbf68bef5e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
