### DISCUSSION TITLE
Too many arguments error

### DISCUSSION THREAD

**Discussion by AnirudhG07** [aws/codewhisperer-command-line-discussions#218] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Even few days ago, when I did 
```bash
# echo hi in blue
```
It would work very nicely. it would output `q translate <something>`.

### Actual behaviour

Current any q command is saying `exit: too many arguments`, may it be autosuggestions, q translate and other amazing useful things, (not q doctor). 

### Steps to reproduce

Nope. I haven't used amazon q features for a while and now I need it, its giving this issue.

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (9d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/opt/postgresql@16/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/USER/.elan/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/go/bin"
QTERM_SESSION_ID = "bffaa515288b4de09ac4004352f39550"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/opt/postgresql@16/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/USER/.elan/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/go/bin"
QTERM_SESSION_ID = "bffaa515288b4de09ac4004352f39550"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
