### DISCUSSION TITLE
autocompletion on fish aliases is not working

### DISCUSSION THREAD

**Discussion by gertjana** [aws/codewhisperer-command-line-discussions#219] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I have for instance `alias k kubectl` in my fish shell config
I would like the autocompletion that works on `kubectl` to also work on the alias

### Actual behaviour

autocompletion does not work on the alias

### Steps to reproduce

- create an alias for a command
- try the autocomplete on the command, this works
- try the autocomplete on the alias, this does not work

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (10d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Max"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/.config/fish"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/fish/3.6.0/bin/fish"
shell-version = "3.6.0"
terminal = "VSCode"
install-method = "brew"

[env-vars]
QTERM_SESSION_ID = "986427b553364ecaae59bbf8f4747bec"
Q_PARENT = ""
Q_TERM = "1.3.1"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
```
