### DISCUSSION TITLE
Bug: cw autocomplete not working while running intellij using idea cli

### DISCUSSION THREAD

**Discussion by lidora-everc** [aws/codewhisperer-command-line-discussions#22] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When i running idea `<path_to_project>` the cw autocomplete will be work

### Actual behaviour

When i running for example: idea  `<path_to_project>` cw auto complete not working.

### Steps to reproduce

When i running intellij without cli the autocomplete working as expected.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: intellij-idea-ultimate
  - cwd: /Users/lidora/IdeaProjects/aws
  - exe-path: /Users/lidora/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - PATH: /Users/lidora/.krew/bin:/Users/lidora/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/lidora/.krew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lidora/.local/bin:/Users/lidora/Library/Python/3.10/bin:/Users/lidora/scripts:/Users/lidora/bin:/Users/lidora/Library/Python/3.10/bin:/Users/lidora/scripts:/Users/lidora/bin
    - SHELL: /bin/zsh
    - CW_SET_PARENT: 693b0d9df2ef422bae24d9fff1ae3a82
    - CWTERM_SESSION_ID: 693b0d9df2ef422bae24d9fff1ae3a82
    - TERM: xterm-256color
    - CW_TERM: 0.12.0
    - __CFBundleIdentifier: com.jetbrains.intellij
    - CW_SET_PARENT_CHECK: 1
```
