### DISCUSSION TITLE
Starship's job module displaying incorrectly. (Amazon Q + fish shell + starship)

### DISCUSSION THREAD

**Discussion by tunefs** [aws/codewhisperer-command-line-discussions#220] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Starship's job module only displays markers if there is a background job.

### Actual behaviour

With Amazon Q's Fish shell integration enabled, Starship's job module will show markers even if there are no background jobs.

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (11d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Volumes/Space/ghq/nileworks.github.com/nileworks/qianliyan_device"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "Kitty"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/fzf/bin:/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "add0d10998da4ccf8fff405a87e59dd9"
Q_PARENT = ""
Q_TERM = "1.3.1"
SHELL = "/bin/zsh"
TERM = "xterm-kitty"
__CFBundleIdentifier = "net.kovidgoyal.kitty"
```
