### DISCUSSION TITLE
Input Method: Not enabled for Rust Rover

### DISCUSSION THREAD

**Discussion by pallabroytushar** [aws/codewhisperer-command-line-discussions#221] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

 q doctor

✘ Input Method: Not enabled for Rust Rover

  Restart Rust Rover [24888] to enable autocomplete in this terminal.

✘ Doctor found errors. Please fix them and try again.

### Actual behaviour

 q doctor

✘ Input Method: Not enabled for Rust Rover

  Restart Rust Rover [24888] to enable autocomplete in this terminal.

✘ Doctor found errors. Please fix them and try again.

### Environment

```toml
[q-details]
version = "1.3.1"
hash = "d5b57f42682e3254b9439924a61daf20e34533f6"
date = "2024-06-28T22:16:55.644011Z (13d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M3 Pro"
total-cores = 11
memory = "18.00 GB"

[environment]
cwd = "/Users/USER/Rusty/hello"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Rust Rover"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/opt/postgresql@16/bin:/Users/USER/Library/pnpm:/Users/USER/.pyenv/shims:/opt/homebrew/opt/ruby/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/tools:/Users/USER/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/laravel:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/Users/USER/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/USER/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/USER/.antigen/bundles/zsh-users/zsh-completions:/Users/USER/.antigen/bundles/romkatv/powerlevel10k:/Users/USER/.spicetify"
QTERM_SESSION_ID = "3b6cbfebd98a4b26937b846aa0ebca26"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.jetbrains.rustrover"
```
