### DISCUSSION TITLE
Amazon Q does not provide services to the China mainland?

### DISCUSSION THREAD

**Discussion by zhi-zhi-zhi** [aws/codewhisperer-command-line-discussions#222] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Work normal like Fig.

### Actual behaviour

All completion are out of time.

### Steps to reproduce

Just download and install it.
You will find all comletion all out of time.

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:02:57.28089Z (4d ago)"

[system-info]
os = "macOS 14.4.0 (23E214)"
chip = "Apple M3 Pro"
total-cores = 11
memory = "18.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.nvm/versions/node/v20.14.0/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts"
QTERM_SESSION_ID = "d2bd83574ae14fdc87fdd90fcf2b69af"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
