### DISCUSSION TITLE
Q is not working

### DISCUSSION THREAD

**Discussion by celljuke** [aws/codewhisperer-command-line-discussions#223] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

It should open the auto complete popup

### Actual behaviour

It is not opening auto-complete popup

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:02:57.28089Z (5d ago)"

[system-info]
os = "macOS 14.1.1 (23B81)"
chip = "Apple M2 Max"
total-cores = 12
memory = "96.00 GB"

[environment]
cwd = "/Users/USER/works/casebender/app-fe"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.nvm/versions/node/v22.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/PostgreSQL/16/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin:/Users/USER/Library/pnpm:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.nvm/versions/node/v22.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.local/bin:/usr/local/bin"
QTERM_SESSION_ID = "219816f5e1df42218d140d8c992aa8a3"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
