### DISCUSSION TITLE
Outdated option for kubectl version subcommand

### DISCUSSION THREAD

**Discussion by mbd-s** [aws/codewhisperer-command-line-discussions#224] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Typing `kubectl version` should bring up a context menu with the correct options:

```sh
Options:
    --client=false:
	If true, shows client version only (no server required).

    -o, --output='':
	One of 'yaml' or 'json'.
```

### Actual behaviour

The context menu includes an option for `--short`, which was removed in version 1.28.

 ![Screenshot 2024-07-17 at 13 07 43](https://github.com/user-attachments/assets/7ca4f7ed-908a-4067-ba3d-7388c0fc7d0c)

### Steps to reproduce

```
# .tool-versions
kubectl 1.29.6
```

```sh
kubectl version 
```

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:02:57.28089Z (7d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "36.00 GB"

[environment]
cwd = "/Users/USER/work/src/devops/kube-hq"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/opt/homebrew/share/google-cloud-sdk/bin:/Users/USER/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/USER/work/src:/Users/USER/work:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "d503586e147b4c7a8feaba24257b0115"
Q_PARENT = ""
Q_TERM = "1.3.2"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
