### DISCUSSION TITLE
amazon-q/ssh_inter bad configuration option

### DISCUSSION THREAD

**Discussion by damoon33** [aws/codewhisperer-command-line-discussions#225] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I am no longer able to execute git commands

### Actual behaviour

```
$ % git pull --rebase
/home/damoon/.local/share/amazon-q/ssh_inner: line 15: Bad configuration option: setenv
/home/damoon/.local/share/amazon-q/ssh_inner: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:01:21.259565Z (12d ago)"

[system-info]
chip = "Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz"
total-cores = 8
memory = "62.76 GB"

[system-info.os.linux]
kernel_version = "5.10.220-187.867.amzn2int.x86_64"
id = "amzn"
name = "Amazon Linux"
pretty_name = "Amazon Linux 2"
version_id = "2"
version = "2"
variant = "internal"

[environment]
cwd = "/local/home/USER/workplace/AlfredSelfServiceGeneratorsAccess/src/AlfredSelfServiceGeneratorsAccess"
cli-path = "/local/home/USER/.toolbox/tools/q/1.3.2/q"
shell-path = "/local/home/USER/.toolbox/tools/toolbox/1.1.1487.0/toolbox-exec"
install-method = "toolbox"

[env-vars]
PATH = "/usr/lib/jvm/java-11-amazon-corretto/bin:/apollo/env/NodeJS/bin:/apollo/env/EnvImprovement/bin:/apollo/env/NRE-Desktop/bin:/home/USER/.toolbox/bin:/usr/local/bin:/usr/bin:/home/USER/bin:/usr/local/sbin:/usr/sbin:/home/USER/.local/bin:/home/USER/bin:/home/USER/.fzf/bin"
QTERM_SESSION_ID = "ebc7ee0083ed4a9aae6a6809e20029c9"
Q_PARENT = "/tmp/q-parent-fe264477f58640eba891938230ae1720.socket"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
```
