### DISCUSSION TITLE
not working in alacritty

### DISCUSSION THREAD

**Discussion by tbsmn** [aws/codewhisperer-command-line-discussions#227] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

there should be popup auto-suggestions

### Actual behaviour

there aren no popup auto-suggestions

### Steps to reproduce

- restartet q
- restartet alacritty
- restartet machine

not suggestions in alacritty but works fine in standard terminal app
q doctor returns
`Terminal support: Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run q issue

  __CFBundleIdentifier: <not-set>`

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:02:57.28089Z (16d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz"
total-cores = 8
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.emacs.d/bin:/Users/USER/homebrew/bin:/Library/TeX/texbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/munki:/usr/local/munkireport:/Users/USER/homebrew/bin:/Users/USER/.local/bin:/Users/USER/scripts/:/Users/USER/homebrew/opt/fzf/bin"
QTERM_SESSION_ID = "e7d01a68a23d43b39d556cfaae2f1fb0"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.2"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
```
