### DISCUSSION TITLE
q doctor generates "could not read sshd_config" error

### DISCUSSION THREAD

**Discussion by vinidlidoo** [aws/codewhisperer-command-line-discussions#228] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

`q doctor` returns the error msg below when connecting via SSH to my Cloud Desktop (x86_64). I'm connecting through VS Code. I confirmed that the two lines are contained in `/etc/ssh/sshd_config`. I work at Amazon and installed q via toolbox. q is correctly installed on my local machine running MacOS. I also successfully ran `q integrations install ssh` on my local machine.

### Actual behaviour

`✘ sshd config: Could not read sshd_config

  The /etc/ssh/sshd_config file needs to have the following line:
    AcceptEnv Q_SET_PARENT
    AllowStreamLocalForwarding yes
  
  If your sshd_config is already configured correctly then:
    1. Restart sshd
    2. Disconnect and reconnect to the host
  
  See https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line-autocomplete-ssh.html for more info

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!`

### Environment

```toml
[q-details]
version = "1.3.2"
hash = "66b44d32a0f0c8218d8fc8900ca6bf6adf4f0440"
date = "2024-07-10T21:01:21.259565Z (16d ago)"

[system-info]
chip = "Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz"
total-cores = 4
memory = "30.55 GB"

[system-info.os.linux]
kernel_version = "5.10.220-187.867.amzn2int.x86_64"
id = "amzn"
name = "Amazon Linux"
pretty_name = "Amazon Linux 2"
version_id = "2"
version = "2"
variant = "internal"

[environment]
cwd = "/local/home/USER"
cli-path = "/local/home/USER/.toolbox/tools/q/1.3.2/q"
shell-path = "/local/home/USER/.toolbox/tools/toolbox/1.1.1487.0/toolbox-exec"
terminal = "VSCode"
install-method = "toolbox"

[env-vars]
PATH = "/local/home/USER/.nodenv/versions/14.16.1/bin:/local/home/USER/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/local/home/USER/.miniforge/bin:/local/home/USER/.miniforge/condabin:/home/USER/.nodenv/shims:/home/USER/.nodenv/bin:/usr/local/bin:/usr/bin:/home/USER/bin:/usr/local/sbin:/usr/sbin:/home/USER/.toolbox/bin:/home/USER/.awsbench/bin:/home/USER/.local/bin"
Q_SET_PARENT_CHECK = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/home/USER"
```
