### DISCUSSION TITLE
can't start tmux successfully. getting error when starting tmux and this is happening after upgrading to Fig to amazon q

### DISCUSSION THREAD

**Discussion by raviSussol** [aws/codewhisperer-command-line-discussions#231] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

should start tmux without any error

### Actual behaviour

when I start tmux then getting `/Users/sussol/.tmux.conf:53: /Users/sussol/.fig/tmux: No such file or directory`

### Steps to reproduce

just type `tmux` and hit enter.

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (5d ago)"

[system-info]
os = "macOS 14.6.0 (23G80)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "18.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/opt/libpq/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/VMware Fusion.app/Contents/Public:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/homebrew/opt/libpq/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/go/bin:/opt/homebrew/opt/go/libexec/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin:/Users/USER/Groovy/4.0.8/bin:/Users/USER/go/bin:/opt/homebrew/opt/go/libexec/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/VMware Fusion.app/Contents/Public:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/homebrew/opt/libpq/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/go/bin:/opt/homebrew/opt/go/libexec/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin:/Users/USER/Groovy/4.0.8/bin:/Users/USER/go/bin:/opt/homebrew/opt/go/libexec/bin:/Users/USER/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin:/Users/USER/Groovy/4.0.8/bin"
QTERM_SESSION_ID = "554e3d0389ea4f0e9400f87dd8e5a61b"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "tmux-256color"
__CFBundleIdentifier = "dev.warp.Warp-Stable"
```
