### DISCUSSION TITLE
App not working as it should on macOS 15.0 Public beta

### DISCUSSION THREAD

**Discussion by driesgroblerw** [aws/codewhisperer-command-line-discussions#232] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I can click my Apple logo (top left) and it opens up the Apple menu

### Actual behaviour

I click the Apple logo and it opens up the Q menu. A transparent Q logo is positioned just left of my Apple logo. No other apps are behaving like this. 

### Steps to reproduce

I just installed the fresh macOS 15.0 Public beta and the Q icon is hovering above the Apple logo. When I click the Apple logo and it opens up the Q menu. 
I have to quit the Q app to use my Apple logo menu item. 

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (7d ago)"

[system-info]
os = "macOS 15.0.0 (24A5298h)"
chip = "Apple M2 Pro"
total-cores = 12
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "e52ab8b8dcda476984cf0a83b6900f42"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
