### DISCUSSION TITLE
Can't remove integration from jetbrain ides

### DISCUSSION THREAD

**Discussion by Bohirjon** [aws/codewhisperer-command-line-discussions#233] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I try to remove intellij plugins with command: 
`q integrations uninstall intellij-plugin`
It says:
```
Warning: IntelliJ integrations are automatically reinstalled on launch
Uninstalled!
```
And then when I restart my Rider It automatically installs again.

### Actual behaviour

It should remove the plugins and should not install again.

### Steps to reproduce

1. Install Intellij plugins
2. Then remove it with: `q integrations uninstall intellij-plugin`

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (8d ago)"

[system-info]
os = "macOS 15.0.0 (24A5309e)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts: 'pwd'/flutter//bin:/Users/USER/.pub-cache/bin:/Users/USER/.dotnet:/Users/USER/sdks/flutter/bin"
QTERM_SESSION_ID = "05e2a96626d34c9dafde68595de9d532"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
