### DISCUSSION TITLE
Cannot use Q because qterm is not running in terminal on ubuntu linux

### DISCUSSION THREAD

**Discussion by gkodali-zededa** [aws/codewhisperer-command-line-discussions#234] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expected the auto complete suggestions to work. 

### Actual behaviour

`q doctor` dumped the following error text
```
✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

  Q_TERM=


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!
```

I tried `q restart` and it dumped the following error
```error: Please restart Amazon Q from your host machine```

### Steps to reproduce

Installed Q following the instructions on Ubuntu 22.04. Tried using autocomplete but the feature did not work.
https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line-autocomplete-ssh.html

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:28:33.163505Z (10d ago)"

[system-info]
chip = "Intel(R) Xeon(R) E-2224 CPU @ 3.40GHz"
total-cores = 4
memory = "62.65 GB"

[system-info.os.linux]
kernel_version = "5.15.0-117-generic"
id = "ubuntu"
name = "Ubuntu"
pretty_name = "Ubuntu 22.04.4 LTS"
version_id = "22.04"
version = "22.04.4 LTS (Jammy Jellyfish)"

[environment]
cwd = "/home/USER"
cli-path = "/home/USER/.local/bin/q"
shell-path = "/usr/bin/bash"
shell-version = "5.1.16"
install-method = "unknown"

[env-vars]
PATH = "/home/USER/.local/bin:/home/USER/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/USER/.local/bin:/home/USER/bin:/home/USER/.nvm:/usr/local/go/bin:/home/USER/go/bin/:/usr/local/go/bin"
Q_SET_PARENT_CHECK = "1"
SHELL = "/bin/bash"
TERM = "xterm-256color"
XDG_SESSION_TYPE = "tty"
```
