### DISCUSSION TITLE
Amazon Q Corrupts Terminal Keybindings During Command Completion

### DISCUSSION THREAD

**Discussion by jihadnaji** [aws/codewhisperer-command-line-discussions#235] [Support ticket]
### Checks

- [x] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behavior

The terminal should continue to accept input normally, without altering the behavior of the Enter and Backspace keys.

### Actual behavior

After Amazon Q suggests completions for the flutter command, the terminal starts behaving incorrectly:
- Pressing Enter results in ^M being displayed.
- Pressing Backspace results in ^? being displayed.
- Other special characters may also appear in place of their intended actions.

### Steps to reproduce

1. Open a terminal on macOS with Amazon Q installed and enabled.
2. Type the command flutter run -d {device id} where {device id} is a valid Flutter device ID (such as chrome, macos, etc.).
3. As Amazon Q begins to provide command suggestions, the terminal input starts displaying unusual characters when pressing Enter or any other action key.

https://github.com/user-attachments/assets/0a4ca705-530f-4721-b802-5b0ba1dcfaf4

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (12d ago)"

[system-info]
os = "macOS 14.6.0 (23G80)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "36.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/usr/local/bin/python3:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.puro/bin:/Users/USER/.puro/envs/default/flutter/bin:/Users/USER/.pub-cache/bin:/Applications/Android Studio.app/Contents/MacOS:/Users/USER/.local/bin"
QTERM_SESSION_ID = "c95ac66f1cbc430a8a881b73c51391da"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
