### DISCUSSION TITLE
Constantly having to login to re-enable inline

### DISCUSSION THREAD

**Discussion by dppeak** [aws/codewhisperer-command-line-discussions#236] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Once I log in with my AWS id, it should remain logged in.

### Actual behaviour

After a while of working correctly, all of a sudden inline completion stops working.  MacOS apps says I'm logged in, but when I run `q doctor`, it tells me I'm not authenticated.

### Steps to reproduce

Not sure how to reproduce.

Never had this issue with FIG.  It's become a very undependable app since Amazon took over.

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (14d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M2 Max"
total-cores = 12
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.rbenv/shims:.:/Users/USER/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/VMware Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Tools/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "251139bbad8b45f5a57009652b45ecd2"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
