### DISCUSSION TITLE
Not working whenever Im inside of my codebases

### DISCUSSION THREAD

**Discussion by ednaaaj** [aws/codewhisperer-command-line-discussions#237] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

the input suggestion should work in every paths even inside of codebases 

### Actual behaviour

Its working inside root, documents, downloads and other directory but whenever i go to the codebases the input suggestions stop working. 

https://github.com/user-attachments/assets/ac23eb39-cf49-4385-8cd9-55c980f83130

### Steps to reproduce

go to the codebase directory

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (17d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M3"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/works/airasia/hotels-mobile"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = '/Users/USER/.pyenv/plugins/pyenv-virtualenv/shims:/Users/USER/.pyenv/shims:/Users/USER/.pyenv/bin:/opt/homebrew/opt/php@8.2/sbin:/opt/homebrew/opt/php@8.2/bin:/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin:/Users/USER/.sdkman/candidates/java/current/bin:/Users/USER/google-cloud-sdk/bin:/Users/USER/.rbenv/shims:/Users/USER/.rbenv/bin:/usr/local/opt/openjdk@17/bin:/Users/USER/.nvm/versions/node/v20.16.0/bin:/opt/homebrew/bin:/Users/USER/.console-ninja/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Android\ Studio.app/Contents/MacOS:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/tools:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/platform-tools'
QTERM_SESSION_ID = "0586432ff89d410ca8404ce1b6fdcc0e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
