### DISCUSSION TITLE
Applications directory doesn't show all contents

### DISCUSSION THREAD

**Discussion by mikaelacaron** [aws/codewhisperer-command-line-discussions#238] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

```zsh
cd Applications/
ls
```

show all the applications on my Mac

### Actual behaviour

only shows Fleet.app, and no other applications in that directory.

I saw the environment says "unknown" for install, but I installed it from this link:
https://aws.amazon.com/blogs/devops/introducing-amazon-codewhisperer-for-command-line/ at the bottom under Getting Started. It installed as Code Whisperer, and then changed to "Amazon Q" at some point. and looking at the path, it does look wrong, but I'm not sure how to fix this. I did previously have Fig.io installed, and migrated to Code Whisperer, and I think it automatically went over to Amazon Q. But it looks like the install path is messed up

### Steps to reproduce

```zsh
cd Applications/
ls
```

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (19d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M1 Max"
total-cores = 10
memory = "64.00 GB"

[environment]
cwd = "/Users/USER/Applications"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/opt/openjdk/bin:/Users/USER/.fastlane/bin:/Users/USER/.rbenv/shims:/Users/USER/.nvm/versions/node/v16.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts"
QTERM_SESSION_ID = "610ad4bbc3df4e899d6b8c01acc91d3f"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
