### DISCUSSION TITLE
bug: Autocomplete Feature Not Working in iTerm2 (Quake Mode)

### DISCUSSION THREAD

**Discussion by arleytm** [aws/codewhisperer-command-line-discussions#239] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The autocomplete feature should work as intended, displaying the autocomplete context menu with suggestions based on the current input.

### Actual behaviour

The autocomplete feature stops working, and the autocomplete context menu is not displayed. This issue seems to be related to how window focus is managed in Quake mode.

### Steps to reproduce

- Open iTerm2
- Configure a profile with the settings shown in the attached screenshots
  - Ensure Quake mode is enabled
- Try to use the autocomplete feature of Fig/Q
- Quit iTerm2
- Open iTerm2 by pressing ⌘I
- Type `cd ` (no directories are displayed)

<img width="936" alt="iterm2-settings-1" src="https://github.com/withfig/fig/assets/1238862/5d08ce4d-2961-4ed4-ae69-3ea0eb8b2478">

<img width="1033" alt="iterm2-settings-2" src="https://github.com/withfig/fig/assets/3323182/51304d0c-072e-4a18-91d6-4e3a67a2bf61">

<img width="1036" alt="iterm2-settings-3" src="https://github.com/withfig/fig/assets/3323182/a96fbc13-bd3b-4bd1-8469-07f4919cb32e">

<video width="1036" alt="iterm2-settings-4" src="https://github.com/withfig/fig/assets/1238862/592d27e6-fc84-411d-a374-7eb1d61c1c81" >

<video width="1036" alt="iterm2-settings-4" src="https://github.com/withfig/fig/assets/1238862/df573ed2-409d-493f-a1c9-b2004d22ff3b" >

### Environment

```toml
[q-details]
version = "1.3.0"
hash = "2e4743b4ae1c59a9b6dea8cd41ca38afeb7a4eb3"
date = "2024-06-24T19:31:19.860282Z (2d ago)"

[system-info]
os = "macOS 15.0.0 (24A5264n)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/usr/local/homebrew/opt/make/libexec/gnubin:/Users/USER/bin/node/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/bin:/usr/local/opt/python/libexec/bin:/usr/local/Cellar/vim:/usr/local/opt/inetutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Privileges.app/Contents/Resources:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/opt/homebrew/opt/fzf/bin"
QTERM_SESSION_ID = "5fe902e2b5db43f39729c0249867da33"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.0"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
