### DISCUSSION TITLE
"Shell Integrations" still showing the red cross icon

### DISCUSSION THREAD

**Discussion by jersonlatorre** [aws/codewhisperer-command-line-discussions#24] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Red cross disappear or "Install" button working

### Actual behaviour

Everything works normally but the red icon is still appearing. When I click to the "Install" button nothing happen.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/uno
  - exe-path: /Users/uno/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: e399ee92d9aa47a3ad4b5ecf76c3438b
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/uno/.modular/pkg/packages.modular.com_mojo/bin:/Users/uno/miniconda3/bin:/Users/uno/miniconda3/condabin:/Users/uno/.bun/bin:/Users/uno/.nvm/versions/node/v20.7.0/bin:/Users/uno/Library/Python/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/uno/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: e399ee92d9aa47a3ad4b5ecf76c3438b
```
