### DISCUSSION TITLE
enter or tab key does not respond

### DISCUSSION THREAD

**Discussion by Okroshiashvili** [aws/codewhisperer-command-line-discussions#241] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

when I, for example run **git pull** it autocompletes, however when I'm trying to click either enter or tab to accept autocompletion, it does not work. Also, up and down arrows does not work

### Actual behaviour

Few days ago, enter, tab, as well as up and down arrows were working

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (24d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER/Desktop/Projects/my_projects/my_project/project"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.pyenv/shims:/Users/USER/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/quarto/bin:/Users/USER/.cargo/bin:/Users/USER/.vscode/extensions/ms-python.python-2024.12.3-darwin-arm64/python_files/deactivate/zsh:/Users/USER/Desktop/Projects/nexus/taran_staging/strategies/.venv/bin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/Coursier/bin:/Users/USER/.pixi/bin"
QTERM_SESSION_ID = "32c66a6b063c4d3385e272a6059dbaef"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
