### DISCUSSION TITLE
zsh-autosuggestions not in .zshrc but still getting the error

### DISCUSSION THREAD

**Discussion by davidggphy** [aws/codewhisperer-command-line-discussions#242] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Not getting error when running `q doctor`

### Actual behaviour

When running `q doctor` in zsh I obtain:

✘ Inline: Using zsh-autosuggestions is not supported at the same time as Inline

  To fix either:
  - Remove zsh-autosuggestions from ~/.zshrc and restart your terminal
  - Disable Inline by running: q inline disable

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!

### Steps to reproduce

In ~/.zshrc I have

```
# plugin zsh-autosuggestions deactvated for Q
# conda-zsh-completion
plugins=(
 git
 macos
 zsh-apple-touchbar
 pip
 poetry
 zsh-syntax-highlighting
)
```

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (27d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M3 Pro"
total-cores = 11
memory = "36.00 GB"

[environment]
cwd = "/Users/USER/_Projects/sumauto-pricing"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/zsh/5.9/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.Ozml7P2FHg/org.xquartz:0"
PATH = "/usr/local/opt/tcl-tk/bin:/usr/local/sbin:/usr/local/opt/tcl-tk/bin:/usr/local/sbin:/opt/homebrew/bin:/Users/USER/google-cloud-sdk/bin:/Users/USER/miniconda3/bin:/Users/USER/miniconda3/condabin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/USER/.fig/bin:/Users/USER/.local/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/USER/google-cloud-sdk/bin:/Users/USER/miniconda3/bin:/Users/USER/miniconda3/condabin:/opt/homebrew/sbin:/Users/USER/.fig/bin:/Users/USER/.local/bin:/usr/local/opt/fzf/bin"
QTERM_SESSION_ID = "e3e1b28de2304f43bdf0d318e9dd845a"
Q_PARENT = ""
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
