### DISCUSSION TITLE
Wrong Propmt to get LaunchTemplate UserData

### DISCUSSION THREAD

**Discussion by stephenmsachs** [aws/codewhisperer-command-line-discussions#243] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

aws ec2 describe-launch-template-versions --launch-template-id lt-XXXX --versions 2 --query 'LaunchTemplateVersions[].LaunchTemplateData.UserData' --output text

### Actual behaviour

aws ec2 describe-launch-template-versions --launch-template-id lt-XXXX --versions 2 --query 'LaunchTemplateData.UserData' --output text

### Steps to reproduce

cw ai
"print the UserData of EC2 launch template lt-XXXX version 2"

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (27d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz"
total-cores = 4
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/git/aws-hpc-recipes"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/bash"
shell-version = "3.2.57"
terminal = "macOS"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.3DotvLYN0d/org.xquartz:0"
PATH = "/Users/USER/.docker/bin:/Users/USER/.docker/bin:/Users/USER/.rbenv/shims:/Users/USER/.poetry/bin:/Users/USER/.toolbox/bin:/Users/USER/.pyenv/shims:/Users/USER/virtualenvs/default/bin:/Users/USER/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/USER/.toolbox/bin:/Users/USER/.local/bin:/usr/local/opt/fzf/bin:/usr/local/bin:/Users/USER/.cargo/bin:/Users/USER/code.amazon.com/Git-review-tools/bin:/usr/local//Cellar/binutils/2.40/bin/:/Users/USER/workplace/SimClient-Sc/build/SimClient-Sc/SimClient-Sc-1.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-target/release:/usr/local//Cellar/binutils/2.41/bin/"
SHELL = "/bin/bash"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
