### DISCUSSION TITLE
'aws sso login' command is missing as a suggestion

### DISCUSSION THREAD

**Discussion by gustaferiksson** [aws/codewhisperer-command-line-discussions#244] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expected `aws sso login` to appear as a alternative when typing `aws sso`

note: it has always appeared until a few weeks ago

### Actual behaviour

`aws sso login` doesn't appear as an alternative

### Steps to reproduce

Type `aws sso ` in the terminal and check for sub commands

### Environment

```toml
[q-details]
version = "1.3.3"
hash = "d6f7500447e6a60baec72c2ca6d695a27c73f977"
date = "2024-07-30T00:30:53.569258Z (28d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M3 Pro"

[environment]
cwd = "REDACTED"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/zsh/5.9/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.deno/bin:/Users/USER/.bun/bin:/Users/USER/.nvm/versions/node/v18.20.2/bin:/Users/USER/.jenv/shims:/Users/USER/.jenv/bin:/Users/USER/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/.deno/bin:/Users/USER/.bun/bin:/Users/USER/.nvm/versions/node/v18.20.2/bin:/Users/USER/.jenv/shims:/Users/USER/.jenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/usr/local/sbin:/usr/local/sbin"
QTERM_SESSION_ID = "952a9d4403fa47f78b9e9eb81e2bd4ef"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.3.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
