### DISCUSSION TITLE
Autocomplete window won't open

### DISCUSSION THREAD

**Discussion by david-moskovitz** [aws/codewhisperer-command-line-discussions#245] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete window should open

### Actual behaviour

When setting `q debug autocomplete-window` I see this
<img width="254" alt="Screenshot 2024-09-01 at 12 26 35" src="https://github.com/user-attachments/assets/e98b5f52-5129-439b-acbd-f4cc25af4640">

### Steps to reproduce

I have a VPN and as discussed [here](https://github.com/aws/q-command-line-discussions/discussions/187) I added `Q_CUSTOM_CERT`.
After running `q debug devtools autocomplete` I see this:
<img width="570" alt="Screenshot 2024-09-01 at 12 22 05" src="https://github.com/user-attachments/assets/a3717935-cee0-428f-a995-28f8eda192c5">

### Environment

```toml
[q-details]
version = "1.4.0"
hash = "a1635029720bc46c285f004832dda2c89b9b9204"
date = "2024-08-28T20:40:51.774343Z (4d ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2 Max"
total-cores = 12
memory = "96.00 GB"

[environment]
cwd = "/Users/USER/Developer/Work"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode Insiders"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.bun/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.docker/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin:/Users/USER/.bun/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.docker/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "e1f98050e52b45cda9e0d397194fbb2c"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCodeInsiders"
```
