### DISCUSSION TITLE
Change the get_all_mysfits() API to return mysfits sorted by the Good/Evil attribute

### DISCUSSION THREAD

**Discussion by aungminkoamk** [aws/codewhisperer-command-line-discussions#246] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Update the API to allow sorting of mysfits by whether they are Good, Neutral, or Evil. Add a button on the website that allows users to quickly choose this sort and to exclude alignments that they don't want to see.

### Actual behaviour

Update the API to allow sorting of mysfits by whether they are Good, Neutral, or Evil. Add a button on the website that allows users to quickly choose this sort and to exclude alignments that they don't want to see.

### Environment

```toml
[q-details]
version = "1.4.0"
hash = "a1635029720bc46c285f004832dda2c89b9b9204"
date = "2024-08-28T20:40:51.774343Z (4d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz"
total-cores = 2
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/usr/local/Cellar/zsh/5.9/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/Cellar/zplug/2.4.2/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/mysql@8.4/bin:/usr/local/opt/curl/bin:/usr/local/opt/bison/bin:/usr/local/opt/binutils/bin:/usr/local/opt/ssh-copy-id/bin:/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "8b04a7f9c7f444428b4fc7b546ba847e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.0"
SHELL = "/usr/local/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
