### DISCUSSION TITLE
Issue with install.sh: Could not find glibc and Manual Installation Steps

### DISCUSSION THREAD

**Discussion by hjm79** [aws/codewhisperer-command-line-discussions#247] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I encountered an issue while trying to install the Amazon Q CLI on my Ubuntu 22.04 system using the provided install.sh script. The installation failed due to a glibc version compatibility issue. Below are the details of the error and the steps I took to manually install the CLI.

Error Message:
[ERROR] Could not find glibc.
[ERROR] This release built for a GNU system with glibc 2.34 or newer, try installing the musl version of the CLI.

### Actual behaviour

Steps Taken:

Attempted Installation Using install.sh:

Ran the install.sh script, which failed with the above error.
The script could not locate the glibc version, even though my system meets the requirement (glibc 2.35).
Manual Installation:

Downloaded the Amazon Q CLI zip file.
Extracted the files and manually copied the q and qterm binaries to the /bin directory.
Updated my .zshrc file to include the necessary pre and post integration blocks:

# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/.local/share/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/.local/share/amazon-q/shell/zshrc.pre.zsh"
export Q_TERM="qterm"
# Amazon Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/.local/share/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/.local/share/amazon-q/shell/zshrc.post.zsh"

Restarted the terminal and manually started qterm.

Current Issue:

Despite setting everything up, running q doctor still indicates that qterm is not running or that the terminal is not using the latest integration.
Terminal output:

✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

Q_TERM=qterm

Could you please provide guidance on how to resolve this issue? I suspect it might be related to the initial glibc detection failure. Is there a recommended workaround for this?

Thank you for your assistance.

### Environment

```toml
[q-details]
version = "1.4.0"
hash = "a1635029720bc46c285f004832dda2c89b9b9204"
date = "2024-08-28T20:38:27.489062Z (7d ago)"

[system-info]
chip = "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz"
total-cores = 4
memory = "23.19 GB"

[system-info.os.linux]
kernel_version = "5.15.0-119-generic"
id = "ubuntu"
name = "Ubuntu"
pretty_name = "Ubuntu 22.04.4 LTS"
version_id = "22.04"
version = "22.04.4 LTS (Jammy Jellyfish)"

[environment]
cwd = "/home/USER"
cli-path = "/home/USER/.local/bin/q"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
install-method = "unknown"
in-ssh = true

[env-vars]
PATH = "/home/USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/USER/.local/bin"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "qterm"
SHELL = "/usr/bin/zsh"
TERM = "xterm-256color"
XDG_SESSION_TYPE = "tty"
```
