### DISCUSSION TITLE
Not working : Not show suggestion

### DISCUSSION THREAD

**Discussion by Nooktarisa** [aws/codewhisperer-command-line-discussions#248] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete window won't open 

![Screenshot at Sep 06 08-57-09](https://github.com/user-attachments/assets/3f1f00e3-6945-4c89-a3c0-0dcad20616ec)

### Actual behaviour

When setting q debug autocomplete-window I see this
![Screenshot at Sep 06 08-55-55](https://github.com/user-attachments/assets/e7acbaef-6081-4f59-93a6-e5d3d875b78c)

### Steps to reproduce

1. restart my computer
2. `q restart `
3. not work

### Environment

```toml
[q-details]
version = "1.4.0"
hash = "a1635029720bc46c285f004832dda2c89b9b9204"
date = "2024-08-28T20:40:51.774343Z (8d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/mckean-web"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.nvm/versions/node/v20.16.0/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/USER/.nvm/versions/node/v20.16.0/bin:/opt/homebrew/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "22c2a4f324d14ac1b6a03a1e0467587c"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
