### DISCUSSION TITLE
Autocomplete didn't work with iterm hotkey window

### DISCUSSION THREAD

**Discussion by ErBlack** [aws/codewhisperer-command-line-discussions#25] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete popup shown after type cd

### Actual behaviour

No autocomplete shown

### Steps to reproduce

Open iterm hotkey windows
Start typing cd

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.1 (22F82)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ertema
  - exe-path: /Users/ertema/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: d97381337ec3462dad7d633cf28c7233
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/ertema/Yandex.Disk.localized/Tools/Unix/bin:/Users/ertema/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ertema/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: d97381337ec3462dad7d633cf28c7233
```
