### DISCUSSION TITLE
Amazon Q for command line

### DISCUSSION THREAD

**Discussion by jotasies** [aws/codewhisperer-command-line-discussions#250] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Amazon Q for the command line extension should not be installed in VS Code if integration is disabled

### Actual behaviour

Amazon Q for command line extension is installed on VS Code on every start of my computer even after deleting it is installed back even when integration is disabled on Amazon Q settings.

`q restart` installs the extension again
<img width="981" alt="image" src="https://github.com/user-attachments/assets/4835db84-857e-450b-84c4-cb95c0d750cd">

### Environment

```toml
[q-details]
version = "1.4.0"
hash = "a1635029720bc46c285f004832dda2c89b9b9204"
date = "2024-08-28T20:40:51.774343Z (9d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Sites/monitaur/monitaur-governml/web"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
PATH = "/Users/USER/.docker/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/Users/USER/.pyenv/shims:/Users/USER/.nvm/versions/node/v20.11.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "3f9dad652ee2474da27bbf62ccf87e8e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.0"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
