### DISCUSSION TITLE
I can not use my terminal, some processes going on and can not terminate it

### DISCUSSION THREAD

**Discussion by kodcuserkan** [aws/codewhisperer-command-line-discussions#252] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I should use my terminal

### Actual behaviour

![Screenshot 2024-09-10 at 12 45 57](https://github.com/user-attachments/assets/e828d619-3e4e-4bbe-87b1-4cdfbf3fa633)

![Screenshot 2024-09-10 at 12 46 15](https://github.com/user-attachments/assets/604871cd-f51b-4155-8b82-852d4652aca5)

I can not use terminals, I restarted laptop, restarted app, nothing works. Happened after updated to Version 1.4.1

### Steps to reproduce

On MacOS with slicon processor just open new terminal

### Environment

```toml
[q-details]
version = "1.4.1"
hash = "abb0bde76283b2e41da287108700e7f6fa9cae18"
date = "2024-09-09T22:49:25.460098Z (11h ago)"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Apple M2 Max"
total-cores = 12
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/Desktop/projects/iris/iris"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.rbenv/shims:/Users/USER/.nvm/versions/node/v18.20.4/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.rbenv/shims:/Users/USER/.nvm/versions/node/v18.20.4/bin:/Users/USER/Library/pnpm:/opt/homebrew/bin:/usr/local/sbin:/opt/homebrew/sbin:/Users/USER/.local/bin:/Users/USER/android-sdk/cmdline-tools/latest/bin:/Users/USER/android-sdk/platform-tools:/Users/USER/android-sdk/cmdline-tools/latest/bin:/Users/USER/android-sdk/platform-tools"
QTERM_SESSION_ID = "cbd0e6ad344d4d06bea468a7d8d74760"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
