### DISCUSSION TITLE
Cannot figure out how to integrate with Panic Nova

### DISCUSSION THREAD

**Discussion by steveblue** [aws/codewhisperer-command-line-discussions#255] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I'm trying to run q in Panic Nova's terminal and found some evidence this was supported with fig, but cannot figure out how to install q to work in the context of Panic Nova's Terminal. Works fine in iTerm 2, but I would greatly prefer directly in the IDE.

### Actual behaviour

q doctor reports to run `q integrations install input-method` and opens System Settings, but not sure what to do. Nova wasn't in the list of input methods. 

### Steps to reproduce

Install and open Panic Nova.
Run q doctor inside Terminal.

### Environment

```toml
[q-details]
version = "1.4.3"
hash = "42defbd83b1fdfd651537628e06830d978bc138d"
date = "2024-09-13T23:17:19.490215Z (3d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "64.00 GB"

[environment]
cwd = "/Users/USER/www/"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Nova"
install-method = "unknown"

[env-vars]
PATH = ** redacted **
QTERM_SESSION_ID = "240564d6119848c8b2a28cc121a9e8fc"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.3"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.panic.Nova"
```
