### DISCUSSION TITLE
Polluted autocomplete for Zellij session names

### DISCUSSION THREAD

**Discussion by akkadaya** [aws/codewhisperer-command-line-discussions#257] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Valid autocomplete for Zellij session names

```sh
# session name is cg
zellij a cg
```

### Actual behaviour

Autocomplete is polluted and does not show the correct session name
```sh
zellij a ;1mcg ; reated ;1m1month 8days 18h 25m 26s ago] (;1mEXITED - attach to resurrect)
```

### Steps to reproduce

type `zellij a` and it'll show the polluted suggestions

### Environment

```toml
[q-details]
version = "1.4.4"
hash = "956c5739077211bb2c5d4cb95d35c4ace3de42a0"
date = "2024-09-16T22:13:24.309363Z (14h ago)"

[system-info]
os = "macOS 14.7.0 (23H124)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Wezterm"
install-method = "brew"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.xH9Xm9gAF0/org.xquartz:0"
PATH = "/opt/homebrew/share/google-cloud-sdk/bin:/Users/USER/.bun/bin:/Users/USER/go/bin:/opt/homebrew/opt/llvm/bin:/Users/USER/.dotnet/tools:/Users/USER/.local/bin:/opt/homebrew/opt/libpq/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/cmdline-tools/latest/bin:/Users/USER/.asdf/shims:/Users/USER/.asdf/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/Privileges.app/Contents/Resources:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/.yarn/bin:/opt/homebrew/opt/fzf/bin"
QTERM_SESSION_ID = "128509589e1d4688b83c1ab6c31cb20a"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.4"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.github.wez.wezterm"
```
