### DISCUSSION TITLE
Bug: All AI commands fail with dispatch failure

### DISCUSSION THREAD

**Discussion by PCManticore** [aws/codewhisperer-command-line-discussions#26] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

`cw ai` to work, even with basic examples.

### Actual behaviour

`cw ai` crashes for every input text with `dispatch failure`.

### Steps to reproduce

`cw ai` fails consistently. Example:

```
Translate Text to Shell

  Text · list all EC2 instances in my account
error: dispatch failure
```

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 7a20ff11fcc844648a75d9dd96ce5f6d
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 7a20ff11fcc844648a75d9dd96ce5f6d
```
```
