### DISCUSSION TITLE
menu mar icon for q is "ghosted" over the apple icon on the top left of menu bar

### DISCUSSION THREAD

**Discussion by noahdurbin** [aws/codewhisperer-command-line-discussions#261] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect to only see the q icon in the right side of the menu bar

### Actual behaviour

I see a "ghosted" q icon over top the apple logo in the top left

### Steps to reproduce

I have just opened q and have this issue
<img width="52" alt="Screenshot 2024-09-20 at 8 08 33 AM" src="https://github.com/user-attachments/assets/cf394191-869f-46ed-b353-d43e5f875e42">

### Environment

```toml
[q-details]
version = "1.4.4"
hash = "956c5739077211bb2c5d4cb95d35c4ace3de42a0"
date = "2024-09-16T22:13:24.309363Z (4d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M2"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Alacritty"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/Library/Application Support/Herd/bin/:/Users/USER/.modular/pkg/packages.modular.com_max/bin:/Users/USER/.nvm/versions/node/v16.15.1/bin:/Users/USER/.rbenv/shims:/Users/USER/.local/share/solana/install/active_release/bin:/Applications/MacVim.app/Contents/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/USER/.gem/bin:/Users/USER/development/flutter/bin:/Users/USER/.cargo/bin:/Users/USER/.pub-cache/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/Library/Application Support/Coursier/bin"
QTERM_SESSION_ID = "b1d8b61cb2914e7b8c5b88f2b2494f40"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.4"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "org.alacritty"
```
