### DISCUSSION TITLE
ssh missing match criteria for exec=command -v q

### DISCUSSION THREAD

**Discussion by npearlaws** [aws/codewhisperer-command-line-discussions#263] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

% ssh npearl

login to host called npearl

npearl %

### Actual behaviour

5ce91ec30510 % ssh npearl
Missing Match criteria for exec=command -v q && q internal generate-ssh --remote-host %h --remote-port %p --remote-username %r
/Users/npearl/Library/Application Support/amazon-q/ssh line 1: Bad Match condition
/Users/npearl/Library/Application Support/amazon-q/ssh: terminating, 1 bad configuration options

### Steps to reproduce

Yes.  

Attempt to ssh into a host.

### Environment

```toml
[q-details]
version = "1.4.4"
hash = "956c5739077211bb2c5d4cb95d35c4ace3de42a0"
date = "2024-09-16T22:13:24.309363Z (5d ago)"

[system-info]
os = "macOS 15.0.0 (24A335)"
chip = "Apple M2 Pro"
total-cores = 12
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.toolbox/bin:/Users/USER/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.0.0.2/Contents/Home/bin"
QTERM_SESSION_ID = "561667e9092e4ed699a5e328d7756b12"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.4"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
