### DISCUSSION TITLE
Q screws up the terminal when using the up arrow

### DISCUSSION THREAD

**Discussion by rossng** [aws/codewhisperer-command-line-discussions#264] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I should be able to press the up arrow repeatedly to scroll through the buffer of previous commands

### Actual behaviour

The new text starts overwriting previous lines printed in the terminal and, before long, it's a mess.

### Steps to reproduce

* Use [Hyper](https://hyper.is/) as your terminal
* Start a new shell, run a random command like ls and then hold the up arrow
* Observe

Disabling this line in `.zprofile` prevents the problem.

```
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zprofile.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zprofile.pre.zsh"
```

### Environment

```toml
[q-details]
version = "1.4.4"
hash = "956c5739077211bb2c5d4cb95d35c4ace3de42a0"
date = "2024-09-16T22:13:24.309363Z (8d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Hyper"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.cabal/bin:/Users/USER/.ghcup/bin:/usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/USER/.nvm/versions/node/v20.10.0/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:/Users/USER/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin"
QTERM_SESSION_ID = "cf061d9f1b8d4e4b9373239317b3acc7"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.4"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "co.zeit.hyper"
```
