### DISCUSSION TITLE
flutter emulators integration issue

### DISCUSSION THREAD

**Discussion by AdiStar350** [aws/codewhisperer-command-line-discussions#265] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Tried to run the command:
```
flutter emulators --launch 'emulator-name'
```

As always when getting to the emulator name a drop-down menu appears.

Expecting to use arrow keys to navigate the menu.

### Actual behaviour

The arrow key presses register in the terminal as escape sequences and also every key that i try to press after it.
The only thing I can do from there is kill the terminal and reopen.

### Steps to reproduce

- Terminal: Kitty
- Shell: zsh
- Have flutter installed and configured ( saw similar issue when using flutter, but a different command ).

### Environment

```toml
[q-details]
version = "1.4.4"
hash = "956c5739077211bb2c5d4cb95d35c4ace3de42a0"
date = "2024-09-16T22:13:24.309363Z (9d ago)"

[system-info]
os = "macOS 15.1.0 (24B5055e)"
chip = "Apple M1 Max"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Kitty"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/development/flutter/bin:/Users/USER/Library/pnpm:/Users/USER/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/USER/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/USER/.local/bin:/Users/USER/.spicetify"
QTERM_SESSION_ID = "b11f05f9bdc94f8cb773dcc9a5ad2249"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.4"
SHELL = "/bin/zsh"
TERM = "xterm-kitty"
__CFBundleIdentifier = "net.kovidgoyal.kitty"
```
