### DISCUSSION TITLE
install jetbrains-plugin

### DISCUSSION THREAD

**Discussion by sawyer523** [aws/codewhisperer-command-line-discussions#268] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

q integrations install jetbrains-plugin

### Actual behaviour

error: Couldn't get JVM properties for IDEA Ultimate: Custom("Could not read plist file: Error { inner: ErrorImpl { kind: Serde(\"missing field `JVMOptions`\"), file_position: None } }")

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (2d ago)"

[system-info]
os = "macOS 15.1.0 (24B5055e)"
chip = "Apple M2 Max"
total-cores = 12
memory = "96.00 GB"

[environment]
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/bin/zsh"
```
