### DISCUSSION TITLE
cw works fine in Hyper but not on VSCode

### DISCUSSION THREAD

**Discussion by wladpaiva** [aws/codewhisperer-command-line-discussions#27] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I've already restarted and tried to reinstall but no success. It works fine on Hyper and Terminal but no successs on making it working on vscode

### Actual behaviour

https://github.com/aws/codewhisperer-command-line-discussions/assets/1843792/933489e1-7329-4c50-a119-af31fa877c46

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/wladpaiva/projects/treino
  - exe-path: /Users/wladpaiva/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 397d733ae479454c8004b213c9be9aac
    - CW_SET_PARENT: 397d733ae479454c8004b213c9be9aac
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/wladpaiva/.bun/bin:/Users/wladpaiva/.nvm/versions/node/v20.10.0/bin:/Users/wladpaiva/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/wladpaiva/.bun/bin:/Users/wladpaiva/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/wladpaiva/.local/bin:/Users/wladpaiva/.orbstack/bin:/Users/wladpaiva/.orbstack/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/wladpaiva
    - __CFBundleIdentifier: com.microsoft.VSCode
```
