### DISCUSSION TITLE
inline autocomplete does not work on tab, and the floating prompt covers my text.

### DISCUSSION THREAD

**Discussion by jasikpark** [aws/codewhisperer-command-line-discussions#270] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expected for pressing "tab" when I have an inline autocomplete to fill in the suggested autocomplete, and for the floating prompt not to cover my input text.

### Actual behaviour

<img width="415" alt="image" src="https://github.com/user-attachments/assets/48cd179b-e1fc-4561-aab9-7e9bde9e6bc5">

Running `q restart` moved it down so now it's just in a weird spot, and pressing tab when in the state shown in the screenshot does not autocomplete the suggested commit message.

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (4d ago)"

[system-info]
os = "macOS 15.0.0 (24A335)"
chip = "Apple M1 Max"
total-cores = 10
memory = "64.00 GB"

[environment]
cwd = "/Users/USER/Git/defined.net/api"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Zed"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.rd/bin:/Users/USER/.local/state/fnm_multishells/79996_1727715142169/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Users/USER/Library/pnpm:/Users/USER/.rd/bin:/Users/USER/.local/state/fnm_multishells/53084_1727713687270/bin:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/go/bin:/Users/USER/.local/bin:/Users/USER/.local/bin:/Users/USER/go/bin"
QTERM_SESSION_ID = "8c1fb12cc6054e8f9e550c37940fd51e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "alacritty"
__CFBundleIdentifier = "dev.zed.Zed"
```
