### DISCUSSION TITLE
autocomplete not working

### DISCUSSION THREAD

**Discussion by harshal1906** [aws/codewhisperer-command-line-discussions#275] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Autocomplete should normally work

### Actual behaviour

Nothing related to autocomplete works

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (10d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Desktop/PrivateAI"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "59eda44aceeb403fa30b81b5c1d45514"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
