### DISCUSSION TITLE
✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

### DISCUSSION THREAD

**Discussion by Mustafaa71** [aws/codewhisperer-command-line-discussions#276] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

After installing Amazon Q for command line.
I could not use it

### Actual behaviour

➜  ~ q doctor

✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

  Q_TERM=

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (18d ago)"

[system-info]
os = "macOS 15.0.1 (24A348)"
chip = "Apple M1"
total-cores = 8
memory = "8.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Applications/Amazon Q.app/Contents/MacOS/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/Users/USER/.rvm/gems/ruby-3.0.0/bin:/Users/USER/.rvm/gems/ruby-3.0.0@global/bin:/Users/USER/.rvm/rubies/ruby-3.0.0/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/.fig/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/usr/local/mysql/bin:/Users/USER/development/flutter/bin:/Users/USER/.pub-cache/bin:/Users/USER/.rvm/bin:/Applications/Amazon Q.app/Contents/MacOS:/Users/USER/development/flutter/bin:/Users/USER/.pub-cache/bin:/Applications/Amazon Q.app/Contents/MacOS"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
