### DISCUSSION TITLE
Add the ability to disable CLI intercepting a comment (`#`) prefixed command and sending it to `q translate`.

### DISCUSSION THREAD

**Discussion by mcteo** [aws/codewhisperer-command-line-discussions#277] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I want to delete a long command in the terminal, or save it in history for later, I type `Home`, `#`, `Enter`. I learned this off someone else, but not sure how widespread it really is. (I use `Home` because `Ctrl + A` tends to be bound to `screen`).

Q's terminal integration intercepts commands beginning with `#` and sends it to `q translate`.

I don't Q being overzealous initially, but would like the ability to disable this specific functionality, without needing to disable all terminal integration.

### Actual behaviour

Executing the following:
```
$ # echo hello
```
turns into:

```
$ ~ q translate 'echo hello'

  Shell · #rm -rf *

⚠️ Warning: this command contains an irreversible flag ( -rf), please make sure you know what you are doing before you run this...
```
(Also the suggestion wasn't great either)

### Steps to reproduce

1. Execution `# echo hello` in terminal.
2. Observe it using `q translate` and asking if you want to execute some other unrelated command.

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (20d ago)"

[system-info]
os = "macOS 14.7.0 (23H124)"
chip = "Apple M1"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown" (via Public DMG + drag & drop)

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.SF2LYtwBso/org.xquartz:0"
PATH = "/Users/USER/.pyenv/shims:/opt/homebrew/opt/sqlite/bin:/Users/USER/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Users/USER/Library/Android/sdk/platform-tools:/Users/USER/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/usr/local/bin:/Users/USER/.local/bin:/Users/USER/.toolbox/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/USER/Downloads/sonar-scanner-4.7.0.2747-macosx/bin:/Users/USER/.local/bin"
IS_AMAZON_EMPLOYEE = "yes"
QTERM_SESSION_ID = "e1f380793ab04a6dad4724a0435d1e1e"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
