### DISCUSSION TITLE
Pressing enter is blocked when suggestions popup is showing

### DISCUSSION THREAD

**Discussion by marcelocch** [aws/codewhisperer-command-line-discussions#278] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Should press enter to execute the code in terminal

### Actual behaviour

When the suggestions popup is showing, I cant press enter or autocomplete the code.

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (25d ago)"

[system-info]
os = "macOS 14.6.1 (23G93)"
chip = "Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz"
total-cores = 4
memory = "8.00 GB"

[environment]
cwd = "/Users/USER/Documents/next-js-projects/acbt-ticketera"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/opt/libiconv/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/openjdk@11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/USER/Library/Android/sdk/platform-tools:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/mysql/bin:/usr/local/opt/ruby/bin:/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin:/Users/USER/.local/bin:/Users/USER/Library/Android/sdk/tools/bin:/Users/USER/Library/Android/sdk/emulator:/Users/USER/Library/Android/sdk/build-tools/30.0.1:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/USER/.composer/vendor/bin:/Applications/flutter/bin:/Users/USER/.rvm/bin"
QTERM_SESSION_ID = "2ecfb7de91f0435c8880e5357219fb73"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
