### DISCUSSION TITLE
Rio terminal not present at the right location

### DISCUSSION THREAD

**Discussion by dreamfliper** [aws/codewhisperer-command-line-discussions#282] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

display suggest at the right location like this
<img width="710" alt="Screenshot 2024-11-01 at 10 22 40 AM" src="https://github.com/user-attachments/assets/bcd436f6-f9c3-44b6-8899-e472ef1535fe">
suggests

### Actual behaviour

In the Rio terminal it always display in the top left ( (0, 0) in x, y )
<img width="802" alt="Screenshot 2024-11-01 at 10 24 25 AM" src="https://github.com/user-attachments/assets/97675985-a537-4376-89f3-a50e2c29da12">

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (35d ago)"

[system-info]
os = "macOS 15.1.0 (24B83)"
chip = "Apple M3 Pro"
total-cores = 11
memory = "18.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/zsh/5.9/bin/zsh"
shell-version = "5.9"
terminal = "Rio"
install-method = "brew"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.IU9HR0G4Dp/org.xquartz:0"
PATH = "/Users/USER/.console-ninja/.bin:/Users/USER/Library/pnpm:/Users/USER/.local/state/fnm_multishells/87783_1730427057217/bin:/Users/hengpai.hsu/Library/Application Support/fnm:/opt/homebrew/opt/postgresql@15/bin:/Users/USER/.bun/bin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/openjdk/bin:/Users/USER/anaconda3/bin:/opt/homebrew/share/google-cloud-sdk/bin:/Users/USER/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.cargo/bin:~/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/VMware Fusion.app/Contents/Public:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/go/bin:/Users/USER/.cargo/bin:/Users/USER/.pub-cache/bin:/Users/USER/.fvm/default/bin"
QTERM_SESSION_ID = "6bd32ef1ce454e2d8f0c4adde50cc645"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/opt/homebrew/bin/zsh"
TERM = "rio"
__CFBundleIdentifier = "com.raphaelamorim.rio"
```
