### DISCUSSION TITLE
Support request: zsh (qterm)(8300) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

### DISCUSSION THREAD

**Discussion by n-for-all** [aws/codewhisperer-command-line-discussions#284] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

zsh (qterm)(8300) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

This message keeps on popping out if the terminal is inactive and then you try to use it, disabling amazon q resolves the issue, but i need it, how do i rresolve this issue

### Actual behaviour

it shouldn't show this message when i type any command on the terminal

### Steps to reproduce

i am using latest macos and zsh terminal on intel processor

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (35d ago)"

[system-info]
os = "macOS 14.3.1 (23D60)"
chip = "Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER/Desktop/clients/oracleinstance"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/bash"
shell-version = "3.2.57"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/opt/curl/bin:/usr/local/mysql/bin:/usr/local/opt/ruby/bin:/usr/local/opt/node@12/bin:/Users/USER/.rvm/gems/ruby-2.0.0-p648/bin:/Users/USER/.rvm/gems/ruby-2.0.0-p648@global/bin:/Users/USER/.rvm/rubies/ruby-2.0.0-p648/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/grep/libexec/gnubin:/usr/local/sbin:/usr/local/Cellar/php70/7.0.27_19/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/USER/.local/bin:/Users/USER/npear/bin:/Users/USER/.composer/vendor/bin:/usr/local/Cellar/openvpn/2.4.4/sbin:/Users/USER/.rvm/bin"
QTERM_SESSION_ID = "8737c4fdff904d5689b21979ad6b1e00"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/bash"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
