### DISCUSSION TITLE
Question Marks Appearing in shell

### DISCUSSION THREAD

**Discussion by omariqbalnaru** [aws/codewhisperer-command-line-discussions#285] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

To work as expected

### Actual behaviour

Question marks appearing
![Screenshot 2024-11-04 at 6 20 19 PM](https://github.com/user-attachments/assets/55869c0e-292e-41c4-8eb4-3b3586c8d71f)

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (39d ago)"

[system-info]
os = "macOS 15.1.0 (24B83)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "18.00 GB"

[environment]
cwd = "/Users/USER/Documents/repos/insurance_platform"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.local/share/mise/installs/node/18/bin:/Users/USER/.local/share/mise/installs/python/3.8.13/bin:/Users/USER/Documents/repos/insurance_platform/bin:/Users/USER/.local/share/mise/installs/node/18/bin:/Users/USER/.local/share/mise/installs/python/3.8.13/bin:/Users/USER/.pyenv/shims:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/Privileges.app/Contents/Resources:/opt/homebrew/opt/openjdk@11/bin:/Users/USER/Downloads/google-cloud-sdk/bin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts:/Users/USER/Downloads/apache-maven-3.6.2/bin"
QTERM_SESSION_ID = "c6651b511da249a8a0b763270f8a423d"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
