### DISCUSSION TITLE
does not work with SecureCRT

### DISCUSSION THREAD

**Discussion by deepvoice** [aws/codewhisperer-command-line-discussions#286] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

seamless integration with terminal

### Actual behaviour

Needs key mapping I believe

### Steps to reproduce

install SecureCRT from https://vandyke.com 
install Q
Open a localhost terminal

Output at prompt:
7;EndPrompt7;NewCmd=                                                                                                                                                                                          7;StartPrompt7;EndPrompt

### Environment

```toml
7;EndPrompt7;NewCmd=                                                                                                                                                                                          7q diagnostic7;EndPrompt

[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (39d ago)"

[system-info]
os = "macOS 15.1.0 (24B83)"
chip = "Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz"
total-cores = 8
memory = "64.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/usr/local/Cellar/pyenv-virtualenv/1.2.4/shims:/Users/USER/.pyenv/shims:/Users/USER/.pyenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Little Snitch.app/Contents/Components:/Users/USER/.local/bin"
Q_SET_PARENT_CHECK = "1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.vandyke.SecureCRT"
```
