### DISCUSSION TITLE
auto complete not working

### DISCUSSION THREAD

**Discussion by bl-engineer** [aws/codewhisperer-command-line-discussions#287] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

auto complete stopped working 

### Actual behaviour

for instance after typing git inside terminal, I am not getting auto completion as I used to

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (40d ago)"

[system-info]
os = "macOS 15.0.0 (24A335)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "18.00 GB"

[environment]
cwd = "/Users/USER/gt-bootcamp2024/course/01-HTML-Git-CSS/01-Activities"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.console-ninja/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.console-ninja/.bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "c980ef881d36455d803c073f619708e8"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.microsoft.VSCode"
```
