### DISCUSSION TITLE
Fish startup slow

### DISCUSSION THREAD

**Discussion by asportnoy** [aws/codewhisperer-command-line-discussions#289] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Potentially relevant: #256, #123

When starting a new Fish session in either iTerm or VSCode, it takes around 3 seconds to start up. I have narrowed down that the issue lies in `~/fish/conf.d/00_fig_pre.fish` by throwing some `echo`s in there, but I don't know what's causing it beyond that.

Furthermore, any text that I type while the startup is happening gets cleared once startup finishes. Normally, any text I type while the startup is happening will then be moved into my prompt once it is done.

This delay is a major problem for me and I will be disabling Q until it is resolved.

### Actual behaviour

See above

### Steps to reproduce

Any time I start up my terminal it happens

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (48d ago)"

[system-info]
os = "macOS 15.1.0 (24B83)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/opt/homebrew/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.local/share/nvm/v20.12.2/bin:/Users/USER/Documents/depot_tools:/Users/USER/.spicetify:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/postgresql@11/bin:/opt/homebrew/opt/postgresql@15/bin:/opt/homebrew/bin:/Users/USER/Library/pnpm:/Users/USER/.config/fish/commands:/Users/USER/.cargo/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/usr/local/MacGPG2/bin:/usr/local/munki:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "855802a8b4c94240b34813853072545f"
Q_PARENT = ""
Q_TERM = "1.4.5"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
