### DISCUSSION TITLE
os error 13

### DISCUSSION THREAD

**Discussion by yguven17** [aws/codewhisperer-command-line-discussions#291] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Error: bash (/Users/username/.bash_profile): Permissions denied for /Users/username/.bash_profile

To automatically fix the permissions run: sudo q debug fix-permissions

  Error: Permission denied (os error 13)

### Actual behaviour

Error: bash (/Users/username/.bash_profile): Permissions denied for /Users/username/.bash_profile

To automatically fix the permissions run: sudo q debug fix-permissions

  Error: Permission denied (os error 13)

### Environment

```toml
[q-details]
version = "1.4.5"
hash = "804bfdf011c861a45b106573ced14fc088598781"
date = "2024-09-26T21:37:06.944937Z (53d ago)"

[system-info]
os = "macOS 15.0.1 (24A348)"
chip = "Apple M1 Max"
total-cores = 10
memory = "64.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER/.local/bin/q"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/opt/openjdk/bin:/Users/USER/Developer/google-cloud-sdk/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/USER/.local/bin:/Users/USER/Library/Application Support/JetBrains/Toolbox/scripts"
QTERM_SESSION_ID = "b1fef1c2264d467c8c3eba2930b004ba"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.4.5"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
