### DISCUSSION TITLE
Fig errors for kitty shell integrations

### DISCUSSION THREAD

**Discussion by andrewcdowning** [aws/codewhisperer-command-line-discussions#293] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Terminal to start in timely manner without 4 to 6 second delay.

### Actual behaviour

Kitty terminal is slow starting when CLI completions - autocomplete option enabled.  Integrations for kitty installed with `q integrations install input-method` command.  While investigating slowdown I found the following error repeated in kitty's app log during startup of new session.
```
[PARSE+ERROR]+Ignoring+OSC+697%2C+typically+used+by+Fig+for+shell+integration 
```

### Steps to reproduce

Use latest version of Kitty term
Use latest version of Q

In Q enable shell auto completions

In terminal run kitty command

### Environment

```toml
[q-details]
version = "1.4.6"
hash = "bd280c3d07adab595bbd62de5ab841eb0567f094"
date = "2024-11-15T20:16:24.896916Z (4d ago)"
variant = "full"

[system-info]
os = "macOS 14.7.1 (23H222)"
chip = "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
total-cores = 6
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "Kitty"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/bin:/usr/local/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Users/USER/.atuin/bin:/Applications/kitty.app/Contents/MacOS:/Users/USER/.cargo/bin:/Users/USER/.toolbox/bin:/Users/USER/.local/bin"
SHELL = "/bin/zsh"
TERM = "xterm-kitty"
__CFBundleIdentifier = "net.kovidgoyal.kitty"
```
