### DISCUSSION TITLE
Black screen on Linux

### DISCUSSION THREAD

**Discussion by mindaugasw** [aws/codewhisperer-command-line-discussions#295] [Support ticket]
Hi! Very excited to see Amazon Q finally being released on Linux!

### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

- Desktop application opens and shows stuff
- Terminal integration works and shows a pop up when typing

### Actual behaviour

- Opening desktop application shows only black window.
- In the terminal pop up does not show

![image](https://github.com/user-attachments/assets/7eb71768-8802-4526-a2f0-447326400a0c)

### Steps to reproduce

- Downloaded app
- Installed according to the [instructions](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line-installing.html#command-line-installing-ubuntu)
- Opened the app
- See black screen

Things I tried:
- restarting the application
- installing AppImage and .deb
- running from CLI and running from desktop icon
  - On the first run had an error in terminal about missing `/home/USER/.midway` directory. But solved it by manually creating it.
- completing setup on the command line with `q doctor` (now it says ✔ Everything looks good!)
- restarting the application multiple times again

But nothing helps, desktop app still shows only black screen. No errors in the terminal.  
Menu bar app appears, shows menu, but clicking anything opens the same desktop app with black window.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (1d ago)"
variant = "full"

[system-info]
chip = "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz"
total-cores = 4
memory = "15.56 GB"

[system-info.os.linux]
kernel_version = "5.15.0-126-generic"
id = "ubuntu"
name = "Ubuntu"
pretty_name = "Ubuntu 22.04.5 LTS"
version_id = "22.04"
version = "22.04.5 LTS (Jammy Jellyfish)"

[environment]
cwd = "/home/USER"
cli-path = "/home/USER"
os = "Linux"
shell-path = "/usr/bin/bash"
shell-version = "5.1.16"
terminal = "Gnome Terminal"
install-method = "unknown"

[env-vars]
DISPLAY = ":1"
GTK_IM_MODULE = "ibus"
PATH = "/home/USER/.nvm/versions/node/v14.13.1/bin:/home/USER/anaconda3/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/USER/.dotnet/tools:/usr/local/bin:/home/USER/.local/share/JetBrains/Toolbox/scripts:/home/USER/.symfony/bin:/home/USER/Path:./vendor/bin:/usr/local/go/bin"
QTERM_SESSION_ID = "8f1c41c719a04e68be7aec343172d110"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/bash"
TERM = "xterm-256color"
XDG_CURRENT_DESKTOP = "ubuntu:GNOME"
XDG_SESSION_DESKTOP = "ubuntu"
XDG_SESSION_TYPE = "x11"
XMODIFIERS = "@im=ibus"
```
