### DISCUSSION TITLE
Suggestion box not displayed properly in linux

### DISCUSSION THREAD

**Discussion by VBtheFirbolg** [aws/codewhisperer-command-line-discussions#296] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Suggestion dropdown appears next to the text I am typing in the terminal

### Actual behaviour

Suggestion dropdown box appears at the bottom of the terminal and that too unreliably.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (2d ago)"
variant = "full"

[system-info]
chip = "AMD Ryzen 7 PRO 5850U with Radeon Graphics"
total-cores = 8
memory = "14.95 GB"

[system-info.os.linux]
kernel_version = "6.9.3-76060903-generic"
id = "pop"
name = "Pop!_OS"
pretty_name = "Pop!_OS 22.04 LTS"
version_id = "22.04"
version = "22.04 LTS"

[environment]
cwd = "/home/USER"
cli-path = "/home/USER"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
terminal = "Alacritty"
install-method = "unknown"

[env-vars]
DISPLAY = ":1"
GTK_IM_MODULE = "ibus"
PATH = "/home/USER/miniforge3/bin:/home/USER/miniforge3/condabin:/home/USER/.juliaup/bin:/home/USER/.juliaup/bin:/home/USER/texlive/2022/bin/x86_64-linux:/home/USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
QTERM_SESSION_ID = "6633d2d89d8d4d5cbb80929163e801c8"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/usr/bin/zsh"
TERM = "alacritty"
XDG_CURRENT_DESKTOP = "pop:GNOME"
XDG_SESSION_DESKTOP = "pop"
XDG_SESSION_TYPE = "x11"
XMODIFIERS = "@im=ibus"
```
