### DISCUSSION TITLE
mac brew plugins and .zshrc settings no longer works after install amazon q

### DISCUSSION THREAD

**Discussion by ythdelmar68** [aws/codewhisperer-command-line-discussions#297] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I have brew installed this https://github.com/wting/autojump, but when running `j some-folder` it just shows `zsh: command not found`. And I have some plugins installed with oh-my-zsh and settings in .zshrc, they're all gone after the installation. Everything has been messed up after the transition from fig to amazon Q, very unpleasent experience.

### Actual behaviour

I have brew installed this https://github.com/wting/autojump, but when running `j some-folder` it just shows `zsh: command not found`. And I have some plugins installed with oh-my-zsh and settings in .zshrc, they're all gone after the installation. Everything has been messed up after the transition from fig to amazon Q, very unpleasent experience.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:26:56.475228Z (9d ago)"
variant = "full"

[system-info]
os = "macOS 12.5.0 (21G72)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/Repos/ythfin-web"
cli-path = "/Users/USER/Repos/ythfin-web"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.8"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.docker/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "1187e732741d42619cddf86d65795cc0"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
