### DISCUSSION TITLE
qterm doesn't start in guake - add guake support

### DISCUSSION THREAD

**Discussion by KaylorDave** [aws/codewhisperer-command-line-discussions#298] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expected q to provide suggestions in my terminal.

### Actual behaviour

Q does not provide suggestions unless I manually run `qterm`. Once I do that, things begin to work. `q doctor` still reports I have an unsupported terminal however.

### Steps to reproduce

```
> q doctor                                                                                                                                                                                                                                                       

✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

  Q_TERM=


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!

> qterm                                                                                                                                                                                                                                                        > q doctor                                                                                                                                                                                                                                                       

● Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run q issue
✔ Everything looks good!

  Amazon Q still not working? Run q issue to let us know!
```

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (11d ago)"
variant = "full"

[system-info]
chip = "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz"
total-cores = 4

[system-info.os.linux]
kernel_version = "6.8.0-48-generic"
id = "neon"
name = "KDE neon"
pretty_name = "KDE neon 6.2"
version_id = "22.04"
version = "6.2"

[environment]
cwd = "/home/ANT.AMAZON.COM/USER"
cli-path = "/home/ANT.AMAZON.COM/USER"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
install-method = "unknown"

[env-vars]
DISPLAY = ":0"
GTK_IM_MODULE = "ibus"
PATH = "/home/ANT.AMAZON.COM/USER/bin:/usr/local/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/apollo/env/SDETools/bin:/home/ANT.AMAZON.COM/USER/bin:/usr/local/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/home/ANT.AMAZON.COM/USER/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/apollo/env/SDETools/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/apollo/env/SDETools/bin"
QTERM_SESSION_ID = "729d43b235034e6fb86c8896807121fb"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/bash"
TERM = "xterm-256color"
XDG_CURRENT_DESKTOP = "KDE"
XDG_SESSION_DESKTOP = "KDE"
XDG_SESSION_TYPE = "x11"
XMODIFIERS = "@im=ibus"
memory = "15.31 GB"

[system-info.os.linux]
kernel_version = "6.8.0-48-generic"
id = "neon"
name = "KDE neon"
pretty_name = "KDE neon 6.2"
version_id = "22.04"
version = "6.2"

[environment]
cwd = "/home/ANT.AMAZON.COM/USER"
cli-path = "/home/ANT.AMAZON.COM/USER"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
install-method = "unknown"

[env-vars]
DISPLAY = ":0"
GTK_IM_MODULE = "ibus"
PATH = "/home/ANT.AMAZON.COM/USER/bin:/usr/local/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/apollo/env/SDETools/bin:/home/ANT.AMAZON.COM/USER/bin:/usr/local/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/home/ANT.AMAZON.COM/USER/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ANT.AMAZON.COM/USER/.local/bin:/apollo/env/SDETools/bin:/home/ANT.AMAZON.COM/USER/.toolbox/bin:/apollo/env/SDETools/bin"
QTERM_SESSION_ID = "deac088cf287484e941418af2e2a55d7"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/bash"
TERM = "xterm-256color"
XDG_CURRENT_DESKTOP = "KDE"
XDG_SESSION_DESKTOP = "KDE"
XDG_SESSION_TYPE = "x11"
XMODIFIERS = "@im=ibus"
```
