### DISCUSSION TITLE
Shell integrations showing red X

### DISCUSSION THREAD

**Discussion by mismith** [aws/codewhisperer-command-line-discussions#299] [Support ticket] [answered]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Should show a green checkmark

### Actual behaviour

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/dac13cfd-8614-452f-9f3c-e33fe5c7bd51">

`inputMethod` is `NOT_INSTALLED`:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/318959a1-80b5-48da-8fa4-5d6d7e17348c">

`dotfiles` is `NOT_INSTALLED`:
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/5d4bac91-2f78-4fa3-bb81-748ffc175830">

Looks similar to https://github.com/aws/q-command-line-discussions/discussions/24 but no resolution there 

### Steps to reproduce

Just open app

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:26:56.475228Z (12d ago)"
variant = "full"

[system-info]
os = "macOS 15.1.1 (24B91)"
chip = "Apple M3 Pro"
total-cores = 12
memory = "36.00 GB"

[environment]
cwd = "/Users/USER/Sites/@neuroxhq/infra/local"
cli-path = "/Users/USER/Sites/@neuroxhq/infra/local"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "macOS"
install-method = "unknown"

[env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/Users/USER/.yarn/bin:/Users/USER/.config/yarn/global/node_modules/.bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.local/bin:/Users/USER/.orbstack/bin"
QTERM_SESSION_ID = "c2ad933366644ae696d3546986c7bf23"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.apple.Terminal"
```
