### DISCUSSION TITLE
Custom CLI completions not working

### DISCUSSION THREAD

**Discussion by leegoodrich** [aws/codewhisperer-command-line-discussions#30] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

when I call the 'infra' command, I get autocompletion.

### Actual behaviour

No autocompletion occurs.

### Steps to reproduce

The `infra` command is in my `$PATH`.  But when I type `infra` I get no autocompletion, even though the commands I type work when executed and other commands like `git` and `cd` perform autocompletion correctly. I am using the latest iTerm.

I installed the following into ~/.fig/autocomplete/build/infra.ts
As stated here: https://fig.io/docs/handbook/how-does-fig-load-specs#cli-tools
```typescript

// Autogenerated by click_complete_fig
const completionSpec: Fig.Spec = {
  "name": "infra",
  "options": [
    {
      "name": [
        "--help"
      ],
      "description": "Show this message and exit."
    }
  ],
  "subcommands": [
    {
      "name": "asset",
      "options": [
        {
          "name": [
            "--output"
          ],
          "args": [
            {
              "name": "choice",
              "suggestions": [
                "csv",
                "json",
                "table"
              ]
            }
          ]
        },
        {
          "name": [
            "--debug"
          ],
          "exclusiveOn": [
            "--no-debug"
          ]
        },
        {
          "name": [
            "--no-debug"
          ],
          "exclusiveOn": [
            "--debug"
          ]
        },
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ],
      "args": [
        {
          "name": "text"
        }
      ]
    },
    {
      "name": "assets",
      "options": [
        {
          "name": [
            "--output"
          ],
          "args": [
            {
              "name": "choice",
              "suggestions": [
                "csv",
                "json",
                "table"
              ]
            }
          ]
        },
        {
          "name": [
            "--debug"
          ],
          "exclusiveOn": [
            "--no-debug"
          ]
        },
        {
          "name": [
            "--no-debug"
          ],
          "exclusiveOn": [
            "--debug"
          ]
        },
        {
          "name": [
            "--page-size"
          ],
          "description": "number of records being fetch per batch",
          "args": [
            {
              "name": "integer"
            }
          ]
        },
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ],
      "args": [
        {
          "name": "text"
        }
      ]
    },
    {
      "name": "generate-completion-spec",
      "options": [
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ]
    },
    {
      "name": "hello",
      "options": [
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ]
    },
    {
      "name": "host",
      "options": [
        {
          "name": [
            "--output"
          ],
          "args": [
            {
              "name": "choice",
              "suggestions": [
                "csv",
                "json",
                "table"
              ]
            }
          ]
        },
        {
          "name": [
            "--debug"
          ],
          "exclusiveOn": [
            "--no-debug"
          ]
        },
        {
          "name": [
            "--no-debug"
          ],
          "exclusiveOn": [
            "--debug"
          ]
        },
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ],
      "args": [
        {
          "name": "text"
        }
      ]
    },
    {
      "name": "hosts",
      "options": [
        {
          "name": [
            "--columns"
          ],
          "isRepeatable": true,
          "args": [
            {
              "name": "text"
            }
          ]
        },
        {
          "name": [
            "--output"
          ],
          "args": [
            {
              "name": "choice",
              "suggestions": [
                "csv",
                "json",
                "table"
              ]
            }
          ]
        },
        {
          "name": [
            "--debug"
          ],
          "exclusiveOn": [
            "--no-debug"
          ]
        },
        {
          "name": [
            "--no-debug"
          ],
          "exclusiveOn": [
            "--debug"
          ]
        },
        {
          "name": [
            "--index"
          ],
          "exclusiveOn": [
            "--no-index"
          ]
        },
        {
          "name": [
            "--no-index"
          ],
          "exclusiveOn": [
            "--index"
          ]
        },
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ],
      "args": [
        {
          "name": "text",
          "isVariadic": true
        }
      ]
    },
    {
      "name": "rack",
      "options": [
        {
          "name": [
            "--output"
          ],
          "args": [
            {
              "name": "choice",
              "suggestions": [
                "csv",
                "json",
                "table"
              ]
            }
          ]
        },
        {
          "name": [
            "--debug"
          ],
          "exclusiveOn": [
            "--no-debug"
          ]
        },
        {
          "name": [
            "--no-debug"
          ],
          "exclusiveOn": [
            "--debug"
          ]
        },
        {
          "name": [
            "--help"
          ],
          "description": "Show this message and exit."
        }
      ],
      "args": [
        {
          "name": "text"
        }
      ]
    }
  ]
}

export default completionSpec;


``` 

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Volumes/workplace/EC2LeeQueryTools/src/EC2LeeQueryTools
  - exe-path: /Users/legoodri/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: a72900117d464a298e15d4ecf7ad3e10
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Volumes/workplace/EC2LeeQueryTools/src/EC2LeeQueryTools/.venv/bin:/Users/legoodri/.local/share/rtx/installs/python/3.11.6/bin:/Users/legoodri/.local/share/rtx/installs/node/18.17.1/bin:/Users/legoodri/.local/share/rtx/installs/ruby/3.2.2/bin:/Users/legoodri/.local/share/rtx/installs/ruby/2.7.8/bin:/Users/legoodri/bin:/Users/legoodri/.toolbox/bin:/opt/homebrew/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/legoodri/.local/bin:/Users/legoodri/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: a72900117d464a298e15d4ecf7ad3e10
```
