### DISCUSSION TITLE
Q not working in integrated terminal in Windsurf (fork of VSCode)

### DISCUSSION THREAD

**Discussion by andreasmcdermott** [aws/codewhisperer-command-line-discussions#300] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I used to use Q in the integrated terminal in VSCode. I recently switched to Windsurf (which is a fork of VSCode similar to Cursor). From a user's perspective, the editors are identical with exception for the Windsurf AI features. I would therefore expect that Q would just work, but it doesn't.

### Actual behaviour

Q is not working in Windsurf. Running `q doctor` says everything is good. Running `q restart` has no effect.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:26:56.475228Z (12d ago)"
variant = "full"

[system-info]
os = "macOS 14.7.1 (23H222)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/repos/app-frontend"
cli-path = "/Users/USER/repos/app-frontend"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "VSCode"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.codeium/windsurf/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/USER/repos/backend/bin/aws-vault:/Users/USER/.nvm/versions/node/v18.17.1/bin:/Users/USER/.bun/bin:/Users/USER/repos/backend/bin/aws-vault:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/USER/.codeium/windsurf/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/USER/repos/backend/bin/aws-vault:/Users/USER/.nvm/versions/node/v18.17.1/bin:/Users/USER/.bun/bin:/backend/bin/aws-vault:/Users/USER/.cargo/bin:/Users/USER/.local/bin"
QTERM_SESSION_ID = "f3e0a1c5f3354e828186343ea4dd9946"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
ZDOTDIR = "/Users/USER"
__CFBundleIdentifier = "com.exafunction.windsurf"
```
