### DISCUSSION TITLE
Cinnamon Support

### DISCUSSION THREAD

**Discussion by kzagoris** [aws/codewhisperer-command-line-discussions#301] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The inline window is to be in the position of the cursor.

### Actual behaviour

The inline window is in the top left corner of the left-most monitor. The `q doctor` command outputs:
```
IBus Env Check: unknown desktop, checked environment variables: XDG_CURRENT_DESKTOP: `X-Cinnamon`, XDG_SESSION_DESKTOP: `cinnamon`, GDMSESSION: `cinnamon`
```

### Steps to reproduce

Use the latest Linux Mint with cinnamon in the kitty terminal with ssh shell. 

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (13d ago)"
variant = "full"

[system-info]
chip = "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"
total-cores = 6
memory = "31.27 GB"

[system-info.os.linux]
kernel_version = "6.8.0-49-generic"
id = "linuxmint"
name = "Linux Mint"
pretty_name = "Linux Mint 22"
version_id = "22"
version = "22 (Wilma)"

[environment]
cwd = "/home/USER/Desktop"
cli-path = "/home/USER/Desktop"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "3.7.1"
terminal = "Kitty"
install-method = "unknown"

[env-vars]
DISPLAY = ":0"
PATH = "/home/USER/.local/bin:/home/USER/.nvm/versions/node/v22.11.0/bin:/home/USER/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/USER/.dotnet/tools:/opt/mssql-tools18/bin"
QTERM_SESSION_ID = "e3f0306f12824636a999e7c63842fd67"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
Q_USING_ZSH_AUTOSUGGESTIONS = "1"
SHELL = "/usr/bin/zsh"
TERM = "xterm-kitty"
XDG_CURRENT_DESKTOP = "X-Cinnamon"
XDG_SESSION_DESKTOP = "cinnamon"
XDG_SESSION_TYPE = "x11"
```
