### DISCUSSION TITLE
Auto complete not working unless i run qterm in terminal or add it to my .bash_profile

### DISCUSSION THREAD

**Discussion by somtooo** [aws/codewhisperer-command-line-discussions#302] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Im not getting auto-completions in my terminal; shell is bash.  qdoctor throws error - 
✘ Amazon Q terminal integrations: qterm is not running in this terminal, please try restarting your terminal

 But if i run qterm in the terminal everything starts to work. but i think that is running a subshell or something

### Actual behaviour

nothing happens

### Steps to reproduce

just type "cd " it will not suggest next folder name or just type starting few letter of git command it will not suggest anything

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (13d ago)"
variant = "full"

[system-info]
chip = "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz"
total-cores = 8
memory = "15.34 GB"

[system-info.os.linux]
kernel_version = "6.11.10-300.fc41.x86_64"
id = "fedora"
name = "Fedora Linux"
pretty_name = "Fedora Linux 41 (Workstation Edition)"
version_id = "41"
version = "41 (Workstation Edition)"
variant_id = "workstation"
variant = "Workstation Edition"

[environment]
cwd = "/home/USER/dev-cave/themes/WhiteSur-gtk-theme"
cli-path = "/home/USER/dev-cave/themes/WhiteSur-gtk-theme"
os = "Linux"
shell-path = "/usr/bin/bash"
shell-version = "5.2.32"
install-method = "unknown"

[env-vars]
DISPLAY = ":0"
PATH = "/home/USER/.local/bin:/home/USER/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
SHELL = "/bin/bash"
TERM = "xterm-256color"
XDG_CURRENT_DESKTOP = "GNOME"
XDG_SESSION_DESKTOP = "gnome"
XDG_SESSION_TYPE = "wayland"
XMODIFIERS = "@im=ibus"
```
