### DISCUSSION TITLE
Path does not contain ~/.local/bin

### DISCUSSION THREAD

**Discussion by zemise** [aws/codewhisperer-command-line-discussions#305] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

run ```q doctor``` in ubuntu terminal, there should be no issues 

### Actual behaviour

when i run ```q doctor``` in ubuntu terminal, there show 

✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin
✘ Doctor found errors. Please fix them and try again.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (15d ago)"
variant = "full"

[system-info]
chip = "Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz"
total-cores = 12
memory = "62.64 GB"

[system-info.os.linux]
kernel_version = "5.15.0-117-generic"
id = "ubuntu"
name = "Ubuntu"
pretty_name = "Ubuntu 22.04.5 LTS"
version_id = "22.04"
version = "22.04.5 LTS (Jammy Jellyfish)"

[environment]
cwd = "/home/USER/temp"
cli-path = "/home/USER/temp"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
install-method = "unknown"
in-ssh = true

[env-vars]
PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
SHELL = "/usr/bin/zsh"
TERM = "xterm-256color"
XDG_SESSION_TYPE = "tty"
```
