### DISCUSSION TITLE
where can I set my color of suggestion like: ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'

### DISCUSSION THREAD

**Discussion by BH1SCW** [aws/codewhisperer-command-line-discussions#306] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I can't see the suggestion text , but  if I select the area , it appears, so I think I need to change color

by the way I use Solarized color preset in iterm2 on mac os .

### Actual behaviour

the suggestion text is grey , I cant see it whey using Solarized.

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:26:56.475228Z (25d ago)"
variant = "full"

[system-info]
os = "macOS 15.2.0 (24C101)"
chip = "Apple M1 Pro"
total-cores = 10
memory = "32.00 GB"

[environment]
cwd = "/Users/USER/code/python/keypress/node-project"
cli-path = "/Users/USER/code/python/keypress/node-project"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.MJzZZtOYGB/org.xquartz:0"
PATH = "/Users/USER/code/python/myenv/bin:/Users/USER/.cargo/bin:/opt/homebrew/Cellar/llvm/16.0.6/bin:/opt/homebrew/Cellar/qt/6.5.1_3/bin:/Users/USER/.tst_deploy/slave/bin:/Users/USER/.tst_deploy/server/bin:/Users/USER/.tst_deploy/client/bin:/Users/USER/BackBlaze/golang/go/bin:/Users/USER/bin:/usr/local/opt/llvm/bin:/Users/USER/.local/bin:/usr/local/opt/openssl/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/USER/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin:/usr/local/go/bin:/usr/local/go/bin:/Library/Maven/apache-maven-3.6.1//bin:/opt/homebrew/opt/fzf/bin:/Users/USER/.env_deploy/tst-env/client/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
QTERM_SESSION_ID = "a90677ed2e704d61be49ab26e9cc143d"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/opt/homebrew/bin/zsh"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"
```
