### DISCUSSION TITLE
Don;t work on ubuntu 22.04 on cinnamon desktop

### DISCUSSION THREAD

**Discussion by PakoAraya** [aws/codewhisperer-command-line-discussions#307] [Support ticket]
### Checks

- [X] I ran `q doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `q restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/q-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

my shell work with aws autocomplete statements

### Actual behaviour

❯ q doctor

✘ IBus Env Check: unknown desktop, checked environment variables: XDG_CURRENT_DESKTOP: `X-Cinnamon`, XDG_SESSION_DESKTOP: `cinnamon`, GDMSESSION: `cinnamon`

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with q issue to let us know!

### Environment

```toml
[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:29:46.821159Z (25d ago)"
variant = "full"

[system-info]
chip = "Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz"
total-cores = 2
memory = "3.69 GB"

[system-info.os.linux]
kernel_version = "6.8.0-49-generic"
id = "ubuntu"
name = "Ubuntu"
pretty_name = "Ubuntu 22.04.5 LTS"
version_id = "22.04"
version = "22.04.5 LTS (Jammy Jellyfish)"

[environment]
cwd = "/home/USER"
cli-path = "/home/USER"
os = "Linux"
shell-path = "/usr/bin/zsh"
shell-version = "5.8"
terminal = "Gnome Terminal"
install-method = "unknown"

[env-vars]
DISPLAY = ":1"
GTK_IM_MODULE = "ibus"
PATH = "/home/USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/USER/.local/bin:/home/USER/.fig/bin"
QTERM_SESSION_ID = "923f477b7a854e3f900895d90be2c4a0"
QT_IM_MODULE = "ibus"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.0"
SHELL = "/usr/bin/zsh"
TERM = "xterm-256color"
XDG_CURRENT_DESKTOP = "X-Cinnamon"
XDG_SESSION_DESKTOP = "cinnamon"
XDG_SESSION_TYPE = "x11"
XMODIFIERS = "@im=ibus"
```
