### DISCUSSION TITLE
Wrong popup position in WebStorm console in some cases

### DISCUSSION THREAD

**Discussion by risenxxx** [aws/codewhisperer-command-line-discussions#32] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The suggestions popup follows the caret

### Actual behaviour

The suggestions popup breaks and moves to left-bottom screen corner until window switch (or maybe some other actions)

### Steps to reproduce

1. Open some project in webstorm (A)
2. Type something in console to trigger CodeWhisperer
3. Open some other project in new window (B)
4. Close project B
5. Type something in console to trigger CodeWhisperer

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.2 (23B92)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/risenforces/Desktop/Work/redacted
  - exe-path: /Users/risenforces/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 405f66796973499aa03904fb7810f747
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/risenforces/.volta/bin:/Users/risenforces/Library/pnpm:/Users/risenforces/.yarn/bin:/Users/risenforces/.config/yarn/global/node_modules/.bin:/Users/risenforces/.rye/shims:/Users/risenforces/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/risenforces/.cargo/bin:/Users/risenforces/Desktop/Work/redacted/node_modules/.bin:/Users/risenforces/.local/bin:/Users/risenforces/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - CW_SET_PARENT: 405f66796973499aa03904fb7810f747
```
