### DISCUSSION TITLE
Autohide suggestions in VSCode once terminal tab is switched to a different tab

### DISCUSSION THREAD

**Discussion by 00arpit00** [aws/codewhisperer-command-line-discussions#33] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Suggestions should hide once we switch to a different tab apart from terminal.

### Actual behaviour

Suggestions popup remains there even if tab is switched

https://github.com/aws/codewhisperer-command-line-discussions/assets/17265834/2ea2137f-f81d-4d28-95e5-3d0937ce0816

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/agaarpi
  - exe-path: /Users/agaarpi/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 7618128fe39a4bd0a3a245e65f54231f
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/agaarpi/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 7618128fe39a4bd0a3a245e65f54231f
```
