### DISCUSSION TITLE
Homebrew and Github cli tools do not autocomplete where used with 1password-cli plugins

### DISCUSSION THREAD

**Discussion by afterdesign** [aws/codewhisperer-command-line-discussions#35] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

While typing `brew` or `gh` I would like to get autocompletion.

### Actual behaviour

Completion is not being triggered.

### Steps to reproduce

If you're using 1password add 1password-cli and configure homebrew plugin: https://developer.1password.com/docs/cli/shell-plugins/homebrew

This step changes the `brew` is alias:
```
type brew
brew is an alias for op plugin run -- brew
```

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.2 (23B92)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: ~/Projects/devops
  - exe-path: ~/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 3327b4c41b314aa08dd6c217eced97ad
    - CW_SET_PARENT: 3327b4c41b314aa08dd6c217eced97ad
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: ~/.rbenv/shims:~/go/bin:/opt/homebrew/opt/openjdk/bin:~/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/munki:~/.rbenv/shims:~/go/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:~/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: ~/
    - __CFBundleIdentifier: com.microsoft.VSCode
```
