### DISCUSSION TITLE
Webstorm Terminal Suggestions Wrong Display

### DISCUSSION THREAD

**Discussion by vladcristianmarin** [aws/codewhisperer-command-line-discussions#36] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Terminal autosuggestions box to pop above my cursor

### Actual behaviour

Terminal autosuggestions box pop in the left bottom corner of my screen

### Steps to reproduce

Install Webstorm, integrate CodeWhisperer, enable autosuggestions and use the integrated terminal.
<img width="840" alt="Screenshot 2023-12-06 at 12 19 11" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/74992262/d2470c74-5ca4-4ae8-99cd-b89b8c23484d">

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/vlamarin/Workspace/nela-mobile-app
  - exe-path: /Users/vlamarin/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 0fe2578d46a1411083d5ff5bb3076dad
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/vlamarin/Workspace/nela-mobile-app/node_modules/.bin:/Users/vlamarin/.local/bin:/Users/vlamarin/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - CW_SET_PARENT: 0fe2578d46a1411083d5ff5bb3076dad
```
