### DISCUSSION TITLE
Bug: Incompatible: Requires IDE build 233 or earlier - WebStorm

### DISCUSSION THREAD

**Discussion by costleya** [aws/codewhisperer-command-line-discussions#37] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The CodeWhisperer plugin continues to work after upgrading to the GA release of WebStorm 2023.3.

### Actual behaviour

Plugin auto-disables due to incompatibility.

### Steps to reproduce

1. Have WebStorm 2023.3
2. `cw integrations install input-method` to install plugin, and restart
3. launch IDE

Upgrading the IDE from a previous installation or installing from scratch have the same result.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.1.2 (23B92)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/aaroncostley
  - exe-path: /Users/aaroncostley/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 5bacce7b83cc4d9085f62e068756dd1f
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/aaroncostley/.local/bin:/Users/aaroncostley/Library/Application Support/JetBrains/Toolbox/scripts:/Users/aaroncostley/.dotnet/tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - CW_SET_PARENT: 5bacce7b83cc4d9085f62e068756dd1f
```
