### DISCUSSION TITLE
Shell Integrations display status as a red cross

### DISCUSSION THREAD

**Discussion by GOWxx** [aws/codewhisperer-command-line-discussions#38] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Successfully installed codeWhisperer and integrated it into the shell, display the correct integration status.

### Actual behaviour

![image](https://github.com/aws/codewhisperer-command-line-discussions/assets/12870715/05453358-1169-402d-9a86-90a1bdca6cf1)

<img width="960" alt="image" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/12870715/3638ec91-946d-4c12-8c33-4a5731188d72">

I am a fig user. Today, I uninstalled fig and installed codeWhisperer, then encountered this problem. In another possibly related discussion, I learned to use inspect to view the error message, which appeared at the beginning of the installation.

At present, cw can be used normally in the terminal.

Because I am not sure if the issue is completely consistent with the error in [another discussion("Shell Integrations" still showing the red cross icon #24)](https://github.com/aws/codewhisperer-command-line-discussions/discussions/24), I have started this discussion and added more information, hoping to help the development team and other users.

### Steps to reproduce

I uninstalled fig and then installed codeWhisperer.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.1.2 (23B92)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/gowxx
  - exe-path: /Users/gowxx/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 7a3d39708b0e4890954cd3cea5ab8231
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - DISPLAY: /private/tmp/com.apple.launchd.nh0UFKm8VR/org.xquartz:0
    - PATH: /Users/gowxx/code/unGit/deps/depot_tools:/opt/homebrew/opt/postgresql@15/bin:/Users/gowxx/Library/pnpm:/opt/homebrew/opt/openjdk/bin:/Users/gowxx/.pyenv/shims:/Users/gowxx/.nvm/versions/node/v20.10.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/VMware Fusion.app/Contents/Public:/Users/gowxx/.cargo/bin:/Users/gowxx/.local/bin:/Users/gowxx/Library/Android/sdk/emulator:/Users/gowxx/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 7a3d39708b0e4890954cd3cea5ab8231
```
