### DISCUSSION TITLE
Arrow keys and enter do not work when prompting. Prompts can only be confirmed with the mouse button.

### DISCUSSION THREAD

**Discussion by scannerGT** [aws/codewhisperer-command-line-discussions#41] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Functioning arrow keys and enter when prompting, without using the mouse.

### Actual behaviour

The arrow keys and enter do not work when autocomplete popup appears. Suggested ptions can only be selected and confirmed with the mouse button

### Steps to reproduce

1. Open Terminal.app
2. Type ie. "cw doc" - suggestion popup appears.
3. Try to select suggestion with "Down Arrow" key
4. Try hit "Enter"

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: Apple MacBook Pro 13"
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.2.0 (23C64)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: --- redacted ---
  - exe-path: /Users/scanner/.local/bin/cw
  - install-method: DMG package
  - env-vars:
    - CWTERM_SESSION_ID: de8c7984edb04372ace612369555ad9c
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /opt/homebrew/opt/postgresql@16/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/scanner/.local/bin:/Users/scanner/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: de8c7984edb04372ace612369555ad9c
```
