### DISCUSSION TITLE
Not working with Cursor IDE

### DISCUSSION THREAD

**Discussion by claudfuen** [aws/codewhisperer-command-line-discussions#44] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When typing CW should appear.

### Actual behaviour

When typing CW does not appear.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M3 Max
  - cores: 16
  - mem: 128.00 GB
os-info:
  - macOS 14.2.0 (23C64)
environment:
  - shell: /bin/zsh
  - terminal: cursor
  - cwd: /Users/claudfuen/Documents/Repos/leap-api
  - exe-path: /Users/claudfuen/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.todesktop.230313mzl4w4u92
    - PATH: /Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v15.14.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v15.14.0/bin:/Users/claudfuen/.nvm/versions/node/v15.14.0/bin:/Users/claudfuen/.pyenv/shims:/Users/claudfuen/.pyenv/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.nvm/versions/node/v16.20.2/bin:/Users/claudfuen/.bun/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/claudfuen/.bun/bin:/Users/claudfuen/.nvm/versions/node/v18.19.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/claudfuen/.local/bin
    - SHELL: /bin/zsh
    - CW_SET_PARENT_CHECK: 1
    - ZDOTDIR: /Users/claudfuen
    - CW_TERM: 0.12.0
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: 296d291b1ce1483dab75116c45f767ee
    - CW_SET_PARENT: 296d291b1ce1483dab75116c45f767ee
```
