### DISCUSSION TITLE
Bug: Installing CodeWhisperer broke my zsh setup

### DISCUSSION THREAD

**Discussion by mxstbr** [aws/codewhisperer-command-line-discussions#45] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I installed CodeWhisperer on my MacBook. I expected my ZSH setup to stay the exact same as before.

### Actual behaviour

My custom prompt is gone, the git plugin doesn't work anymore, etc. It's like it's completely ignoring my `.zshrc`:

<img width="1841" alt="CleanShot 2023-12-17 at 12 11 23@2x" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/7525670/6e85286c-a1a7-446f-9491-b41f6f8755ce">

Note how I'm in a git repository, I have the git ZSH plugin installed—and yet the `gst` command (git status) provided by that plugin doesn't work. Nor does my custom prompt show up.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/mxstbr/projects/stellate/fuse.js
  - exe-path: /Users/mxstbr/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 23891d3ad275466283b4dd046076b3f7
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /Users/mxstbr/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mxstbr/.cargo/bin:/Users/mxstbr/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 23891d3ad275466283b4dd046076b3f7
```
