### DISCUSSION TITLE
CodeWhsiper for CLI command clashes with cw

### DISCUSSION THREAD

**Discussion by REBELinBLUE** [aws/codewhisperer-command-line-discussions#46] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

There is an existing popular cloudwatch CLI which also uses the binary named `cw` https://github.com/lucagrulla/cw

### Actual behaviour

Just reporting this as you may, or may not, want to do something about it and use a different name, or discuss with the developer of the other tool

### Steps to reproduce

Install both applications, only the latest one will exist properly

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.2.0 (23C64)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.4/bin/fish
  - terminal: iterm
  - cwd: /Users/stephen.ball
  - exe-path: /Applications/CodeWhisperer.app/Contents/MacOS/cw
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_TERM: 0.12.0
    - PATH: /opt/homebrew/opt/vim/bin:/opt/homebrew/opt/nano/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/findutils/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/gnu-indent/libexec/gnubin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/opt/gnu-which/libexec/gnubin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/opt/gnu-getopt/bin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/mysql-client@5.7/bin:/opt/homebrew/opt/postgresql@12/bin:/opt/homebrew/opt/openssl@1.1/bin:/usr/local/MacGPG2/bin:/Applications/PhpStorm.app/Contents/MacOS:/Applications/DataGrip.app/Contents/MacOS:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/stephen.ball/.local/bin:/Users/stephen.ball/.krew/bin:/Users/stephen.ball/.go/bin:/Users/stephen.ball/.config/composer/vendor/bin:/Users/stephen.ball/.cargo/bin:/Users/stephen.ball/Library/Python/3.9/bin:/Users/stephen.ball/Library/Python/3.10/bin:/Users/stephen.ball/Library/Python/3.11/bin
    - CW_SET_PARENT: w1t0p0:CF5C111B-51D3-41C4-A8D0-2EF1F389FD7E
    - CW_PARENT:
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: a75ae4eafab04e0ea48fabef733b5877
    - SHELL: /opt/homebrew/bin/fish
```
