### DISCUSSION TITLE
Wrong autocomplete position

### DISCUSSION THREAD

**Discussion by simonittensammer** [aws/codewhisperer-command-line-discussions#47] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The suggestion popup is positioned right below the cursor.

### Actual behaviour

The suggestion popup is positioned in the center of the screen.
![Screenshot 2023-12-19 at 07 24 54](https://github.com/aws/codewhisperer-command-line-discussions/assets/38787002/2cbdc655-eacc-46f9-b7d8-e78c209e679d)
![Screenshot 2023-12-19 at 07 28 53](https://github.com/aws/codewhisperer-command-line-discussions/assets/38787002/68d453d0-895b-44ae-85b3-eb6bbcfe2a54)

### Steps to reproduce

Just open any kind of terminal.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/username/WebstormProjects/projectname/ionic
  - exe-path: /Users/username/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: c9050994084a49b280d0a77e0db3bd8c
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/username/.pyenv/shims:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/apache-maven-3.8.6/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/username/WebstormProjects/projectname/ionic/node_modules/.bin:/Users/username/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - CW_SET_PARENT: c9050994084a49b280d0a77e0db3bd8c
```
