### DISCUSSION TITLE
Alias of 'q' triggers 'cw ai' unintentionally

### DISCUSSION THREAD

**Discussion by shipitsteven** [aws/codewhisperer-command-line-discussions#48] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

`q` should run my alias of `cd ..`

### Actual behaviour

`q` runs `cw ai` and triggers Text to Shell

### Steps to reproduce

- set alias in .zshrc for `q`
- `alias q='cd ..'`
- Enable CW for Terminal and iTerm
- cd to any folder and use command `q` alias
- Translate Text to Shell shows up instead of `cd ..`

Feel free to ping me for details steeeve@amazon.com

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.6.2 (22G320)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/steeeve/iOS/RabbitiOSApp/src/NavigationiOSSDK
  - exe-path: /Users/steeeve/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: c5a180af43a34548be334d9fccf6a8dc
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /opt/homebrew/opt/ruby@2.7/bin:/opt/homebrew/opt/node@14/bin:/Users/steeeve/.pyenv/shims:/Users/steeeve/bin:/usr/local/bin:/Users/steeeve/Library/Android/sdk/platform-tools:/Users/steeeve/Library/Android/sdk/emulator:/Users/steeeve/Library/Android/sdk/tools:/Users/steeeve/.toolbox/bin::/Users/steeeve/.toolbox/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/ruby@2.7/bin:/opt/homebrew/opt/node@14/bin:/Users/steeeve/bin:/usr/local/bin:/Users/steeeve/Library/Android/sdk/platform-tools:/Users/steeeve/Library/Android/sdk/emulator:/Users/steeeve/Library/Android/sdk/tools:/Users/steeeve/.toolbox/bin::/Users/steeeve/.toolbox/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/steeeve/.cargo/bin:/Users/steeeve/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: c5a180af43a34548be334d9fccf6a8dc
```
