### DISCUSSION TITLE
Autocomplete prompt window not showing

### DISCUSSION THREAD

**Discussion by lukejans** [aws/codewhisperer-command-line-discussions#49] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

when typing in a terminal window I would expect for the autocomplete window to pop up as I'm typing so I can scroll through the list of commands or options and autocomplete. I have went through all the checks and have run `cw doctor` & `cw restart`.

### Actual behaviour

The actual behaviour of the autocomplete prompt window is between working and not doing anything. it will pull up autocomplete but for to random options for the `cw` command. Other than that the window does not appear at all.

https://github.com/aws/codewhisperer-command-line-discussions/assets/91230392/f8fe5303-4edd-4940-9840-800218fe3599

### Steps to reproduce

I'm unsure how to recreate this but the last thing I did before I noticed it stopped working was edit my spaceshiprc.zsh config file.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.1.2 (23B92)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/lukejans
  - exe-path: /Users/lukejans/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 8b5eeee1bb3740a093282c71ef771c65
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/lukejans/.nvm/versions/node/v18.12.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/lukejans/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - CW_SET_PARENT: 8b5eeee1bb3740a093282c71ef771c65
```
