### DISCUSSION TITLE
Shell intergration bug on macOs.

### DISCUSSION THREAD

**Discussion by eveeifyeve** [aws/codewhisperer-command-line-discussions#50] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Should be installed.

### Actual behaviour

Code whisper is saying it's not installed.

The reason could be this issue at #38.

### Steps to reproduce

1. install code whisper 
2. install the shell extension when you click install it installs it to my ~/.zshrc.
3. Restart your laptop and it will show it's not installed.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.2.0 (23C5055b)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/eveeify
  - exe-path: /Users/eveeify/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: d0d7a83443e6460e9e1e9d903b5d265c
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/eveeify/.jenv/shims:/Users/eveeify/.jenv/bin:/Users/eveeify/.jenv/bin:/Users/eveeify/.bun/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/eveeify/.cargo/bin:/Users/eveeify/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/eveeify/.rvm/bin:/Users/eveeify/.docker/bin.
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: d0d7a83443e6460e9e1e9d903b5d265c
```
