### DISCUSSION TITLE
Not working in Mac iTerm2, no pop-ups/completions.

### DISCUSSION THREAD

**Discussion by Justin-Johnson** [aws/codewhisperer-command-line-discussions#51] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expected pop-up completion when using 'cd' and other CLI commands.

### Actual behaviour

No pop-ups appear.

### Steps to reproduce

Just typing CLI commands like 'cd' or 'git' followed by space.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.6.1 (22G313)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/justinj
  - exe-path: /Users/justinj/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 5fda58eb1e0440a788be2aca6b09bb51
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - DISPLAY: /private/tmp/com.apple.launchd.RTm7U8fsQO/org.macosforge.xquartz:0
    - PATH: /Users/justinj/gems/bin:/Users/justinj/.gem/ruby/2.6.0/bin:/Users/justinj/Develop/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/justinj/.gem/ruby/2.6.0/bin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/justinj/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 5fda58eb1e0440a788be2aca6b09bb51
```
