### DISCUSSION TITLE
Typo in cw prompt

### DISCUSSION THREAD

**Discussion by maishsk** [aws/codewhisperer-command-line-discussions#54] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I ran `cw login` and expected the prompt 
and was prompted with options

### Actual behaviour

The option to use a Builder ID has a typo

Select action · Sing up or Sign in with Email (Builder ID)

It should be **Sign** up not **Sing** up 

### Steps to reproduce

cw login 

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.6.3 (22G436)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/maishsk
  - exe-path: /Users/maishsk/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: aef6e39f36824aaaa4ea7bd0bae55b0e
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /usr/local/sbin:/Users/maishsk/.pyenv/shims:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/sbin:/Users/maishsk/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: aef6e39f36824aaaa4ea7bd0bae55b0e
```
