### DISCUSSION TITLE
Enable history completions (like in Fig)

### DISCUSSION THREAD

**Discussion by imkonsowa** [aws/codewhisperer-command-line-discussions#57] [Feature request]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I start typing a command in iTerm, Fig shows the suggested line from my history, I expect CW to have the same functionality.

### Actual behaviour

No history suggestions.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.2.1 (23C71)
```
