### DISCUSSION TITLE
Code Whisperer plugin on Android Studio force enables Screen Reader option

### DISCUSSION THREAD

**Discussion by jihadnaji** [aws/codewhisperer-command-line-discussions#58] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expected that upon enabling the CodeWhisperer plugin in the Android Studio, it would only activate the features CW feature directly related to terminal. The plugin should function independently without altering other unrelated settings within the IDE, especially those related to accessibility features like the Screen Reader.

### Actual behaviour

Upon activating the CodeWhisperer plugin for the Android Studio terminal, it inadvertently enabled the "Support screen readers" option located in "Appearance & Behavior > Appearance > Accessibility". This unexpected behavior leads to the deactivation of the quick documentation feature when hovering over code within the code editor. This is counterproductive as it affects the overall efficiency of coding by removing a critical feature used frequently during development. Please see the attached screenshot for a visual depiction of the issue.

<img width="1012" alt="Screenshot 2024-01-13 at 12 11 01 PM" src="https://github.com/aws/codewhisperer-command-line-discussions/assets/19856312/a7da068c-3efa-424e-b91f-306d53be6b87">

### Steps to reproduce

1. Open Android Studio and ensure that the CodeWhisperer (CW) plugin is installed.
2. Navigate to "Appearance & Behavior > Appearance > Accessibility" in the Android Studio settings.
3. Ensure that the "Support screen readers" option is disabled.
4. Now, go to the plugin settings in Android Studio and enable the CodeWhisperer plugin.
5. After enabling the CW plugin, restart the IDE to apply the changes.
6. Once the IDE restarts, return to "Appearance & Behavior > Appearance > Accessibility" and observe that the "Support screen readers" option has been automatically re-enabled.
7. To further test, disable the CW plugin, ensure the "Support screen readers" option is turned off, and then restart the IDE. Observe that in this case, the "Support screen readers" option remains disabled, indicating the issue is directly tied to the activation of the CW plugin.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: MacBook Pro
  - model-id: Mac15,7
  - chip-id: Apple M3 Pro
  - cores: 12
  - mem: 36.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/jihadnaji
  - exe-path: /Users/jihadnaji/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 59f2ce3684544bb8b2e9c868421cae9c
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jihadnaji/Development/flutter/bin:/opt/homebrew/bin:/Users/jihadnaji/.pub-cache/bin:/Users/jihadnaji/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: 59f2ce3684544bb8b2e9c868421cae9c
```
