### DISCUSSION TITLE
Support Rio terminal

### DISCUSSION THREAD

**Discussion by Todomir** [aws/codewhisperer-command-line-discussions#59] [Feature request]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expected CodeWhisperer CLI to work with Rio terminal. Rio is a fast, 24-bit color, multiplatform terminal. 

### Actual behaviour

✘ Terminal support: Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run `cw issue`

  __CFBundleIdentifier: com.raphaelamorim.rio

### Steps to reproduce

- Install and setup CW and CW CLI
- Install [Rio terminal](https://raphamorim.io/rio/docs/install/macos)

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/abno
  - exe-path: /Users/abno/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 1eb22fcdfb334e85a63403b2876e1f8f
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/abno/miniconda3/bin:/Users/abno/miniconda3/condabin:/Users/abno/Library/pnpm:/Users/abno/.nvm/versions/node/v20.10.0/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/abno/.local/bin:/Users/abno/.orbstack/bin
    - SHELL: /bin/zsh
    - TERM: rio
    - __CFBundleIdentifier: com.raphaelamorim.rio
    - CW_SET_PARENT: 1eb22fcdfb334e85a63403b2876e1f8f
```
