### DISCUSSION TITLE
cw ai returns "error: service error"

### DISCUSSION THREAD

**Discussion by espuuks** [aws/codewhisperer-command-line-discussions#6] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Translation of text to bash command(s).

### Actual behaviour

Displays "error: service error"

### Steps to reproduce

Can reproduce consistently with any text input and after multiple cw restarts.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /usr/local/Cellar/bash/5.2.21/bin/bash
  - terminal: terminal
  - cwd: /Users/espuuks
  - exe-path: /Users/espuuks/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - CWTERM_SESSION_ID: f6be1dc592704c9ca8c591441003c026
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - CW_TERM: 0.12.0
    - CW_SET_PARENT_CHECK: 1
    - PATH: /Users/espuuks/.nvm/versions/node/v12.2.0/bin:/Users/espuuks/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Users/espuuks/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/espuuks/.cargo/bin:/Users/espuuks/.rvm/gems/ruby-2.5.1/bin:/Users/espuuks/.rvm/gems/ruby-2.5.1@global/bin:/Users/espuuks/.rvm/rubies/ruby-2.5.1/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/espuuks/.local/bin:/Users/espuuks/.rvm/bin:/Users/espuuks/.rvm/bin
```
