### DISCUSSION TITLE
Uses region as AZ

### DISCUSSION THREAD

**Discussion by stephenmsachs** [aws/codewhisperer-command-line-discussions#60] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Use `--region us-west-2`.

### Actual behaviour

$ cw ai "show me all ip addresses of p5.48xlarge instances in us-west-2"

  Shell · aws ec2 describe-instances --filters "Name=instance-type,Values=p5.48xlarge" "Name=availability-zone,Values=us-west-2" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.6.3 (22G436)
environment:
  - shell: /bin/bash
  - terminal: terminal
  - cwd: /Users/stesachs/Downloads
  - exe-path: /Users/stesachs/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - CWTERM_SESSION_ID: 83d5cfdb58a5480287be019083721f10
    - CW_TERM: 0.13.0
    - PATH: /Users/stesachs/.docker/bin:/Users/stesachs/.docker/bin:/Users/stesachs/.rbenv/shims:/Users/stesachs/.poetry/bin:/Users/stesachs/.toolbox/bin:/Users/stesachs/.pyenv/shims:/Users/stesachs/virtualenvs/default/bin:/Users/stesachs/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/stesachs/.local/bin:/Users/stesachs/.toolbox/bin:/Users/stesachs/.local/bin:/usr/local/opt/fzf/bin:/usr/local/bin:/Users/stesachs/.cargo/bin:/Users/stesachs/code.amazon.com/Git-review-tools/bin:/usr/local//Cellar/binutils/2.40/bin/:/Users/stesachs/workplace/SimClient-Sc/build/SimClient-Sc/SimClient-Sc-1.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-target/release
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT_CHECK: 1
    - DISPLAY: /private/tmp/com.apple.launchd.xtTQN2GspL/org.xquartz:0
```
