### DISCUSSION TITLE
Support Warp Terminal

### DISCUSSION THREAD

**Discussion by randiskull** [aws/codewhisperer-command-line-discussions#61] [Feature request]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Expected CodeWhisperer to work with [Warp Terminal](https://www.warp.dev/c)

### Actual behaviour

![Screenshot 2024-01-17 at 12 49 08 PM](https://github.com/aws/codewhisperer-command-line-discussions/assets/13487540/5483f5b1-ef20-4823-bf5c-61ab7daf5d56)

cw doctor

✘ CodeWhisperer Integration: WarpTerminal is not supported

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with cw issue to let us know!

### Steps to reproduce

1/ Install CodeWhisperer
2/ Launch Warp Terminal
3/ run `cw doctor`

### Environment

```yaml
*NOTE* username replaced with $USER

CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/$USER/workingdir
  - exe-path: /Users/$USER/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - PATH: /Users/$USER/bin:/Users/$USER/Library/Python/3.11/bin:/Users/$USER/.rd/bin:/opt/homebrew/opt/texinfo/bin:/Users/$USER/.amplify/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/Users/$USER/bin:/Users/$USER/go/bin:/usr/local/git/bin:/Users/$USER/.composer/vendor/bin:/Users/$USER/bin:/Users/$USER/.toolbox/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Caskroom/miniforge/base/condabin:/Users/$USER/.pyenv/shims:/Users/$USER/.pyenv/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/$USER/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - CW_SET_PARENT_CHECK: 1
    - CW_SET_PARENT:
```
