### DISCUSSION TITLE
Bug: Custom completion specs not working

### DISCUSSION THREAD

**Discussion by TrentBrown** [aws/codewhisperer-command-line-discussions#62] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

It works to put a custom Fig spec in ~/Library/Application Support/codewhisperer/specs

It works to turn on the "Dev Mode" switch and point the "Specs Folder" at another directory that contains my custom spec.

### Actual behaviour

Putting my custom Fig spec in neither of the two locations works. 

### Steps to reproduce

1. Put a custom Fig spec in either or both of the above locations
2. Configure the Dev Mode "on" and point the path to the correct directory
3. Type the command in iTerm2 and follow with a space character
4. Bring up the debugger with "cw debug devtools autocomplete"
5. Observe that two errors appear in the log:
"Fig.MissingSpecError: No spec found" 
"Fig.ParseArgumentsError: Invalid token array"

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 13.6.1 (22G313)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/trent.brown
  - exe-path: /Users/trent.brown/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 685f4533a4fc4e769498341d15cf66dc
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/trent.brown/.volta/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/trent.brown/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 685f4533a4fc4e769498341d15cf66dc
```
