### DISCUSSION TITLE
IntelliJ IDEA CW CLI plugin incompatible with Build #IU-233.13135.103

### DISCUSSION THREAD

**Discussion by akkadaya** [aws/codewhisperer-command-line-discussions#63] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

CW CLI plugin be compatible with IntelliJ IDEA 2023.3.2 (Ultimate Edition) Build #IU-233.13135.103

### Actual behaviour

IntelliJ IDEA CW CLI plugin is incompatible with Build #IU-233.13135.103

### Steps to reproduce

- Open IntelliJ IDEA
- Go to Settings -> Plugins
- Click on "CodeWhisperer for command line" plugin

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
```
