### DISCUSSION TITLE
Update AWS completion spec (e.g. `aws be` for bedrock)

### DISCUSSION THREAD

**Discussion by FireballDWF** [aws/codewhisperer-command-line-discussions#64] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

"aws be" should complete for bedrock.  "aws b" doesn't contain bedrock as one of the options while 4 other services are listed as options.

### Actual behaviour

no bedrock in dropdown list for "aws b" and no dropdown for "aws be"

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.6.3 (22G436)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/filiatra/local_src/containers-eks/outposts/examples/servers-private-createvpc-createiam-vpcendpoints
  - exe-path: /Users/filiatra/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: f5dd31f36b5a4c8b924f15b3bc48bac6
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/filiatra/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: f5dd31f36b5a4c8b924f15b3bc48bac6
```
