### DISCUSSION TITLE
MacOS Sonoma 14.2.1 has a white CodeWhisperer icon on the icon of Apple in the menu bar

### DISCUSSION THREAD

**Discussion by fynntang** [aws/codewhisperer-command-line-discussions#65] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I hope there is no CodeWhisper icon on the Apple icon

### Actual behaviour

![1705718558890](https://github.com/aws/codewhisperer-command-line-discussions/assets/22270008/11b4dda6-b20a-42c5-8c00-513f4ce7a2df)

### Steps to reproduce

Normal installation already exists, the only action I took was to upgrade macOS, and then it existed. Even after reinstalling, it still exists

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/fynn
  - exe-path: /Users/fynn/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 682a8ab6fb0c460a8607b26603b19c8d
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/0x/Library/pnpm:/opt/homebrew/opt/bison/bin:/Users/0x/.deno/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/0x/.cargo/bin:/Users/0x/.local/bin:/Users/0x/.fig/bin:/Users/0x/Library/Application Support/JetBrains/Toolbox/scripts:/Users/0x/go/bin:/Users/0x/.yarn/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - CW_SET_PARENT: 682a8ab6fb0c460a8607b26603b19c8d
```
