### DISCUSSION TITLE
completions panel disappears

### DISCUSSION THREAD

**Discussion by arobida** [aws/codewhisperer-command-line-discussions#66] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

to work

### Actual behaviour

 when ever the completions panel pops up it immediately disappears

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/arobida
  - exe-path: /Users/arobida/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CW_SET_PARENT_CHECK: 1
    - __CFBundleIdentifier: com.microsoft.VSCode
    - CW_TERM: 0.13.0
    - PATH: /Users/arobida/.bun/bin:/Users/arobida/.composer/vendor/bin:/Users/arobida/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/arobida/.bun/bin:/Users/arobida/.composer/vendor/bin:/Users/arobida/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/arobida/Library/pnpm:/Users/arobida/anaconda3/bin:/Users/arobida/anaconda3/condabin:/Users/arobida/.cargo/bin:/Users/arobida/.local/bin:/Users/arobida/Library/Application Support/JetBrains/Toolbox/scripts:/Users/arobida/Library/Application Support/JetBrains/Toolbox/scripts
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: 4b9f1d17c7314c05bfbddbca3e14a761
    - SHELL: /bin/zsh
    - CW_SET_PARENT: 4b9f1d17c7314c05bfbddbca3e14a761
    - ZDOTDIR: /Users/arobida
```
