### DISCUSSION TITLE
Autocomplete is not working for justfiles

### DISCUSSION THREAD

**Discussion by igr-rs** [aws/codewhisperer-command-line-discussions#68] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

After typing `just<space>` I would expect a popup with Justfile receipts.

### Actual behaviour

After typing `just<space>` the mentioned popup appears for a brief moment and then disappears, to be replaced by the tri running dots.

### Steps to reproduce

type "just<space>" in the folder with a justfile.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.4/bin/fish
  - terminal: iterm
  - cwd: /Users/igors/prj/red/hardenize
  - exe-path: /Users/igors/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: a50b35f65de64477bc3847924e87772e
    - CW_PARENT: 
    - PATH: /Users/igors/.pyenv/bin:/usr/local/sbin:/usr/local/opt/libpq/bin:/Users/igors/.config/nvm/20.10.0/bin:/Users/ispasic/.pyenv/bin:/opt/homebrew/opt/ruby/bin:/Users/ispasic/.config/nvm/16.17.0/bin:/Users/igr/.config/nvm/14.16.0/bin:/Users/igr/.config/nvm/12.16.3/bin:/Users/ispasic/.yarn/bin:/Users/igors/.cabal/bin:/Users/igors/.pyenv/shims:/Users/igors/.cabal/bin:/Users/igors/Library/Java/JavaVirtualMachines/temurin-17.0.9/Contents/Home/bin:/Users/igors/flutter/bin:/Users/igors/google-cloud-sdk/bin:/Users/igors/.cargo/bin:/Users/igors/bin:./:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Users/igors/.local/bin:/Users/ispasic/.ghcup/bin:/Users/igors/.ghcup/bin
    - CW_TERM: 0.13.0
    - CW_SET_PARENT: w0t4p0:19BCA724-F525-4DE8-9D76-F23EABCDB596
    - SHELL: /opt/homebrew/bin/fish
    - __CFBundleIdentifier: com.googlecode.iterm2
```
