### DISCUSSION TITLE
Autocomplete does not work after a restart

### DISCUSSION THREAD

**Discussion by aud1ence** [aws/codewhisperer-command-line-discussions#72] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

The autocomplete is working well

### Actual behaviour

After restarting the machine, we don't see autocomplete suggestions, even though they used to work well

### Steps to reproduce

restart the machine

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/macbook
  - exe-path: /Users/macbook/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: ae7d5f9891c34581b7a58fa5f503c48e
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /Users/macbook/.nvm/versions/node/v18.16.1/bin:/Users/macbook/.rbenv/shims:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/macbook/.cargo/bin:/Users/macbook/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: ae7d5f9891c34581b7a58fa5f503c48e
```
