### DISCUSSION TITLE
CW not working in ITerm with powerlevel10k theme

### DISCUSSION THREAD

**Discussion by neerajjain92** [aws/codewhisperer-command-line-discussions#76] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

  Autocomplete to work

### Actual behaviour

Autocomplete doesn't work

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.4.0 (23E5180j)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/neerajjain/Projects/Github/gossip-glomers/02-unique-id-generation
  - exe-path: /Users/neerajjain/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 9b5c9cc16b324bfebd7acb8d32b57cb6
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/neerajjain/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 9b5c9cc16b324bfebd7acb8d32b57cb6
```
