### DISCUSSION TITLE
Have to restart cw to get it to work in PHPStorm

### DISCUSSION THREAD

**Discussion by john-shipp** [aws/codewhisperer-command-line-discussions#77] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect cw to be working in PHPStorm without needing to restart cw using `cw restart` every time. Fig worked as expected, cw isn't working in PHPStorm terminal without running `cw restart` every time.

### Actual behaviour

I launch PHPStorm, open the built-in terminal, cw is not functioning. I run `cw doctor` and it says all is well. I run `cw restart` and cw starts working in the PHPStorm terminal. I close PHPStorm, re-open PHPStorm, and cw stops working without running `cw restart` again.

### Steps to reproduce

See other messages for repro. See me if you need more info.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 96.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: intellij-phpstorm
  - cwd: /Users/johnshipp/Projects/fina-fi.com
  - exe-path: /Users/johnshipp/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 8dc16333e6034579aa72dbe87bf2017e
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - PATH: /opt/homebrew/Cellar/php/8.2.7_2/bin:/Users/johnshipp/Library/Application Support/Herd/bin/:/Users/johnshipp/.nvm/versions/node/v18.16.1/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/johnshipp/Library/Application:/Users/johnshipp/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.PhpStorm
    - CW_SET_PARENT: 8dc16333e6034579aa72dbe87bf2017e
```
