### DISCUSSION TITLE
Python Virtual Environment not activating in IDEs with CodeWhisperer installed

### DISCUSSION THREAD

**Discussion by jmfiola** [aws/codewhisperer-command-line-discussions#78] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

With CodeWhisperer installed, when starting up a terminal VSCode or Pycharm, the Python virtual environment is activated.

### Actual behaviour

With CodeWhisperer installed, when starting up a terminal VSCode or Pycharm, the Python virtual environment is not activated.

It still can be activated if you manually run `source .venv/bin/activate`, though.

### Steps to reproduce

1. Have a Pycharm or VScode Python virtual environment that activates automatically when the shell is opened
2. Install CodeWhisperer
3. Observe that the Python virtual environment is no longer automatically activated, but can be activated if you manually run `source .venv/bin/activate`

### Environment

```yaml
CODEWHISPERER-details:
  - 0.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.6.3 (22G436)
environment:
  - shell: /bin/zsh
  - terminal: intellij-pycharm
  - cwd: /Users/jacob.fiola/Work/shield-trifacta
  - exe-path: /Users/jacob.fiola/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 580b7bafd33e4d6b983bd1c9d06d2f1b
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.13.0
    - DISPLAY: /private/tmp/com.apple.launchd.dSOB7SnFQD/org.xquartz:0
    - PATH: /Users/jacob.fiola/.nvm/versions/node/v16.14.0/bin:/usr/local/opt/openjdk@17/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacob.fiola/Documents/arcanist/arcanist/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jacob.fiola/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.pycharm
    - CW_SET_PARENT: 580b7bafd33e4d6b983bd1c9d06d2f1b
```
