### DISCUSSION TITLE
Installing JetBrains integration doesn't work

### DISCUSSION THREAD

**Discussion by rajdtta** [aws/codewhisperer-command-line-discussions#8] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I would expect autocomplete to start working on JetBrains terminals, but it doesn't.

### Actual behaviour

Running `cw integrations install jetbrains` (or `intellij`) and then `cw doctor` (even after `cw restart`) shows the following:

![image](https://i.raj.wtf/imgs/rxP16P6P3gAZ0i0K5MCzkOaIXuK.png)

### Steps to reproduce

- Run `cw integrations install jetbrains` (or `cw integrations install intellij`)
- Run `cw restart`
- Open a JetBrains terminal (in my case, WebStorm). Autocomplete doesn't work
- (Optional) run `cw doctor` to see the "Input Method: Not Installed" message

### Environment

```yaml
CODEWHISPERER-details:
  - 0.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/rajdatta/Documents/Resintel/resintel.nosync
  - exe-path: /Users/rajdatta/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 7dc3cc98889c488d9012c662d35df82e
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.12.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/Users/rajdatta/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - CW_SET_PARENT: 7dc3cc98889c488d9012c662d35df82e
```
