### DISCUSSION TITLE
CW completion doesn't work in VS Code built-in terminal during SSH / Tunnel session

### DISCUSSION THREAD

**Discussion by oskar-gmerek** [aws/codewhisperer-command-line-discussions#85] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I expect that CW completion will be suggested on VS Code SSH and Tunnel sessions the same way like it will during local development. In simple, I would expect CW to work correctly.

### Actual behaviour

During **SSH session** (macOS to macOS) CW autocompletions doesn't works.

`cw doctor` results with:
```py
✘ CodeWhisperer auth: Not authenticated. Please run `cw login`

error: Not authenticated. Please run `cw login`
```

`cw login` results with pop up login window on host machine, but in the same time error appears in terminal:
```py
✔ Select action · Sign up or Sign in with Email (Builder ID)

Confirm the following code in the browser
Code: XYXY-XZXZ

▰▰▱▱▱▱▱ Logging in...error: service error
``` 

CW is logged in both on host and client machines.

During **Tunnel session**  (macOS to macOS). Completions dialog is showing on host machine instead of client machine (where I put cmd) which is useless.

But during Tunnel session `cw doctor` returns:
```py
✔ Everything looks good!

  CodeWhisperer still not working? Run cw issue to let us know!
  ```
  
  And `cw login` returns:
  ```py
  error: Already logged in, please logout with `cw logout` first
  ```

### Steps to reproduce

1. Open VS Code terminal on the client Mac.
2. Connect in VS Code using SSH or Remote Tunnels to the second Mac. (official extensions Remote - SSH or Remote - Tunnels)
3. Open VS Code built-in terminal (it should show host machine terminal during ssh/tunnel session)
4. Try to trigger completion with eg. `cw ` or `cd ` or anything else and look how is not working correctly

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/root/github_mbp/projectX
  - exe-path: /Users/root/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CW_SET_PARENT_CHECK: 1
    - PATH: /Users/root/.local/share/rtx/installs/node/18.16.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/podman/bin:/Users/root/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/remote-cli:/Users/root/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/root/.fig/bin:/Users/root/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/root
    - CW_SET_PARENT:
```
