### DISCUSSION TITLE
Support request: prompts not working in integrated vscode terminal

### DISCUSSION THREAD

**Discussion by MarGustafsson** [aws/codewhisperer-command-line-discussions#86] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

when i type a command i expect suggestions to appear, which it does in my normal terminal app (Iterm2), but not in the terminal inside VS Code.

### Actual behaviour

In vscode terminal nothing appears.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/marcus/Workspace/Zmarta/service-affiliates
  - exe-path: /Users/marcus/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CW_SET_PARENT_CHECK: 1
    - __CFBundleIdentifier: com.microsoft.VSCode
    - CW_TERM: 0.14.1
    - PATH: /usr/local/sbin//Users/marcus/.bun/bin:/opt/homebrew/opt/php@8.0/sbin:/opt/homebrew/opt/php@8.0/bin:/Users/marcus/.nvm/versions/node/v20.9.0/bin:/Users/marcus/.deno/bin:/opt/homebrew/bin:/usr/local/sbin//Users/marcus/.orbstack/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/marcus/.cargo/bin:/usr/local/sbin//Users/marcus/.bun/bin:/opt/homebrew/opt/php@8.0/sbin:/opt/homebrew/opt/php@8.0/bin:/Users/marcus/.nvm/versions/node/v20.9.0/bin:/Users/marcus/.deno/bin:/opt/homebrew/bin:/usr/local/sbin//Users/marcus/.cargo/bin:/Users/marcus/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM: xterm-256color
    - CWTERM_SESSION_ID: 0d59ec5c0e074f578a0fb9c2596a71c1
    - SHELL: /bin/zsh
    - CW_SET_PARENT: 0d59ec5c0e074f578a0fb9c2596a71c1
    - ZDOTDIR: /Users/marcus
```
