### DISCUSSION TITLE
Support request: Error to install

### DISCUSSION THREAD

**Discussion by giancarlosisasi** [aws/codewhisperer-command-line-discussions#88] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

Should install without errors

### Actual behaviour

There is the output when I run `cw doctor`

````bash
❯ cw doctor

● /Users/myuser/.config/fish/conf.d/00_fig_pre.fish does not exist: No such file or directory (os error 2)
● /Users/myuser/.config/fish/conf.d/99_fig_post.fish does not exist: No such file or directory (os error 2)
✔ Everything looks good!

  CodeWhisperer still not working? Run cw issue to let us know!
````

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: alacritty
  - cwd: /Users/myuser
  - exe-path: /Users/myuser/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 52a8a91c2a4543f2a6e689dd4b7c0c92
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: org.alacritty
    - CW_SET_PARENT: 52a8a91c2a4543f2a6e689dd4b7c0c92
```
