### DISCUSSION TITLE
Can't import scripts from Fig

### DISCUSSION THREAD

**Discussion by xwal** [aws/codewhisperer-command-line-discussions#90] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

before I can run `fig run reset-launchpad` to execute my scripts. but now I can't.

### Actual behaviour

execute my scripts.

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/user
  - exe-path: /Users/user/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 29f5e2797af445488821b9cf5becd216
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Users/user/.rbenv/shims:/Users/user/.pyenv/shims:/Users/user/.nvm/versions/node/v16.19.1/bin:/opt/homebrew/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 29f5e2797af445488821b9cf5becd216
```
