### DISCUSSION TITLE
Support request: autocomplete not working after update from fig

### DISCUSSION THREAD

**Discussion by StoyKK** [aws/codewhisperer-command-line-discussions#92] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

i expected to have it working like fig did just 5 minutes before....

### Actual behaviour

nothing happens

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.6.4 (22G513)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/stoyk
  - exe-path: /Users/stoyk/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 0c324ad3f3434475a17a582dc98f03a3
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - DISPLAY: /private/tmp/com.apple.launchd.OfeyKqMg1B/org.xquartz:0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/stoyk/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 0c324ad3f3434475a17a582dc98f03a3
```
