### DISCUSSION TITLE
`cw integrations install input-method` just opens Keyboard Settings on MacOS

### DISCUSSION THREAD

**Discussion by gwenwindflower** [aws/codewhisperer-command-line-discussions#93] [Support ticket] [answered]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

It should install the input-method integration for Kitty.

### Actual behaviour

It just opens the Keyboard Settings panel and hangs indefinitely.

### Steps to reproduce

- Install codewhisperer via Homebrew.
- Set up and sign in.
- Install shell integrations, etc.
- Open Kitty, run `cw integrations install input-method`

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.3.0 (23D56)
environment:
  - shell: /bin/zsh
  - terminal: kitty
  - cwd: /Users/winnie
  - exe-path: /Users/winnie/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: c2ce9fe59f2f46abb1ead0be72392144
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Users/winnie/.bun/bin:/Users/winnie/.pyenv/shims:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/winnie/.cargo/bin:/Users/winnie/.gem/ruby/2.6.0/bin:/Users/winnie/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/Applications/SnowSQL.app/Contents/MacOS:/Users/winnie/.poetry/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Applications/kitty.app/Contents/MacOS:/Users/winnie/.local/bin:/Users/winnie/.orbstack/bin:/opt/homebrew/opt/fzf/bin:/Users/winnie/go/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: net.kovidgoyal.kitty
    - CW_SET_PARENT: c2ce9fe59f2f46abb1ead0be72392144
```
