### DISCUSSION TITLE
Support request: php artisan autocomplete is not working correctly

### DISCUSSION THREAD

**Discussion by fang-wei-jie** [aws/codewhisperer-command-line-discussions#99] [Support ticket]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

When I typed `php artisan`, it should continue to provide suggestion to other laravel commands. 

### Actual behaviour

The recommendation just stopped at `php artisan` only. 

https://github.com/aws/codewhisperer-command-line-discussions/assets/74292746/db3cba04-c4b4-4f4d-bc1d-3e7e6ed227cd

### Steps to reproduce

1. Change to a Laravel project directory
2. Start typing `php artisan`
3. Suggestion would stop right there. 

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/weijie/Projects/bukku-api
  - exe-path: /Users/weijie/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: b4d3ba294c53493fb3d85c9897df6b71
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Users/weijie/opt/anaconda3/bin:/Users/weijie/opt/anaconda3/condabin:/Users/weijie/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/weijie/Library/Python/3.9/bin:/opt/homebrew/opt/php@8.0/sbin:/opt/homebrew/opt/php@8.0/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/weijie/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - CW_SET_PARENT: b4d3ba294c53493fb3d85c9897df6b71
```
